### ISSUE TITLE
[Bug] Error 1130: Host '10.131.0.28' is not allowed to connect to this MariaDB server

### ISSUE THREAD

**Issue by djjudas21** [mariadb-operator/mariadb-operator#1005]
**Describe the bug**

I have deployed a MariaDB Galera Cluster with MaxScale on OpenShift and used the CRs to create some Databases, Users and Grants. The Operator log is full of repeating error messages like this (`10.131.0.28` is the operator pod IP) 

```
Error 1130: Host '10.131.0.28' is not allowed to connect to this MariaDB server
``` 

I've included examples of Database, User and Grant but I think it's the same fundamental error in each case. This also occurs for every namespace on the cluster that has CRs for these resources (about 40 of them).

### Database

```
{"level":"error","msg":"Error reconciling SQL resource","controller":"database","controllerGroup":"k8s.mariadb.com","controllerKind":"Database","Database":{"name":"web-test","namespace":"web-test"},"namespace":"web-test","name":"web-test","resource":"web-test","error":"1 error occurred:\n\t* Error 1130: Host '10.131.0.28' is not allowed to connect to this MariaDB server\n\n","stacktrace":"github.com/mariadb-operator/mariadb-operator/pkg/controller/sql.(*SqlReconciler).retryResult\n\t/app/pkg/controller/sql/controller.go:139\ngithub.com/mariadb-operator/mariadb-operator/pkg/controller/sql.(*SqlReconciler).Reconcile\n\t/app/pkg/controller/sql/controller.go:111\ngithub.com/mariadb-operator/mariadb-operator/internal/controller.(*DatabaseReconciler).Reconcile\n\t/app/internal/controller/database_controller.go:51\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Reconcile\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:116\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:303\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:263\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:224"}
```

### Grant

```
{"level":"error","msg":"Error reconciling SQL resource","controller":"grant","controllerGroup":"k8s.mariadb.com","controllerKind":"Grant","Grant":{"name":"web-test","namespace":"web-test"},"namespace":"web-test","name":"web-test","resource":"web-test","error":"1 error occurred:\n\t* Error 1130: Host '10.131.0.28' is not allowed to connect to this MariaDB server\n\n","stacktrace":"github.com/mariadb-operator/mariadb-operator/pkg/controller/sql.(*SqlReconciler).retryResult\n\t/app/pkg/controller/sql/controller.go:139\ngithub.com/mariadb-operator/mariadb-operator/pkg/controller/sql.(*SqlReconciler).Reconcile\n\t/app/pkg/controller/sql/controller.go:111\ngithub.com/mariadb-operator/mariadb-operator/internal/controller.(*GrantReconciler).Reconcile\n\t/app/internal/controller/grant_controller.go:56\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Reconcile\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:116\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:303\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:263\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:224"}
```

### User

```
{"level":"error","msg":"Error reconciling SQL resource","controller":"user","controllerGroup":"k8s.mariadb.com","controllerKind":"User","User":{"name":"web-test","namespace":"web-test"},"namespace":"web-test","name":"web-test","resource":"web-test","error":"1 error occurred:\n\t* Error 1130: Host '10.131.0.28' is not allowed to connect to this MariaDB server\n\n","stacktrace":"github.com/mariadb-operator/mariadb-operator/pkg/controller/sql.(*SqlReconciler).retryResult\n\t/app/pkg/controller/sql/controller.go:139\ngithub.com/mariadb-operator/mariadb-operator/pkg/controller/sql.(*SqlReconciler).Reconcile\n\t/app/pkg/controller/sql/controller.go:111\ngithub.com/mariadb-operator/mariadb-operator/internal/controller.(*UserReconciler).Reconcile\n\t/app/internal/controller/user_controller.go:58\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Reconcile\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:116\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:303\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:263\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:224"}
```

If I connect to the database directly, I can see that the Database, User and Grant do already exist - so the error is not with adding them, but with the reconciler checking that they exist. Maybe the query rate from the Operator to the database is too high, or too many simultaneous connections open?

```
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 7511131
Server version: 11.4.3-MariaDB-ubu2404 mariadb.org binary distribution

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> use web-test;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

MariaDB [web-test]> select USER from mysql.user where USER='web-test';
+----------+
| User     |
+----------+
| web-test |
+----------+
1 row in set (0.001 sec)

MariaDB [web-test]> show grants for 'web-test'@'%';
+--------------------------------------------------------------------------------------------------------------------------------------+
| Grants for web-test@%                                                                                                                |
+--------------------------------------------------------------------------------------------------------------------------------------+
| GRANT USAGE ON *.* TO `web-test`@`%` IDENTIFIED BY PASSWORD '*AA3E6B2D76186392AF935C637DE014862DEA58B9' WITH MAX_USER_CONNECTIONS 20 |
| GRANT ALL PRIVILEGES ON `web-test`.* TO `web-test`@`%`                                                                               |
+--------------------------------------------------------------------------------------------------------------------------------------+
2 rows in set (0.000 sec)
```

**Expected behaviour**
I expect the reconciler to be able to connect reliably to the database to ensure these resources are created

**Steps to reproduce the bug**

1. Install the Operator from OLM
2. Deploy a MariaDB Galera Cluster closely based on [mariadb_galera_maxscale.yaml](https://github.com/mariadb-operator/mariadb-operator/blob/main/examples/manifests/mariadb_galera_maxscale.yaml)
3. Add resources like the examples here:

```yaml
apiVersion: k8s.mariadb.com/v1alpha1
kind: Database
metadata:
  name: web-test
spec:
  mariaDbRef:
    name: production
    namespace: mariadb
  characterSet: utf8
  collate: utf8_general_ci
  cleanupPolicy: Delete
  requeueInterval: 30s
  retryInterval: 5s
```

```yaml
apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: web-test
spec:
  mariaDbRef:
    name: production
    namespace: mariadb
  passwordSecretKeyRef:
    name: mariadb-password
    key: password
  maxUserConnections: 20
  host: "%"
  cleanupPolicy: Delete
  requeueInterval: 30s
  retryInterval: 5s
```

```yaml
apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: web-test
spec:
  mariaDbRef:
    name: production
    namespace: mariadb
  privileges:
    - "ALL PRIVILEGES"
  database: web-test
  table: "*"
  username: web-test
  grantOption: false
  host: "%"
  cleanupPolicy: Delete
  requeueInterval: 30s
  retryInterval: 5s
```

**Environment details**:
- Kubernetes version: v1.29
- Kubernetes distribution: OpenShift v4.16.16
- mariadb-operator version: 0.35.1
- Galera data-plane version (init and agent): [Version number]
- Install method: OLM

**Additional context**

cc: @mariadb-pieterhumphrey
