### ISSUE TITLE
[Bug] Backup compress: file pointer not closed correctly

### ISSUE THREAD

**Issue by johanjk** [mariadb-operator/mariadb-operator#1007]
### Documentation
- [x] I acknowledge that I have read the relevant [documentation](https://github.com/mariadb-operator/mariadb-operator/tree/main/docs).

### Describe the bug

When a backup finishes compressing, the file pointer to the file _(`*.gzip.sql.tmp`)_ is not closed before it is moved _(`*.gzip.sql`)_ leading to a file system panic on filesystems not supporting rename of open files.

<details>
  <summary>logs:</summary>

Backup pod logs:

```jsonc
{
  "level": "error",
  "ts": 1730208338.7464154,
  "msg": "error compressing file",
  "path": "backup.2024-10-29T13:19:26Z.gzip.sql",
  "error": "rename /backup/backup.2024-10-29T13:19:26Z.gzip.sql.tmp /backup/backup.2024-10-29T13:19:26Z.gzip.sql: operation not supported",
  "stacktrace": "
  github.com/mariadb-operator/mariadb-operator/cmd/backup.init.func1
    /app/cmd/backup/main.go:117
  github.com/spf13/cobra.(*Command).execute
    /go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:989
  github.com/spf13/cobra.(*Command).ExecuteC
    /go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1117
  github.com/spf13/cobra.(*Command).Execute
    /go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1041
  main.main
    /app/cmd/controller/main.go:415
  runtime.main
    /usr/local/go/src/runtime/proc.go:272"
}
```

`gke-gcsfuse-sidecar` logs:

```jsonc
{
  "timestamp": {
    "seconds": 1730208325,
    "nanos": 533063832
  },
  "severity": "ERROR",
  "message": "Rename: operation not supported, cannot rename open file \"backup.2024-10-29T13:19:26Z.gzip.sql.tmp\": operation not supported"
}
{
  "timestamp": {
    "seconds": 1730208325,
    "nanos": 552161431
  },
  "severity": "ERROR",
  "message": "fuse: *fuseops.RenameOp error: operation not supported"
}
```
</details>

### Expected behaviour

When doing file operations like `os.Rename`, the file should no longer be open.

### Steps to reproduce the bug

Create a backup using `gcs-fuse`:

```yaml
apiVersion: k8s.mariadb.com/v1alpha1
kind: Backup
metadata:
  name: db-backup
spec:
  podMetadata:
    annotations:
      gke-gcsfuse/volumes: "true"
  storage:
    volume:
      csi:
        driver: gcsfuse.csi.storage.gke.io
        volumeAttributes:
          bucketName: <bucket>
          mountOptions: "implicit-dirs"
          gcsfuseLoggingSeverity: warning
  compression: gzip
  # [...]
```

### Environment details

- Kubernetes version: `1.30`
- Kubernetes distribution: `GKE`
- mariadb-operator version: `0.35.1`
- Install method: `helm`
