### ISSUE TITLE
[Bug] DB gets deleted on redeploy

### ISSUE THREAD

**Issue by bennyvar77** [mariadb-operator/mariadb-operator#1011]
**Documentation**
- [x] I acknowledge that I have read the relevant [documentation](https://github.com/mariadb-operator/mariadb-operator/tree/main/docs).

**Describe the bug**
I have deployed a maria db as follows
```
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-password
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
type: Opaque
data:
  root-password: bWFyaWFwYXNzd29yZA==  # echo -n 'mariapassword'|base64
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb
spec:
  rootPasswordSecretKeyRef:
    name: mariadb-password
    key: root-password
    generate: true

  username: mariadb
  passwordSecretKeyRef:
    name: mariadb-password
    key: root-password
    generate: true
  database: mariadb

  port: 3306

  storage:
    size: 1Gi

  myCnf: |
    [mariadb]
    bind-address=*
    default_storage_engine=InnoDB
    binlog_format=row
    innodb_autoinc_lock_mode=2
    innodb_buffer_pool_size=1024M
    max_allowed_packet=256M

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      memory: 1Gi
```
After deploying, i have added a new table to the mariadb db
![image](https://github.com/user-attachments/assets/2be048a7-d2ad-4104-a6cb-0129ead3b586)

If i remove the deployment and redeploy it, the new table will be gone
![image](https://github.com/user-attachments/assets/5904a26f-6f85-4f07-8194-9c9e549c184c)

**Expected behaviour**
The removal and redeployment should not delete the db

**Steps to reproduce the bug**
1. use the manifest above to deploy a maria db
2. Create a table in the mariadb db
3. remove the deployment
4. redeploy and check whether the newly created table still exist

**Environment details**:
- Kubernetes version: [v1.29.7]
- Kubernetes distribution: [AKS]
- mariadb-operator version: [0.35.1]
- Galera data-plane version (init and agent): [nil]
- Install method: [static manifests]

**Additional context**
I use ArgoCD for deployment.
