### ISSUE TITLE
[Bug] error reconciling in TemplateReconciler: error getting MariaDB

### ISSUE THREAD

**Issue by djjudas21** [mariadb-operator/mariadb-operator#1014]
**Describe the bug**

I have deployed MariaDB Operator into the `mariadb` namespace, and then used it to deploy a Galera cluster also into the `mariadb` namespace.

```
[jonathan@latitude wordpress]$ kubectl get mariadb -n mariadb
NAME      READY   STATUS    PRIMARY POD   AGE
mariadb   True    Running   mariadb-0     24h
```

Then, in the `wordpress` namespace I have created Database, User and Grant CRs (it's a disposable password). Am I correct that the `passwordSecretKeyRef` should reference a Secret in the same namespace as the CR?

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: mariadb
  namespace: wordpress
data:
  password: YjZmNTA5YmM2ZmVkNjFjMmY0MmQwNjM4NmUwMDZhMGM=
```
```yaml
apiVersion: k8s.mariadb.com/v1alpha1
kind: Database
metadata:
  name: wordpress
  namespace: wordpress
spec:
  mariaDbRef:
    name: mariadb
  characterSet: utf8
  collate: utf8_general_ci
```
```yaml
apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: wordpress
  namespace: wordpress
spec:
  mariaDbRef:
    name: mariadb
  passwordSecretKeyRef:
    name: mariadb
    key: password
  host: "%"
```
```yaml
apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: wordpress
  namespace: wordpress
spec:
  mariaDbRef:
    name: mariadb
  privileges:
    - "ALL PRIVILEGES"
  database: "wordpress"
  table: "*"
  username: wordpress
  grantOption: false
  host: "%"
```

The Operator is reporting repeated errors like this, the SQL resources do not get created.

```
{"level":"error","ts":1730322087.9639723,"msg":"Reconciler error","controller":"database","controllerGroup":"k8s.mariadb.com","controllerKind":"Database","Database":{"name":"wordpress","namespace":"wordpress"},"namespace":"wordpress","name":"wordpress","reconcileID":"67ef9e2a-dc43-458e-ac61-e1f9fa401ce4","error":"error reconciling in TemplateReconciler: error getting MariaDB: 1 error occurred:\n\t* MariaDB.k8s.mariadb.com \"mariadb\" not found\n\n","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:316\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:263\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:224"}
{"level":"error","ts":1730322178.5263636,"msg":"Reconciler error","controller":"grant","controllerGroup":"k8s.mariadb.com","controllerKind":"Grant","Grant":{"name":"wordpress","namespace":"wordpress"},"namespace":"wordpress","name":"wordpress","reconcileID":"d3657527-878c-4257-b707-3f413b85fea2","error":"error reconciling in TemplateReconciler: error getting MariaDB: 1 error occurred:\n\t* MariaDB.k8s.mariadb.com \"mariadb\" not found\n\n","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:316\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:263\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:224"}
{"level":"error","ts":1730322180.7637274,"msg":"Reconciler error","controller":"user","controllerGroup":"k8s.mariadb.com","controllerKind":"User","User":{"name":"wordpress","namespace":"wordpress"},"namespace":"wordpress","name":"wordpress","reconcileID":"71642ef7-5c00-4c58-b352-e2b9f5cc2851","error":"error reconciling in TemplateReconciler: error getting MariaDB: 1 error occurred:\n\t* MariaDB.k8s.mariadb.com \"mariadb\" not found\n\n","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:316\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:263\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:224"}
```
It seems like the Operator can't locate the MariaDB instance `mariadb` but I can't figure out why.

This is a MicroK8s cluster with RBAC enabled.

**Expected behaviour**

**Steps to reproduce the bug**

1. Deploy a Galera cluster called `mariadb` in the `mariadb` namespace
2. Deploy some CRs in a different namespace
3. Observe those CRs don't get reconciled

**Environment details**:
- Kubernetes version: v1.31.1
- Kubernetes distribution: MicroK8s
- mariadb-operator version: 0.35.1
- Galera data-plane version (init and agent): [Version number]
- Install method: helm

**Comment by djjudas21** [comment]
This one was user error. I forgot to specify the namespace in the `mariaDbRef`. Fixed by amending to:

```yaml
spec:
  mariaDbRef:
    name: mariadb
    namespace: mariadb
```
