### ISSUE TITLE
[Bug] statefulset and pod are into Not ready state

### ISSUE THREAD

**Issue by Ludea** [mariadb-operator/mariadb-operator#1020]
**Documentation**
- [x] I acknowledge that I have read the relevant [documentation](https://github.com/mariadb-operator/mariadb-operator/tree/main/docs).

**Describe the bug**

I follow the readme, I deploy mariadb.yaml, check mariadb pod / statefulset state and it is into `Not Ready` state

**Expected behaviour**

Pod and statefulset in Ready state

**Steps to reproduce the bug**

1. Install operator and crd into its own namespace
2. apply examples/manifests/config/mariadb-auth.yaml, mariadb-configmap.yaml and mariadb-secret.yaml into same namespace as operator
3. apply examples/manifests/mariadb.yaml into same namespace

**Debug information**
- Related object events:
logs from created pod:
```
Readiness probe failed: Error 1045 (28000): access denied for user 'root'@'localhost' (using password: YES)
```

**Environment details**:
- Kubernetes version: 1.31.1-k3s1
- Kubernetes distribution: k3s
- mariadb-operator version: 0.35.1
- Install method: helm

**Additional context**

I use argocd to deploy operator and crd

**Comment by Ludea** [comment]
more logs from pods:.
```
Normal   Pulled     97s (x3 over 2m47s)  kubelet            Container image "docker-registry1.mariadb.com/library/mariadb:11.4.3" already present on machine
  Normal   Created    97s (x3 over 2m47s)  kubelet            Created container mariadb
  Normal   Started    97s (x3 over 2m47s)  kubelet            Started container mariadb
  Warning  Unhealthy  97s (x6 over 2m22s)  kubelet            Liveness probe failed: ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
  Warning  Unhealthy  97s (x6 over 2m22s)  kubelet            Readiness probe failed: ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
  Normal   Killing    97s (x2 over 2m12s)  kubelet            Container mariadb failed liveness probe, will be restarted
  Warning  Unhealthy  97s (x2 over 2m12s)  kubelet            Readiness probe failed: ERROR 2002 (HY000): Can't connect to local server through socket '/run/mysqld/mysqld.sock' (2)
```

**Comment by angelocorreia27** [comment]
Hi @Ludea 

I'm facing the exact same issue with similar cluster characteristics. Were you able to resolve it, and if so, could you share how you fixed it? Any guidance would be greatly appreciated!

Thanks in advance.

**Comment by Ludea** [comment]
I still get issue
for workaround I use [minimal example](https://github.com/mariadb-operator/mariadb-operator/blob/main/examples/manifests/mariadb_minimal.yaml) but it's not a solution for prod

**Comment by mmontes11** [comment]
> Readiness probe failed: Error 1045 (28000): access denied for user 'root'@'localhost' (using password: YES)

This means that the `Secret` that holds the root password differs from the root password internal state available in the PVCs. Delete the PVCs and recreate the MariaDB resource.

For production, make sure you pin the root password by providing a `Secret` yourself, instead of relying in an auto-generated password.

**Comment by tedli** [comment]
Hi all,

I run into the same issue. My case is because of the poor performance storage.
It takes too long to init the db ('[Note] [Entrypoint]: Initializing database files'), then the probes failed, the pod got killed.
However, since it's not been completely initialized, privileges haven't been granted. Then turned into this issue.

By alter probes delay to a larger period, I got this fixed.

```yaml
apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb
spec:
  rootPasswordSecretKeyRef:
    name: mariadb-root
    key: password
    generate: true
  username: lalala
  database: lalala
  passwordSecretKeyRef:
    name: mariadb-password
    key: password
    generate: true
  storage:
    size: 8Gi
    storageClassName: localpv
  myCnf: |
    [mariadb]
    bind-address=*
    default_storage_engine=InnoDB
    binlog_format=row
    innodb_autoinc_lock_mode=2
    innodb_buffer_pool_size=4096M
    innodb_lock_wait_timeout=900
    innodb_log_file_size=1024M
    max_allowed_packet=256M
  tolerations:
  - key: node-role.kubernetes.io/control-plane
    operator: Equal
    effect: NoSchedule
  livenessProbe:  # <-- enlarge these delay periods
    initialDelaySeconds: 60
  readinessProbe:
    initialDelaySeconds: 60
  startupProbe:
    initialDelaySeconds: 60
```
