### ISSUE TITLE
[Bug] MariaDB pods crash after set `rootEmptyPassword` to `true`

### ISSUE THREAD

**Issue by kos-team** [mariadb-operator/mariadb-operator#1021]
**Documentation**
- [x] I acknowledge that I have read the relevant [documentation](https://github.com/mariadb-operator/mariadb-operator/tree/main/docs).

**Describe the bug**

In our test environment, we set the `rootEmptyPassword` to `true`. However, the MariaDB pods cannot be initialized correctly due to the error ```"msg":"Error getting environment variables","error":"MariadbRootPassword: missing required value: MARIADB_ROOT_PASSWORD"``` 

**Expected behaviour**

We want to see the mariadb pods are initialized correctly and then running.

**Steps to reproduce the bug**

1. Apply a CR with more than `1` replicas and `rootEmptyPassword` enabled, for example:
```
apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb-min
spec:
  rootEmptyPassword: true
  storage:
    size: 1Gi
    storageClassName: standard
    resizeInUseVolumes: true
    waitForVolumeResize: true
  galera:
    enabled: true
  replicas: 3
```

**Debug information**
- Related object events:
```bash
kubectl get events --field-selector involvedObject.name=<mariadb-resource-name>
kubectl get events --field-selector involvedObject.name=<backup-resource-name>
kubectl get events --field-selector involvedObject.name=<restore-resource-name>
```
13s         Normal    Created     pod/mariadb-min-1   Created container init
12s         Normal    Started     pod/mariadb-min-1   Started container init
12s         Warning   BackOff     pod/mariadb-min-1   Back-off restarting failed container init in pod mariadb-min-1_default(8b3c2a50-511d-4a5c-a41d-932629a5a26a)

**Environment details**:
- Kubernetes version: v1.29
- Kubernetes distribution: KIND
- mariadb-operator version: 0.35.1
- Install method: [helm, OLM, or static manifests]: helm

**Additional context**

I think the issue happens in the init containers of mariadb pods when there are more than `1` replicas.
