### ISSUE TITLE
[Bug] MariaDB operator does not roll update the cluster when users update Galera `providerOptions` and `sst`

### ISSUE THREAD

**Issue by kos-team** [mariadb-operator/mariadb-operator#1022]
**Documentation**
- [x] I acknowledge that I have read the relevant [documentation](https://github.com/mariadb-operator/mariadb-operator/tree/main/docs).

**Describe the bug**
We created a MariaDB cluster with Galera enabled. Later, we want to change the Galera configurations. However, after updating the Galera configurations, the operator does not rolling update the changes. In the container, the `etc/mysql/mariadb.conf.d/0-galera.cnf` is not updated. If some pods crash and restart, the updates are applied to them causing inconsistent configuration.

**Expected behaviour**

We want to see that after changing the Galera configurations, the operator automatically rolling updates the MariaDB cluster so that the cluster runs with the desired configurations.

**Steps to reproduce the bug**

1. Apply a CR with `spec.galera` enabled, for example:
```
apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: test-cluster
spec:
  connection:
    healthCheck:
      interval: 10s
      retryInterval: 3s
    params:
      parseTime: 'true'
    secretName: connection-mariadb
    secretTemplate:
      key: dsn
  database: mariadb
  env:
  - name: TZ
    value: SYSTEM
  galera:
    enabled: true
    primary:
      automaticFailover: true
  myCnf: '[mariadb]

    bind-address=*

    default_storage_engine=InnoDB

    binlog_format=row

    innodb_autoinc_lock_mode=2

    innodb_buffer_pool_size=1024M

    max_allowed_packet=256M

    '
  passwordSecretKeyRef:
    key: password
    name: mariadb
  podDisruptionBudget:
    maxUnavailable: 50%
  port: 3306
  replicas: 3
  resources:
    limits:
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 128Mi
  rootPasswordSecretKeyRef:
    key: root-password
    name: mariadb
  securityContext:
    allowPrivilegeEscalation: false
  service:
    type: ClusterIP
  storage:
    resizeInUseVolumes: true
    size: 1Gi
    storageClassName: standard
    waitForVolumeResize: true
  suspend: false
  timeZone: UTC
  updateStrategy:
    type: ReplicasFirstPrimaryLast
  username: mariadb
```
2. Update the `spec.galera.providerOptions ` or `spec.galera.sst`:
```
apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: test-cluster
spec:
  connection:
    healthCheck:
      interval: 10s
      retryInterval: 3s
    params:
      parseTime: 'true'
    secretName: connection-mariadb
    secretTemplate:
      key: dsn
  database: mariadb
  env:
  - name: TZ
    value: SYSTEM
  galera:
    enabled: true
    sst: rsync
    providerOptions:
      gcs.fc_limit: '64'
  myCnf: '[mariadb]

    bind-address=*

    default_storage_engine=InnoDB

    binlog_format=row

    innodb_autoinc_lock_mode=2

    innodb_buffer_pool_size=1024M

    max_allowed_packet=256M

    '
  passwordSecretKeyRef:
    key: password
    name: mariadb
  podDisruptionBudget:
    maxUnavailable: 50%
  port: 3306
  replicas: 3
  resources:
    limits:
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 128Mi
  rootPasswordSecretKeyRef:
    key: root-password
    name: mariadb
  securityContext:
    allowPrivilegeEscalation: false
  service:
    type: ClusterIP
  storage:
    resizeInUseVolumes: true
    size: 1Gi
    storageClassName: standard
    waitForVolumeResize: true
  suspend: false
  timeZone: UTC
  updateStrategy:
    type: ReplicasFirstPrimaryLast
  username: mariadb
```

**Environment details**:
- Kubernetes version: v1.29
- Kubernetes distribution: KIND
- mariadb-operator version: 0.35.1
- Install method: [helm, OLM, or static manifests]: helm

**Additional context**

The inconsistent `sst` and `providerOptions` might cause severe problems as in the [documentation](https://mariadb.com/kb/en/mariabackup-sst-method/), it mentions `"For an SST to work properly, the donor and joiner node must use the same SST method. "`
