### ISSUE TITLE
[Bug] MariaDB operator cannot recover the cluster if one of the pods crashes during the bootstrapping

### ISSUE THREAD

**Issue by kos-team** [mariadb-operator/mariadb-operator#1023]
**Documentation**
- [x] I acknowledge that I have read the relevant [documentation](https://github.com/mariadb-operator/mariadb-operator/tree/main/docs).

**Describe the bug**
We deployed a 3-node MariaDB cluster. When the cluster was bootstrapping, one of the pod crashed. It kept restarting and crashing. Finally, it fell into `CrashLoopBackOff` and never went healthy. The pod crashed with the following error message `[ERROR] WSREP: It may not be safe to bootstrap the cluster from this node. It was not the last one to leave the cluster and may not contain all the updates.`

**Expected behaviour**

We expect the pod recovers from crash and the entire cluster runs normally.

**Steps to reproduce the bug**

1. Apply a CR with 3 or more replicas, for example:
```
apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: test-cluster
spec:
  connection:
    healthCheck:
      interval: 10s
      retryInterval: 3s
    params:
      parseTime: 'true'
    secretName: connection-mariadb
    secretTemplate:
      key: dsn
  database: mariadb
  env:
  - name: TZ
    value: SYSTEM
  galera:
    enabled: true
    primary:
      automaticFailover: true
  livenessProbe:
    exec:
      command:
      - bash
      - -c
      - mariadb -u root -p"${MARIADB_ROOT_PASSWORD}" -e "SELECT 1;"
    initialDelaySeconds: 20
    periodSeconds: 5
    timeoutSeconds: 5
  myCnf: '[mariadb]

    bind-address=*

    default_storage_engine=InnoDB

    binlog_format=row

    innodb_autoinc_lock_mode=2

    innodb_buffer_pool_size=1024M

    max_allowed_packet=256M

    '
  passwordSecretKeyRef:
    key: password
    name: mariadb
  podDisruptionBudget:
    maxUnavailable: 50%
  port: 3306
  readinessProbe:
    exec:
      command:
      - bash
      - -c
      - mariadb -u root -p"${MARIADB_ROOT_PASSWORD}" -e "SELECT 1;"
    initialDelaySeconds: 20
    periodSeconds: 5
    timeoutSeconds: 5
  replicas: 3
  resources:
    limits:
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 128Mi
  rootPasswordSecretKeyRef:
    key: root-password
    name: mariadb
  securityContext:
    allowPrivilegeEscalation: false
  service:
    type: ClusterIP
  storage:
    resizeInUseVolumes: true
    size: 1Gi
    storageClassName: standard
    waitForVolumeResize: true
  suspend: false
  timeZone: UTC
  updateStrategy:
    type: ReplicasFirstPrimaryLast
  username: mariadb
```
2. Crash one of the pods.

**Environment details**:
- Kubernetes version: v1.29
- Kubernetes distribution: KIND
- mariadb-operator version: 0.35.1
- Install method: [helm, OLM, or static manifests]: helm
