### ISSUE TITLE
[Feature] Add Support for restartPolicy in InitContainers, SidecarContainers, and main containers

### ISSUE THREAD

**Issue by georgelazaroff** [mariadb-operator/mariadb-operator#1050]
**Is your feature request related to a problem? Please describe.**

Currently, the MariaDB Operator does not allow specifying individual restartPolicy values for initContainers, sidecarContainers, or the main MariaDB container. This limitation makes it difficult to control restart behavior for specific container types.

Our Use Case: We want to use an initContainer to dynamically update the my.cnf file (e.g., changing max_connections or other runtime parameters). The initContainer should restart independently (restartPolicy: Always) if its task fails, without impacting the running MariaDB container. However, since the MariaDB Operator doesn't support container-level restartPolicy, any failure in the initContainer can unnecessarily disrupt the main MariaDB container or require a full pod restart.

Without this feature, we cannot reliably update runtime configurations without introducing downtime or manual intervention.

**Describe the solution you'd like**

Extend the MariaDB CRD to allow specifying the restartPolicy for:

initContainers: Ability to set a restartPolicy (e.g., Always or OnFailure) for init containers. This would allow us to use an initContainer to modify the my.cnf file dynamically (e.g., updating max_connections) at runtime, retrying on failure without restarting the entire pod or the main MariaDB container.

sidecarContainers: Allow sidecars (e.g., monitoring agents, log shippers) to have an independent restartPolicy (e.g., Always) to restart without disrupting the main MariaDB container.

Main MariaDB Container: Enable restartPolicy (e.g., OnFailure) for the primary MariaDB container, ensuring it only restarts on failure while keeping other containers unaffected.

```YAML
spec:
  initContainers:
    - name: config-updater
      restartPolicy: Always
      command:
        - sh
        - -c
        - |
          if grep -q '^max_connections=4000$' /etc/mysql/conf.d/my.cnf; then
            sed -i 's/^max_connections=4000$/max_connections=4100/' /etc/mysql/conf.d/my.cnf;
          fi
  sidecarContainers:
    - name: monitoring-agent
      restartPolicy: Always
  containers:
    - name: mariadb
      restartPolicy: OnFailure

 ```

**Environment details**:
- Kubernetes version: 1.30
- Kubernetes distribution: EKS
- Install method: helm
- Install flavor: recommended

**Additional context**

***Benefits***

Granular Restart Management: Provides fine-grained control over container lifecycle, improving operational reliability.

Dynamic Updates: Enables us to dynamically update runtime configuration files like my.cnf without restarting the entire pod.

Reduced Downtime: Prevents unnecessary disruptions to the MariaDB container when auxiliary containers (e.g., initContainers or sidecars) encounter failures.
