### ISSUE TITLE
[Bug] Error reconciling Spec: Internal error occurred: failed calling webhook "mmariadb.kb.io": failed to call webhook: Post "https://mariadb-operator-webhook.mariadb-system.svc:443/mutate-k8s-mariadb-com-v1alpha1-mariadb?timeout=10s": dial tcp 172.31.222.11:443: connect: connection refused

### ISSUE THREAD

**Issue by DCx14** [mariadb-operator/mariadb-operator#1060]
hello,

I'm having problems with the mariadb operator.

several of my clusters have this error:

"Error reconciling Spec: Internal error occurred: failed calling webhook "mmariadb.kb.io": failed to call webhook: Post "https://mariadb-operator-webhook.mariadb-system.svc:443/mutate-k8s-mariadb -com-v1alpha1-mariadb?timeout=10s": dial tcp 172.31.222.11:443: connect: connection refused"

I am with the operator in version 0.36.0 and these are HA replication clusters without galera.

I specify that my CNI is antrea and that the namespaces in ingress do not communicate with each other.

A network policy was made to just authorize port 3306

Has anyone ever had the problem?

**Comment by aarnaud** [comment]
Same issue

**Comment by ctrought** [comment]
Is your webhook pod starting up and reaching the "ready" state? And do you by change use cert-manager to generate the webhook certificate?

In my case, the certificate request is being approved but the certificate is not being generated.

```
NAME                            READY   SECRET                          AGE
mariadb-operator-webhook-cert   Ready   mariadb-operator-webhook-cert   11m

NAME                              APPROVED   DENIED   READY   ISSUER                               REQUESTER                                         AGE
mariadb-operator-webhook-cert-1   True                False   mariadb-operator-selfsigned-issuer   system:serviceaccount:cert-manager:cert-manager   11m
```

Looking at the secret where the certificate should be stored, it seems the ownerReference is being set to the MariadbOperator instance. However, cert-manager has a feature flag to enable owner references for certificates which also sets the owner reference this on the secret to the certificate resource.

```
kind: Secret
apiVersion: v1
metadata:
  name: mariadb-operator-webhook-cert'
  labels:
    app.kubernetes.io/instance: mariadb-operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mariadb-operator-webhook
    app.kubernetes.io/version: 0.36.0
    helm.sh/chart: mariadb-operator-0.36.0
    mariadb-operator.io/component: webhook
  ownerReferences:
    - apiVersion: helm.mariadb.mmontes.io/v1alpha1
      kind: MariadbOperator
      name: mariadb-operator
      uid: 7dfcb1c2-78ae-4156-80d5-29c4cc5e85ff
      controller: true
      blockOwnerDeletion: true
```

Cert-manager is throwing the error below due to the existence of the ownerRef set to something other than itself.
```
ion="v1" secret="malibu-ldap-cname-tls" message="unexpected Secret Owner Reference value on Secret --enable-certificate-owner-ref=true"
E0117 18:20:58.049259       1 controller.go:157] "re-queuing item due to error processing" err="failed to apply secret namespace/mariadb-operator-webhook-cert: Secret \"mariadb-operator-webhook-cert\" is invalid: metadata.ownerReference
```

So if you are using cert-manager for the webhook, then it won't be compatible if you [enable the owner ref feature](https://artifacthub.io/packages/helm/cert-manager/cert-manager#enablecertificateownerref-~-bool) in cert-manager. Ideally, the operator would be patched to consider this and either use a different secret name when cert-manager is enabled (and not set owner reference for it) or only set the owner reference if cert-manager is not enabled.
