### ISSUE TITLE
[Feature] Support path prefixes for backup and restore when using storage other than S3

### ISSUE THREAD

**Issue by dale-c-anderson** [mariadb-operator/mariadb-operator#1070]
**Problem encountered**

In the context of developing projects with a lot of simultaneous branches:
* Need to back up multiple environments (prod, staging, occasionally PR branches, occasionally long term branches) to a shared volume, and be able to select which environment's backup to use as a starting point for new environments
* Environments are hosted on AKS (Azure), which doesn't have S3 compatible object storage, so our next best option is to use PVCs backed by file shares

Since operator only puts backups in the root directory of wherever it's writing to, and since it doesn't give the choice of how to name a backup, there doesn't seem to be any way to restore anything but those from a single environment.

**Desired solution**
Similar to how S3 supports path prefixes, it would be great if we could give backups a named prefix to distinguish them from each other:
```yaml
apiVersion: k8s.mariadb.com/v1alpha1
kind: Backup
metadata:
  name: backup
spec:
  mariaDbRef:
    name: mariadb
  compression: gzip
  storage:
    persistentVolumeClaim:
      prefix: foo        # <<<<
      resources:
        requests:
          storage: 100Mi
...
```
Or even make the prefix a higher level item, so it could be supported universally regardless of storage method:

```yaml
apiVersion: k8s.mariadb.com/v1alpha1
kind: Backup
metadata:
  name: backup
spec:
  mariaDbRef:
    name: mariadb
  compression: gzip
  storage:
    prefix: foo         # <<<
    persistentVolumeClaim:
      resources:
        requests:
          storage: 100Mi
...
```

**Consdered Alternatives**
* Considered opening a PR to request adding subPath to the volume mount, but that's problematic in itself since the subpath would already need to exist in the volume, and for our use case, it won't yet be there 99% of the time.
* Considered opening a PR to request support for Azure file storage, but that's probably significantly more effort
* We'd prefer not to add more complexity (eg minio or s3 proxy); those are more potential points of failure, more things to have to keep maintained

**Environment details**:
- Kubernetes version: 1.30
- Kubernetes distribution: AKS
- mariadb-operator version: 0.36.0
- Install method: helm
- Install flavor: recommended

**Comment by Pandry** [comment]
Hi,
I was having a look (for SSE-C) and found this issue.
I think this is [already implemented with the `prefix`](https://github.com/mariadb-operator/mariadb-operator/blob/2497b17434c99c0d3b776a8651dac79df1e2adac/api/v1alpha1/base_types.go#L547):
> Prefix indicates a folder/subfolder in the bucket. For example: mariadb/ or mariadb/backups. A trailing slash '/' is added if not provided.

**Comment by dale-c-anderson** [comment]
@Pandry prefix only applies to S3 storage. This feature request is to have a prefix option when not using s3 storage - i.e. with regular volume claims.

**Comment by Pandry** [comment]
Oh, **other than** S3; I apologize, I don't know but I somehow missed that reading among other S3 stuff

**Comment by dale-c-anderson** [comment]
Yeah I could see how that would be easy to gloss over. I've made the issue title clearer.

**Comment by dale-c-anderson** [comment]
For now, I've worked around this by switching from an azure file share to an azure blobfuse container, which looks something like this:
```yaml
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: my-shared-pv
spec:
  storageClassName: azureblob-fuse-premium
  mountOptions:
    - --subdirectory=my/env/id    # < saved my bacon here
# ...etc...
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc1
spec:
  volumeName: my-shared-pv
  storageClassName: azureblob-fuse-premium
# ...etc...
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: Backup
metadata:
  name: backup
spec:
  storage:
    volume:
      persistentVolumeClaim:
          claimName: pvc1
  securityContext:
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
# ...etc...
```
I am then able to back up to segregated dirs on a shared volume, and choose an arbitrary environment's db to bootstrap from.

This scenario has some drawbacks though:
* Blob storage doesn't seem to support access from non-root containers, so I have to run my backup and bootstrapped mariadb pods as root
* Azure's blobfuse has aggressive cache defaults (which you can disable, for a much more expensive bill), so updates between environments are sometimes painfully slow.

So I'd still love to see at least `subPath` support being added to the persistent volume claim spec of mariadb-operator so I can go back to using file shares, which in general plays a lot nicer with Linux.
