### ISSUE TITLE
[Bug]  MariaDB docker's startup script conflict with `skip_grant_tables: ON` in the configuration

### ISSUE THREAD

**Issue by kos-team** [mariadb-operator/mariadb-operator#1072]
<!--
Bugs should be filed for issues encountered whilst operating mariadb-operator.
Please provide as much detail as possible. 
-->

**Documentation**
- [x] I acknowledge that I have read the relevant [documentation](https://github.com/mariadb-operator/mariadb-operator/tree/main/docs).

**Describe the bug**
We deployed a MariaDB cluster with `skip_grant_tables=ON`, the pod kept crashing and the cluster cannot start up correctly.

**Expected behaviour**
<!--A concise description of what you expected to happen.-->
We expected that the cluster initialized correctly and be in the healthy state.

**Steps to reproduce the bug**

1. Apply a CR with `skip_grant_tables=ON` in `spec.myCnf`, for example:
```
apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: test-cluster
spec:
  connection:
    healthCheck:
      interval: 10s
      retryInterval: 3s
    params:
      parseTime: 'true'
    secretName: connection-mariadb
    secretTemplate:
      key: dsn
  database: mariadb
  env:
  - name: TZ
    value: SYSTEM
  galera:
    enabled: true
  livenessProbe:
    exec:
      command:
      - bash
      - -c
      - mariadb -u root -p"${MARIADB_ROOT_PASSWORD}" -e "SELECT 1;"
    initialDelaySeconds: 20
    periodSeconds: 5
    timeoutSeconds: 5
  metrics:
    enabled: true
  myCnf: |
    [mariadb]
    bind_address = *
    default_storage_engine = InnoDB
    binlog_format = row
    innodb_autoinc_lock_mode = 2
    innodb_buffer_pool_size = 1024M
    max_allowed_packet = 256M
    automatic_sp_privileges = OFF
    skip_grant_tables = ON

  passwordSecretKeyRef:
    key: password
    name: mariadb
  podDisruptionBudget:
    maxUnavailable: 50%
  port: 3306
  readinessProbe:
    exec:
      command:
      - bash
      - -c
      - mariadb -u root -p"${MARIADB_ROOT_PASSWORD}" -e "SELECT 1;"
    initialDelaySeconds: 20
    periodSeconds: 5
    timeoutSeconds: 5
  replicas: 3
  resources:
    limits:
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 128Mi
  rootPasswordSecretKeyRef:
    key: root-password
    name: mariadb
  securityContext:
    allowPrivilegeEscalation: false
  service:
    type: ClusterIP
  storage:
    resizeInUseVolumes: true
    size: 1Gi
    storageClassName: standard
    waitForVolumeResize: true
  suspend: false
  timeZone: UTC
  updateStrategy:
    type: ReplicasFirstPrimaryLast
  username: mariadb
```
2. The second pod kept crashing.

**Error logs**
--------------                                                                                                                                                 
DROP USER IF EXISTS root@'127.0.0.1', root@'::1'                                                                                                              
 --------------                                                                                                                                                                                                                                                                                                                ERROR 1290 (HY000) at line 7: The MariaDB server is running with the --skip-grant-tables option so it cannot execute this statement 

**Root Cause**
During the initialization of the MariaDB Docker container, the `docker-entrypoint.sh` script runs the query `DROP USER IF EXISTS root@'127.0.0.1', root@'::1'`. However, this query fails to execute when `skip-grant-tables` is enabled. As a result, the MariaDB container repeatedly crashes, preventing the entire cluster from being initialized correctly.

**Environment details**:
- Kubernetes version: v1.29
- Kubernetes distribution: KIND
- mariadb-operator version: 0.35.1
- Install method: [helm, OLM, or static manifests]: helm
