### ISSUE TITLE
[Bug] Anti-affinity rules prevents creating backup pod

### ISSUE THREAD

**Issue by peix2** [mariadb-operator/mariadb-operator#1074]
**Documentation**
- [*] I acknowledge that I have read the relevant [documentation](https://github.com/mariadb-operator/mariadb-operator/tree/main/docs).

**Describe the bug**
Going through https://github.com/mariadb-operator/mariadb-operator/blob/main/docs/quickstart.md I got to the point of creating backup. Created backup job/pod based on provided yaml and it can't be scheduled due to its anti-affinity rules
```
...
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/instance
            operator: In
            values:
            - mariadb
        topologyKey: kubernetes.io/hostname
...
```
which I understand as "do not run where mariadb instance is running". Currently my backup job/pod status is:
```
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-12-12T01:48:53Z"
    message: '0/1 nodes are available: 1 node(s) didn''t match pod anti-affinity rules.
      preemption: 0/1 nodes are available: 1 No preemption victims found for incoming
      pod.'
    reason: Unschedulable
    status: "False"
    type: PodScheduled
  phase: Pending
  qosClass: Burstable
```
Whatever logic has been to that applied (which I do not deny) this is preventing running on "lab like" environments which simply will have single node. If this anti-affinity rules are indeed intended then I'd expect mariadb-operator helm chart shall have switch, like "development: true/false" what would change affinity rules so running backup on same node is possible. 

**Expected behaviour**
Possibility to run backup jobs on single-node k8s clusters.
Either:
1. Implement switch for development/production deployment for chart which would alter anti-affinity rules for backup (maybe there are others similar?)
2. Delete anti-affinity rules for backup jobs completely describing in docs consequences or running backup job on same node as instance and providing example of manual implementation of anti-affinity rules to backup CRD yaml. 

**Steps to reproduce the bug**

As described in current Quickstart under: https://github.com/mariadb-operator/mariadb-operator/blob/main/docs/quickstart.md 

**Environment details**:
- Kubernetes version: 1.31.3
- Kubernetes distribution: microk8s
- mariadb-operator version: 0.36.0
- Galera data-plane version (init and agent): no Galera, standalone primary
- Install method: helm
