### ISSUE TITLE
[Bug]  Reconciler error,  error disabling bootstrap in Pod 0

### ISSUE THREAD

**Issue by siwyroot** [mariadb-operator/mariadb-operator#1085]
**Documentation**
- [x] I acknowledge that I have read the relevant [documentation](https://github.com/mariadb-operator/mariadb-operator/tree/main/docs).

After deploying new MariaDB cluster, following error can be observed in `mariadb-operator` logs all the time.
```
{"level":"error","ts":1734443310.1598058,"msg":"Reconciler error","controller":"mariadb","controllerGroup":"k8s.mariadb.com","controllerKind":"MariaDB","MariaDB":{"name":"atds-mariadb","namespace":"atds"},"namespace":"atds","name":"atds-mariadb","reconcileID":"26568f09-f6d4-4f3d-be54-b5a89e1e6bb1","error":"error reconciling Galera: 1 error occurred:\n\t* error disabling bootstrap in Pod 0: error decoding body into error: json: cannot unmarshal number into Go value of type errors.APIError\n\n","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.1/pkg/internal/controller/controller.go:316\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.1/pkg/internal/controller/controller.go:263\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.1/pkg/internal/controller/controller.go:224"}
```

**Expected behaviour**
Operator should reconcile without errors

**Steps to reproduce the bug**

1. Deploy operator
2. Create a new cluster
3. Check operator logs

**Environment details**:
- Kubernetes version: v1.27.13+048520e
- Kubernetes distribution: OpenShift 4.14
- mariadb-operator version: 0.3.6
- Galera data-plane version (init and agent): latest
- Install method: operator

Cluster config:
```
apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb
  namespace: mariadb
spec:
  podSecurityContext:
    runAsUser: 999
    runAsGroup: 999
    fsGroup: 999
  rootPasswordSecretKeyRef:
    name: mariadb-root
    key: password
    generate: true
  storage:
    size: 1Gi
    storageClassName: some-class
    resizeInUseVolumes: true
    waitForVolumeResize: true
    volumeClaimTemplate:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      storageClassName: some-class
  port: 3306
  replicas: 3
  image: mss-docker/devsecops/mariadb:11.4.3
  galera:
    enabled: true
    primary:
      podIndex: 0
      automaticFailover: true
    sst: mariabackup
    availableWhenDonor: false
    galeraLibPath: /usr/lib/galera/libgalera_smm.so
    replicaThreads: 1
    providerOptions:
      gcs.fc_limit: '64'
    agent:
      port: 5555
      kubernetesAuth:
        enabled: true
      gracefulShutdownTimeout: 1s
    recovery:
      enabled: true
      minClusterSize: 50%
      clusterMonitorInterval: 10s
      clusterHealthyTimeout: 30s
      clusterBootstrapTimeout: 10m
      podRecoveryTimeout: 10m
      podSyncTimeout: 3m

    initJob:
      metadata:
        labels:
          sidecar.istio.io/inject: "false"
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          memory: 1Gi
    config:
      reuseStorageVolume: false
      volumeClaimTemplate:
        resources:
          requests:
            storage: 300Mi
        accessModes:
          - ReadWriteOnce


  service:
    type: LoadBalancer
    metadata:
      annotations:
        metallb.universe.tf/loadBalancerIPs: 172.18.0.150
  connection:
    secretName: mariadb-galera-conn
    secretTemplate:
      key: dsn

  primaryService:
    type: LoadBalancer
    metadata:
      annotations:
        metallb.universe.tf/loadBalancerIPs: 172.18.0.160
  primaryConnection:
    secretName: mariadb-galera-conn-primary
    secretTemplate:
      key: dsn

  secondaryService:
    type: LoadBalancer
    metadata:
      annotations:
        metallb.universe.tf/loadBalancerIPs: 172.18.0.161
  secondaryConnection:
    secretName: mariadb-galera-conn-secondary
    secretTemplate:
      key: dsn

  affinity:
    antiAffinityEnabled: true

  tolerations:
    - key: "k8s.mariadb.com/ha"
      operator: "Exists"
      effect: "NoSchedule"

  podDisruptionBudget:
    maxUnavailable: 33%

  updateStrategy:
    type: ReplicasFirstPrimaryLast

  myCnf: |
    [mariadb]
    bind-address=*
    default_storage_engine=InnoDB
    binlog_format=row
    innodb_autoinc_lock_mode=2
    max_allowed_packet=256M

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      memory: 1Gi

  livenessProbe:
    initialDelaySeconds: 20
    periodSeconds: 5
    timeoutSeconds: 5

  readinessProbe:
    initialDelaySeconds: 20
    periodSeconds: 5
    timeoutSeconds: 5

  metrics:
    enabled: false
```
