### ISSUE TITLE
[Bug] HA Replication scheduling same node

### ISSUE THREAD

**Issue by chris102994** [mariadb-operator/mariadb-operator#109]
**Describe the bug**
When trying to use the new replicas feature I am getting an error where pods are scheduled all on the same node using the following configuration:

`mariadb.yaml`
(**Note:** I renamed my mariadb in the below example to avoid any information leakage)
```yaml
apiVersion: mariadb.mmontes.io/v1alpha1
kind: MariaDB
metadata:
  name: mariadb
spec:
  rootPasswordSecretKeyRef:
    name: mariadb-secret
    key: db_root_password
  database: mariadb
  username: admin
  passwordSecretKeyRef:
    name: mariadb-secret
    key: db_password


  connection:
    secretName: mariadb-secret
    secretTemplate:
      key: dsn

  image:
    repository: mariadb
    tag: "10.7.8"
    pullPolicy: IfNotPresent

  port: 3306
  replicas: 3

  replication:
    primary:
      podIndex: 0
      automaticFailover: true
      service:
        type: LoadBalancer
      connection:
        secretName: mariadb-secret
        secretTemplate:
          key: dsn
    replica:
      waitPoint: AfterCommit
      connectionTimeout: 10s
      connectionRetries: 10
      syncTimeout: 10s

  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - topologyKey: "kubernetes.io/hostname"

  volumeClaimTemplate:
    resources:
      requests:
        storage: 1Gi
    storageClassName: local-path
    accessModes:
      - ReadWriteOnce

  tolerations:
    - key: "mariadb.mmontes.io/ha"
      operator: "Exists"
      effect: "NoSchedule"

  podDisruptionBudget:
    minAvailable: "66%"

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 512Mi

  envFrom:
    - configMapRef:
        name: mariadb-cm

  podSecurityContext:
    runAsUser: 0

  securityContext:
    allowPrivilegeEscalation: false
```

It would seem that when the replicas/pv/pvcs are built from the operator that they are all binding on the same node even though the pod config(s) contain:

```yaml
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - topologyKey: "kubernetes.io/hostname"
```

I was able to perform a workaround which isn't great but I suppose works for now until this is officially resolved.

The CRD contains no way to label the replicated pods so I used the default label of `app.kubernetes.io/instance=mariadb` which seems to match `metadata.name` (note: `metadata.labels` didn't match to the pods - probably shouldn't?)

Anyways I wiped everything away and did an initial DB build with:

```yaml
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/instance
                  operator: In
                  values:
                    - mariadb
          topologyKey: "kubernetes.io/hostname"
```

And it worked! However, I was unable to schedule any jobs/backups on any of those 3 nodes.... So I defaulted the config back to:

```yaml
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - topologyKey: "kubernetes.io/hostname"
```

And now since the PV/PVCs were built on different hosts it was now able to replicate across different nodes.

**Expected behaviour**
I would expect that replication with the outlined:

```yaml
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - topologyKey: "kubernetes.io/hostname"
```

would work properly on different hosts.

**Steps to reproduce the bug**
Apply the [sample replication config](https://github.com/mariadb-operator/mariadb-operator/blob/main/config/samples/mariadb_v1alpha1_mariadb_replication.yaml) for a `MariaDB` to your multi-node cluster and see if the pods are all scheduled on different nodes.

**Additional context**
* Nodes do have the `kubernetes.io/hostname` label.
* Metrics had to be disabled for similar scheduling reasons with the replication.
* Cluster is a 3-node rancher k3s cluster.

**Environment details**:
- Kubernetes version: v1.21.5+k3s2
- mariadb-operator version: v0.0.12
- Install method: helm over argocd (chart version 0.12.0)
- Install flavour: recommended
