### ISSUE TITLE
[Bug] MariaDB operator keeps killing the cluster pod when set `max_prepared_stmt_count` to 0 or 1 in `spec.myCnf`

### ISSUE THREAD

**Issue by kos-team** [mariadb-operator/mariadb-operator#1096]
**Documentation**
- [x] I acknowledge that I have read the relevant [documentation](https://github.com/mariadb-operator/mariadb-operator/tree/main/docs).

**Describe the bug**
We deployed a 3-node MariaDB cluster and set `max_prepared_stmt_count` in the `spec.myCnf` to 0 or 1. The pods kept being killed by the mariadb operator with the following error logs in the agent container:

```
error getting cluster status: Error 1461 (42000): Can't create more than max_prepared_stmt_count statements (current value: 1)
```

**Expected behaviour**

We expected our configuration is applied to the mariadb and mariadb running healthily without being killed.

**Steps to reproduce the bug**

1. Apply a CR with `max_prepared_stmt_count=1` in `spec.myCnf`, for example:
```
apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: test-cluster
spec:
  connection:
    healthCheck:
      interval: 10s
      retryInterval: 3s
    params:
      parseTime: 'true'
    secretName: connection-mariadb
    secretTemplate:
      key: dsn
  database: mariadb
  env:
  - name: TZ
    value: SYSTEM
  galera:
    enabled: true
  livenessProbe:
    exec:
      command:
      - bash
      - -c
      - mariadb -u root -p"${MARIADB_ROOT_PASSWORD}" -e "SELECT 1;"
    initialDelaySeconds: 20
    periodSeconds: 5
    timeoutSeconds: 5

  myCnf: '[mariadb]

    bind_address = *

    default_storage_engine = InnoDB

    binlog_format = row

    innodb_autoinc_lock_mode = 2

    innodb_buffer_pool_size = 1024Mi

    max_allowed_packet = 256Mi

    max_prepared_stmt_count = 1


    '
  passwordSecretKeyRef:
    key: password
    name: mariadb
  podDisruptionBudget:
    maxUnavailable: 50%
  port: 3306
  readinessProbe:
    exec:
      command:
      - bash
      - -c
      - mariadb -u root -p"${MARIADB_ROOT_PASSWORD}" -e "SELECT 1;"
    initialDelaySeconds: 20
    periodSeconds: 5
    timeoutSeconds: 5
  replicas: 3
  resources:
    limits:
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 128Mi
  rootPasswordSecretKeyRef:
    key: root-password
    name: mariadb
  securityContext:
    allowPrivilegeEscalation: false
  service:
    type: ClusterIP
  storage:
    resizeInUseVolumes: true
    size: 1Gi
    storageClassName: standard
    waitForVolumeResize: true
  suspend: false
  timeZone: UTC
  updateStrategy:
    type: ReplicasFirstPrimaryLast
  username: mariadb
```
2. Check the logs in the `agent` pod and check the status of mariadb

**Root Cause**
The root cause is that mariadb operator executes a prepared query statement to check the readiness or liveness of the mariadb pod at this line: https://github.com/mariadb-operator/mariadb-operator/blob/main/pkg/sql/sql.go#L545C9-L545C29. If `max_prepared_stmt_count` is set to 0 or 1, MariaDB rejects the query and returns an error. After several failed readiness or liveness checks, the MariaDB Operator interprets the cluster as not ready or unhealthy and subsequently terminates the pods.

**Environment details**:
- Kubernetes version: v1.29
- Kubernetes distribution: KIND
- mariadb-operator version: 0.35.1
- Install method: [helm, OLM, or static manifests]: helm
