### ISSUE TITLE
[Bug] Restore jobs fails to restore backup on NFS

### ISSUE THREAD

**Issue by pinpins** [mariadb-operator/mariadb-operator#1099]
**Documentation**
- [x] I acknowledge that I have read the relevant [documentation](https://github.com/mariadb-operator/mariadb-operator/tree/main/docs).

**Describe the bug**
When running CRD as below
```
apiVersion: k8s.mariadb.com/v1alpha1
kind: Restore
metadata:
  name: db1-mariadb-restore
  namespace: default
spec:
  mariaDbRef:
    name: db1-mariadb
  args:
  - --verbose
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
  targetRecoveryTime: "2024-12-27T10:00:01Z"
  volume:
    nfs:
      path: /volume1/db1_backups
      server: nas.local
```

During processing creating intermediate file 0-backup-target.txt  referencing backup SQL file to be imported e.g. backup.2024-12-27T10:00:01Z.sql

Second container in restore job pod use that file via "cat" to extract actual file name. Issue is it however report an problem 
`mariadb bash: line 1: backup.2024-12-27T10:00:01Z.sql: No such file or directory` 

Issue is that default container path is not /backup mount point, but I guess root, so exact path should be specified in `0-backup-target.txt` file e.g.: 
/backup/backup.2024-12-27T10:00:01Z.sql

**Expected behaviour**
exact path provided in 0-backup-target.txt file .e.g.
`/backup/backup.2024-12-27T10:00:01Z.sql`

**Steps to reproduce the bug**

1. Try Restore CRD with NFS mount point
```
apiVersion: k8s.mariadb.com/v1alpha1
kind: Restore
metadata:
  name: db1-mariadb-restore
  namespace: default
spec:
  mariaDbRef:
    name: db1-mariadb
  args:
  - --verbose
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
  targetRecoveryTime: "2024-12-27T10:00:01Z"
  volume:
    nfs:
      path: /volume1/db1_backups
      server: nas.local
```
