### ISSUE TITLE
Physical backups via `mariabackup` 

### ISSUE THREAD

**Issue by mmontes11** [mariadb-operator/mariadb-operator#11]
MariaDB has its own backup command to perform backups, we should migrate to use it:
- https://mariadb.com/kb/en/mariabackup-overview/

Usage can be found here under the `Creating backups with Mariabackup` section:
- https://hub.docker.com/_/mariadb/

```bash
docker run --user mysql -v some-mariadb-socket:/var/run/mysqld -v some-mariadb-backup:/backup -v /my/own/datadir:/var/lib/mysql --rm mariadb:latest mariabackup --backup --target-dir=/backup
```

**Comment by grooverdan** [comment]
There's still a role for the venerable mysqldump as a logical backup as its a good mitigator for the odd corruption bugs of database tables that mariabackup (and others like aria-hotcopy) physical backup programs don't mitigate. So I'd consider an addition rather than replacement.

**Comment by mmontes11** [comment]
@grooverdan thanks for the clarification, it does sound great. We could extend our CRD so the user could choose the `type` of backup, defaulting to the logical one:
```yaml
apiVersion: database.mmontes.io/v1alpha1
kind: BackupMariaDB
metadata:
  name: backup
spec:
  type: (logical | physical)
  mariaDbRef:
    name: mariadb
  storage:
    persistentVolumeClaim:
      resources:
        requests:
          storage: 100Mi
      storageClassName: standard
      accessModes:
        - ReadWriteOnce
```

**Comment by mmontes11** [comment]
Reopening, see:
- https://github.com/mariadb-operator/mariadb-operator/pull/97

**Comment by mmontes11** [comment]
I've managed to restore a physical backup in a `MariaDB` instance with Galera. Steps followed:

- Provision a `MariaDB` instance with Galera
```yaml
apiVersion: mariadb.mmontes.io/v1alpha1
kind: MariaDB
metadata:
  name: mariadb-galera
spec:
  rootPasswordSecretKeyRef:
    name: mariadb
    key: root-password

  database: mariadb
  username: mariadb
  passwordSecretKeyRef:
    name: mariadb
    key: password

  image:
    repository: mariadb
    tag: "11.0.3"
    pullPolicy: IfNotPresent

  port: 3306

  replicas: 3
     
  galera:
    enabled: true

  volumeClaimTemplate:
    resources:
      requests:
        storage: 1Gi
    accessModes:
      - ReadWriteOnce
  volumes: 
    - name: mariabackup
      persistentVolumeClaim:
        claimName: mariabackup
  volumeMounts: 
    - name: mariabackup
      mountPath: /var/mariadb/backup/
```
- Populate the database using [SqlJobs](https://github.com/mariadb-operator/mariadb-operator/tree/main/examples/manifests/sqljobs)
- Shell into `mariadb-galera-0` and run:
```bash
mariabackup --backup --target-dir=/var/mariadb/backup/ --user=root --password=mariadb
mariabackup --prepare --target-dir=/var/mariadb/backup/
```
- Delete the `MariaDB` instance and its PVCs
- Create another `MariaDB` with a `mariabackup` init container
```yaml
apiVersion: mariadb.mmontes.io/v1alpha1
kind: MariaDB
metadata:
  name: mariadb-galera
spec:
  rootPasswordSecretKeyRef:
    name: mariadb
    key: root-password

  database: mariadb
  username: mariadb
  passwordSecretKeyRef:
    name: mariadb
    key: password

  image:
    repository: mariadb
    tag: "11.0.3"
    pullPolicy: IfNotPresent

  port: 3306

  replicas: 3
     
  galera:
    enabled: true

  # See: https://mariadb.com/kb/en/full-backup-and-restore-with-mariabackup/
  initContainers:
    - image:
        repository: mariadb
        tag: "11.0.3"
        pullPolicy: IfNotPresent
      args:
        - mariabackup 
        - --copy-back 
        - --target-dir=/var/mariadb/backup/

  volumeClaimTemplate:
    resources:
      requests:
        storage: 1Gi
    accessModes:
      - ReadWriteOnce
  volumes: 
    - name: mariabackup
      persistentVolumeClaim:
        claimName: mariabackup
  volumeMounts: 
    - name: mariabackup
      mountPath: /var/mariadb/backup/
```
- Shell into any `MariaDB` `Pod` (`mariadb-galera-0`, `mariadb-galera-1` or `mariadb-galera-2`) and make sure the tables and data are there:
```bash
MariaDB [(none)]> use mariadb;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
MariaDB [mariadb]> show tables;
+-------------------+
| Tables_in_mariadb |
+-------------------+
| repos             |
| stars             |
| users             |
+-------------------+
3 rows in set (0.000 sec)
```
