### ISSUE TITLE
[Bug] Upgrade from 0.0.11 to 0.0.13 causes selector error

### ISSUE THREAD

**Issue by J0n4t4n** [mariadb-operator/mariadb-operator#111]
**Describe the bug**

I upgraded my Operator from Helm version 0.0.11 to 0.0.13 and now all of my MariaDB issues are throwing this error:

```
Error reconciling StatefulSet: StatefulSet.apps "photoview-mariadb" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{"app.kubernetes.io/instance":"photoview-mariadb", "app.kubernetes.io/name":"mariadb"}: `selector` does not match template `labels`
```

The labels in the mentioned Statefulset are the following:
```
  labels:
    app.kubernetes.io/component: database
    app.kubernetes.io/instance: photoview-mariadb
    app.kubernetes.io/name: mariadb
```

I don't see any changes required from my side and don't know how to fix the issue.
**Expected behaviour**

I expect the Sync to work

**Steps to reproduce the bug**

Create MariaDB object in 0.0.11 and upgrade to 0.0.13.

**Additional context**

Here is the MariaDB object I'm using:

```
---
apiVersion: mariadb.mmontes.io/v1alpha1
kind: MariaDB
metadata:
  name: photoview-mariadb
  namespace: photoview
spec:
  rootPasswordSecretKeyRef:
    name: photoview-mariadb
    key: root-password

  database: photoview
  username: photoview
  passwordSecretKeyRef:
    name: photoview-mariadb
    key: password

  image:
    repository: mariadb
    tag: "10.7.4"
    pullPolicy: IfNotPresent

  port: 3306

  volumeClaimTemplate:
    resources:
      requests:
        storage: 5Gi
    storageClassName: longhorn
    accessModes:
      - ReadWriteOnce

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 512Mi
```

**Environment details**:
- Kubernetes version: v1.25.7+k3s1
- mariadb-operator version: 0.0.13
- Install method: helm
- Install flavour: Helm Default

**Comment by mmontes11** [comment]
Hey @J0n4t4n! Thanks for reporting this and sorry for the invonvenience 🙇🏻 🙏🏻 

We've introduced breaking changes in the v0.0.12 in regards to the labels, basically we made a considerable refactor and got rid of the `app.kubernetes.io/component: database` as it wasn't adding any value.

The problem is that your current `StatefulSet`  does have that label in `spec.selector.matchLabels` and the new version of the operator is not providing it on the `spec.template.metadata.labels`, so they don't match as the error says.

Unfortunately,  `spec.selector.matchLabels` is an inmutable field in Kubernetes, so if you try to update it to add `app.kubernetes.io/component: database` and make them match, you will get this error:
```bash
statefulsets.apps "mariadb" was not valid: * spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', 'updateStrategy', 'persistentVolumeClaimRetentionPolicy' and 'minReadySeconds' are forbidden
```
which is the reason why we only update `spec.replicas` and `spec.template` here:
- https://github.com/mariadb-operator/mariadb-operator/blob/main/controllers/mariadb_controller.go#L203-L204

We are releasing a new feature in the `v0.0.14` that allows to provide metadata for the children objects, something that can potentially fix your case:
```yaml
---
apiVersion: mariadb.mmontes.io/v1alpha1
kind: MariaDB
metadata:
  name: photoview-mariadb
  namespace: photoview
spec:
  inheritMetadata:
    labels:
      app.kubernetes.io/component: database
  ...
``` 
See this [resource](https://github.com/mariadb-operator/mariadb-operator/blob/main/config/samples/mariadb_v1alpha1_mariadb_metadata.yaml) as an example. I've managed to fix your case with it.

As an alternative, you can now with the current release (`v0.0.13`) re-create your MariaDB instance without data loss by following this steps:
-  [Backup](https://github.com/mariadb-operator/mariadb-operator/blob/main/config/samples/mariadb_v1alpha1_backup.yaml) your current instance
-  [Bootstrap](https://github.com/mariadb-operator/mariadb-operator/blob/main/config/samples/mariadb_v1alpha1_mariadb_from_backup.yaml) a new instance from the previous backup.

Sorry again for the breaking change, I hope this helps fixing the issue. Stay tuned for the `v0.0.14`  🚀
