### ISSUE TITLE
[Feature] Static NodePort service

### ISSUE THREAD

**Issue by paul-grozav** [mariadb-operator/mariadb-operator#1161]
**Is your feature request related to a problem? Please describe.**

I need to access the cluster through a static port on the control plane nodes. I can specify the `MariaDB` `.spec.service.type: NodePort` but the port is randomly assigned and I need it to be static and predictable, so that I can (for example) recreate the cluster and ensure that clients will be able to reconnect on the same port.

**Describe the solution you'd like**

Might be a solution to define a property in the `.spec.service` that would be used as the `nodePort` in the `Service` object that is created.

**Describe alternatives you've considered**

Maybe  place the new property in the `.spec.service.metadata` object, just like the `LoadBalancer` can ask for an IP through the `metallb.universe.tf/loadBalancerIPs` `metadata.annotation`.

**Environment details**:
- Kubernetes version: v1.30.4
- Kubernetes distribution: Vanilla Kubernetes
- MariaDB Operator version: 0.37.1
- MariaDB Server version: 11.4.4
- MaxScale version: not used
- Install method: Helm

**Additional context**

Deployed on bare metal. I'm happy to provide more details if needed, and to help test/reproduce the problem/fix. I'd even be happy to try implementing a fix, but I'm not sure when the time would permit it. Here's my current `MariaDB` object:
```yaml
apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb-galera
spec:
  rootPasswordSecretKeyRef:
    name: mariadb
    key: root-password
  storage:
    size: 1Gi
  replicas: 3
  galera:
    enabled: true
  service:
    type: NodePort
  # service:
  #   type: LoadBalancer
  #   metadata:
  #     annotations:
  #       metallb.universe.tf/loadBalancerIPs: 172.18.0.150
  # primaryService:
  #   type: LoadBalancer
  #   metadata:
  #     annotations:
  #       metallb.universe.tf/loadBalancerIPs: 172.18.0.160
  # secondaryService:
  #   type: LoadBalancer
  #   metadata:
  #     annotations:
  #       metallb.universe.tf/loadBalancerIPs: 172.18.0.161
  metrics:
    enabled: true
```
Based on the example provided in this project. If we will support static NodePort ports, it might be nice to have it implemented in one example file. 

Thank you !
