### ISSUE TITLE
[Bug] Maxscale periodic restart with TLS enabled

### ISSUE THREAD

**Issue by bjanTS** [mariadb-operator/mariadb-operator#1222]
I am experiencing a strange issue with the MaxScale deployment in a HA setup with TLS enabled.

I have used the galera TLS examples from the examples section in the 2 below yaml files, so that the operator should handle the whole TLS configuration.

With TLS enabled the maxscale-0 pod continues to rise in its memory usage, until it crashes every time after ~30 minutes, becomes unresponsive for a few minutes, but only after a few minutes of being unresponsive it is killed by the liveness probe failing, the liveness probe does not fail immediately. But the memory usage of this pod is only ~50Mi when it crashes, so nowhere near the assigned limit.

Pods maxscale-1 and maxscale-2 are running fine.

Without TLS enabled it works fine for all 3 maxscale pods, with the only change in the 2 yaml files being removal of the tls sections.

I have been unable to locate anything in logs - is this a known issue? Where should I look to maybe identify the problem?

mariadb.yaml:
```
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb
  namespace: mariadb-cluster
spec:
  rootPasswordSecretKeyRef:
    name: mariadb-root
    key: MARIADB_ROOT_PASSWORD
  tls:
    enabled: true
    required: true
  maxScaleRef:
    name: maxscale
    namespace: mariadb-cluster
  storage:
    size: 100Gi
    storageClassName: mariadb-storage

  replicas: 3

  galera:
    enabled: true
    config:
      reuseStorageVolume: true

  primaryService:
    type: ClusterIP

  secondaryService:
    type: ClusterIP

  resources:
    requests:
      cpu: 2
      memory: 6144M
    limits:
      cpu: 6
      memory: 10240M

  tolerations:
    - key: "mariadb"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"

  affinity:
    antiAffinityEnabled: true
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                  - node07
                  - node08
                  - node09

  myCnf: |
    [mariadb]
    max_connections=100000
    max_user_connections=100000
    bind-address=*
    default_storage_engine=InnoDB
    binlog_format=row
    innodb_autoinc_lock_mode=2
    innodb_buffer_pool_size=4096M
    max_allowed_packet=512M
```

maxscale.yaml:
```
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: MaxScale
metadata:
  name: maxscale
  namespace: mariadb-cluster
spec:
  mariaDbRef:
    name: mariadb
    namespace: mariadb-cluster

  replicas: 3
  config:
    volumeClaimTemplate:
      storageClassName: maxscale-storage

  tolerations:
    - key: "mariadb"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"

  resources:
    requests:
      cpu: "2"
      memory: "2048Mi"
    limits:
      cpu: "4"
      memory: "4096Mi"

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                  - node07
                  - node08
                  - node09
  auth:
    generate: true
  tls:
    enabled: true
```

**Expected behaviour**
That the maxscale-0 pod does not periodically restart every ~30 minutes

**Steps to reproduce the bug**
1. Apply the mariadb yaml
2. Apply the maxscale yaml
3. Watch the memory usage of maxscale-0 pod continually rise until it crashes and is restarted

**Extra info**
The only suspicious thing I have been able to notice, is when I click on one of the MariaDB server instances in the Maxscale GUI, then it continually get a new timestamp every ~10 seconds with the status server_down in the last event field, even though it says that the server is healthy.
