### ISSUE TITLE
[Bug] MariaDB experiences bursts of unavailability during scaling operations

### ISSUE THREAD

**Issue by kos-team** [mariadb-operator/mariadb-operator#1226]
**Documentation**
- [x] I acknowledge that I have read the relevant [documentation](https://github.com/mariadb-operator/mariadb-operator/tree/main/docs).

**Describe the bug**
During scaling operation, or any operation that requires the operator to perform a rolling upgrade of the MariaDB cluster, we notice that the MariaDB clients experience multiple bursts of unavailability.

The unavailability happens when a MariaDB is being restarted, and when the primary is getting restarted. When the primary gets restarted, the client gets `ERROR 1047 (08S01): WSREP has not yet prepared node for application use` and cluster remains unavailable for a long time.

**Expected behaviour**

We expect the replicated MariaDB cluster with Galera remains highly available during operations.

The unavailability during secondary node restart maybe a limitation of the Galera itself. However, we believe the primary restart procedure can be optimized by first switchover the leader to another ready node before restarting. This can prevent directly bringing down a primary which causes significant amount of downtime. 

**Steps to reproduce the bug**

1. Create a replicated MariaDB cluster with 3 nodes using Galera:
```
apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb
spec:
  rootPasswordSecretKeyRef:
    name: mariadb
    key: root-password
  username: mariadb
  passwordSecretKeyRef:
    name: mariadb
    key: password
  database: mariadb
  port: 3306
  replicas: 3
  galera:
    enabled: true
  storage:
    size: 1Gi
    storageClassName: standard
    resizeInUseVolumes: true
    waitForVolumeResize: true
  connection:
    secretName: connection-mariadb
    secretTemplate:
      key: dsn
    healthCheck:
      interval: 10s
      retryInterval: 3s
    params:
      parseTime: "true"
  myCnf: |
    [mariadb]
    bind_address=*
    default_storage_engine=InnoDB
    binlog_format=row
    innodb_autoinc_lock_mode=2
    innodb_buffer_pool_size=1024Mi
    max_allowed_packet=256Mi
  timeZone: "UTC"
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      memory: 1Gi
  env:
    - name: TZ
      value: SYSTEM
  securityContext:
    allowPrivilegeEscalation: false
  livenessProbe:
    exec:
      command:
        - bash
        - -c
        - mariadb -u root -p"${MARIADB_ROOT_PASSWORD}" -e "SELECT 1;"
    initialDelaySeconds: 20
    periodSeconds: 5
    timeoutSeconds: 5
  readinessProbe:
    exec:
      command:
        - bash
        - -c
        - mariadb -u root -p"${MARIADB_ROOT_PASSWORD}" -e "SELECT 1;"
    initialDelaySeconds: 20
    periodSeconds: 5
    timeoutSeconds: 5
  podDisruptionBudget:
    maxUnavailable: 50%
  updateStrategy:
    type: ReplicasFirstPrimaryLast
  service:
    type: ClusterIP
  metrics:
    enabled: true
  suspend: false
```
2. We have a MariaDB client which constantly performs write and read operations using the `test-cluster-primary` service.
3. Perform an upscale operation by changing the `spec.replicas` from `3` to `5`, notice that the client starts to have errors returned by the MariaDB cluster everytime a node is restarted (even if the node is a secondary). When the primary is restarted, 

**Environment details**:
- Kubernetes version: v1.29
- Kubernetes distribution: KIND
- mariadb-operator version: 0.35.1
- Install method: [helm, OLM, or static manifests]: helm
