### ISSUE TITLE
[Bug] Root User Password Bootstrapping Fails

### ISSUE THREAD

**Issue by FRQ-MaLang** [mariadb-operator/mariadb-operator#1262]
**Documentation**
- [x] I acknowledge that I have read the relevant [documentation](https://github.com/mariadb-operator/mariadb-operator/tree/main/docs).

**Describe the bug**
When creating a MariaDB cluster (with Galera and MaxScale) using the k8s mariadb-operator, bootstrapping of the root user fails from time to time.

This behavior cannot be observed all the time - but very frequently, so I am suspecting some timing dependency / race condition.

I am bootstrapping the root user using the 'rootPasswordSecretKeyRef' with a k8s secret called "mariadb-admin".
I am using helm for installing the mariadb-cluster with the following deployment.

```
NAME: mariadb-galera-test
LAST DEPLOYED: Tue Apr 22 12:29:10 2025
NAMESPACE: mariadb-operator
STATUS: pending-install
REVISION: 1
TEST SUITE: None
USER-SUPPLIED VALUES:
{}

COMPUTED VALUES:
mariadb:
  hostPath:
    path: /var/data/bitnami/mariadb/mariadb-galera-test
    storage: 250Mi
  maxScale:
    guiEnabled: true
    loadBalancerIPs: 10.16.109.120
    replicas: 3
  name: mariadb-galera-test
  replicas: 3
  users:
    admin:
      password: '!test'
      username: mariadb
mariadb-helpers:
  global: {}

HOOKS:
MANIFEST:
---
# Source: mariadb/templates/mariadb.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-admin
  namespace: mariadb-operator
  labels:
    app.kubernetes.io/name: mariadb-galera-test
type: Opaque
stringData:
  password: "!test"
---
# Source: mariadb/templates/mariadb.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mariadb
  namespace: mariadb-operator
  labels:
    app.kubernetes.io/name: mariadb-galera-test
type: Opaque
stringData:
  mariadb-user: "mariadb"
  mariadb-password: "!test"
---
# Source: mariadb/templates/mariadb.yaml
apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: mariadb-user-grant
  namespace: mariadb-operator
  labels:
    app.kubernetes.io/name: mariadb-galera-test
spec:
  mariaDbRef:
    name: mariadb-galera-test
  privileges:
    - "ALL PRIVILEGES"
  database: "*"
  table: "*"
  username: "mariadb"
  grantOption: true
  host: "%"
  cleanupPolicy: Delete
  requeueInterval: 30s
  retryInterval: 5s
---
# Source: mariadb/templates/mariadb.yaml
apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb-galera-test
  namespace: mariadb-operator
  labels:
    app.kubernetes.io/name: mariadb-galera-test
spec:
  replicas: 3
  replicasAllowEvenNumber: false
  galera:
    enabled: true
    agent:
      basicAuth:
        enabled: true
  maxScale:
    enabled: true
    replicas: 3
    admin:
      guiEnabled: true
    auth:
      adminUsername: mariadb
      adminPasswordSecretKeyRef:
        name: mariadb-admin
        key: password
    kubernetesService: 
      type: LoadBalancer
      metadata:
        annotations:
          metallb.universe.tf/loadBalancerIPs: 10.16.109.120
  database: mariadb
  rootPasswordSecretKeyRef:
    name: mariadb-admin
    key: password
  username: mariadb
  passwordSecretKeyRef:
    name: mariadb-admin
    key: password
  storage:
    size: "250Mi"
  affinity:
    antiAffinityEnabled: true
  podSecurityContext:
    runAsUser: 1001
    runAsGroup: 1001
  metrics:
    enabled: true
```
Once the mariadb-operator executed the init pod to bootstrap the cluster, the mariadb nodes are created. The first node is trying to start, but the agent performing liveness checks always restarts the node, as the liveness probes fails. This is because access to the database using the root user and password is denied.
-> Cluster unable to start up!

```
NAME                                                READY   STATUS     RESTARTS      AGE
mariadb-galera-test-0                               1/2     Running    8 (48s ago)   16m
mariadb-galera-test-1                               0/2     Init:0/1   0             16m
mariadb-galera-test-2                               0/2     Init:0/1   0             16m
```

```
k logs mariadb-galera-test-0 agent 
{"level":"info","ts":1745317775.7879882,"msg":"Agent starting"}
{"level":"info","ts":1745317775.7882683,"logger":"api","msg":"Configuring basic authentication"}
{"level":"info","ts":1745317775.7890265,"logger":"api","msg":"Configuring TLS"}
{"level":"info","ts":1745317775.791002,"logger":"api","msg":"Server listening","addr":":5555","tls":true}
{"level":"info","ts":1745317775.7910924,"logger":"probe","msg":"Server listening","addr":":5566","tls":false}
{"level":"error","ts":1745317804.0074303,"logger":"probe.liveness","msg":"error getting SQL client","error":"Error 1045 (28000): Access denied for user 'root'@'::1' (using password: YES)","stacktrace":"github.com/mariadb-operator/mariadb-operator/pkg/galera/agent/handler.(*Probe).Liveness\n\t/app/pkg/galera/agent/handler/probe.go:67\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2294\ngithub.com/go-chi/chi/v5.(*Mux).routeHTTP\n\t/go/pkg/mod/github.com/go-chi/chi/v5@v5.2.1/mux.go:480\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2294\ngithub.com/go-chi/chi/v5/middleware.Recoverer.func1\n\t/go/pkg/mod/github.com/go-chi/chi/v5@v5.2.1/middleware/recoverer.go:45\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2294\ngithub.com/go-chi/chi/v5/middleware.(*Compressor).Handler-fm.(*Compressor).Handler.func1\n\t/go/pkg/mod/github.com/go-chi/chi/v5@v5.2.1/middleware/compress.go:209\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2294\ngithub.com/go-chi/chi/v5.(*Mux).ServeHTTP\n\t/go/pkg/mod/github.com/go-chi/chi/v5@v5.2.1/mux.go:90\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:3301\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:2102"}
```

Furthermore, accessing the database directly from the container fails with 'Access denied'.
```
kubectl exec -it mariadb-galera-test-0 -- mariadb -uroot -p'!test' -e "SHOW STATUS LIKE 'wsrep%';"
```

**Expected behaviour**
The correct bootstrapping of the root user credentials is expected.
In one of the few cases where bootstrapping of the user works correct (using exactly the same configuration and procedures for deployment), the cluster starts up and everything works as expected.

**Steps to reproduce the bug**
Reusage of the provided manifest (helm).

**Debug information**
- The k8s secret 'mariadb-admin' exist:
```bash
k get secrets 
NAME                                          TYPE                 DATA   AGE
mariadb                                       Opaque               2      30m
mariadb-admin                                 Opaque               1      30m
mariadb-galera-test-agent-auth                Opaque               1      30m
mariadb-galera-test-ca                        Opaque               2      30m
mariadb-galera-test-ca-bundle                 Opaque               1      30m
mariadb-galera-test-client-cert               kubernetes.io/tls    2      30m
mariadb-galera-test-maxscale-client           Opaque               1      30m
mariadb-galera-test-maxscale-config           Opaque               1      30m
mariadb-galera-test-maxscale-monitor          Opaque               1      30m
mariadb-galera-test-maxscale-server           Opaque               1      30m
mariadb-galera-test-maxscale-sync             Opaque               1      30m
mariadb-galera-test-server-cert               kubernetes.io/tls    2      30m
mariadb-operator-webhook-ca                   kubernetes.io/tls    2      7d
mariadb-operator-webhook-cert                 kubernetes.io/tls    2      7d
sh.helm.release.v1.mariadb-galera-test.v1     helm.sh/release.v1   1      30m
sh.helm.release.v1.mariadb-operator-crds.v1   helm.sh/release.v1   1      7d
sh.helm.release.v1.mariadb-operator.v1        helm.sh/release.v1   1      7d
```

```bash
k describe secrets mariadb-admin 
Name:         mariadb-admin
Namespace:    mariadb-operator
Labels:       app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=mariadb-galera-test
Annotations:  meta.helm.sh/release-name: mariadb-galera-test
              meta.helm.sh/release-namespace: mariadb-operator

Type:  Opaque

Data
====
password:  5 bytes
```

**Environment details**:
- Kubernetes version: v1.29.3
- Kubernetes distribution: Vanilla Kubernetes
- MariaDB Operator version: mariadb-operator-0.38.0
- MariaDB Server version: 11.4.5-MariaDB
- MaxScale version: maxscale:23.08.5
- Install method: Helm

**Additional context**
-
