### ISSUE TITLE
Add Fine-Grained Replica Control (spec.manageReplicas) to Support KEDA Integration

### ISSUE THREAD

**Issue by keval-indoriya-devops-ak** [mariadb-operator/mariadb-operator#1292]
**Is your feature request related to a problem? Please describe.** :-
I’m using the MariaDB Operator in an EKS cluster along with [KEDA (Kubernetes Event-Driven Autoscaler)](https://keda.sh/) to scale my MariaDB instances based on external metrics like queue length.

However, the operator reconciles the spec.replicas field and keeps resetting the replica count to what is defined in the CR. This causes a conflict with KEDA, which tries to scale the StatefulSet independently. The net effect is unstable autoscaling behavior where KEDA's scaling decisions are reverted by the operator.

The only available workaround is setting spec.suspend: true, but that disables all reconciliation including user creation, backups, TLS, and more — which is not acceptable for a production workload.

**Describe the solution you'd like** :-
I’d like a new field in the MariaDB Custom Resource:

spec:
  manageReplicas: false

This field would allow the operator to ignore changes to replicas and let external systems like KEDA manage scaling freely, while the operator continues to manage all other aspects like TLS, backup, user creation, etc.

This feature would preserve backward compatibility by defaulting to true if not specified.

Describe alternatives you've considered
Using spec.suspend: true — but this stops all controller functionality, not just replica management.

Patching StatefulSet directly and ignoring the CR — leads to constant conflict due to reconciliation loop.

Custom fork of the operator — too high maintenance and not future-proof.

**Environment details** :-

  Kubernetes version: 1.32
  Kubernetes distribution: EKS
  MariaDB Operator version: 0.38.1
  MariaDB Server version: 11.4
  MaxScale version: 23.08
  Install method: Helm

**Additional context** :- 
This feature would make the MariaDB Operator much more flexible in dynamic, autoscaled environments. We rely heavily on KEDA for metric-based scaling and want to retain all other benefits of the operator without suspension. Happy to help with testing or a PR.

**Comment by ibotty** [comment]
Isn't the best way forward to configure KEDA to scale the mariadb object instead?  This should work, because AFAICT `mariadbs.k8s.mariadb.com` has a scale subresource.

https://keda.sh/docs/2.17/concepts/scaling-deployments/#scaling-custom-resources

**Comment by mmontes11** [comment]
As @ibotty mentioned, we do have a scale subresource:
https://github.com/mariadb-operator/mariadb-operator/blob/c95dd1ad8d341e4aae5c0af94ab4a471690b5abb/api/v1alpha1/mariadb_types.go#L766

Would that work for KEDA?

**Comment by CameronCarranza** [comment]
@ibotty @mmontes11 I came across this issue looking for HPA/KEDA functionality through the operator. [The MariaDB blog mentions the implementation of the scale subresource](https://mariadb.com/resources/blog/get-started-with-mariadb-in-kubernetes-and-mariadb-operator/) however there isn't really any example of it just a secondary mention on the MaxScale doc in the repo.

Does seem like it implements the scale subresources required fields but _doesn't_ implement the "optional" `labelSelectorPath` which appears to be an issue since the Scale subresource documentation mentions **"It must be set to work with HPA and VPA."**

```
    subresources:
      scale:
        specReplicasPath: .spec.replicas
        statusReplicasPath: .status.replicas
```

**KEDA Targetting MariaDB CRD**

I have tried both HPA and KEDA, and while both can target the `MariaDB` CRD, they do appear to be missing something to fetch all of the metrics (occurs both for KEDA-created and standard HPA):

```
Min replicas:                              3
Max replicas:                              15
MariaDB pods:                              3 current / 0 desired
Conditions:
  Type           Status  Reason             Message
  ----           ------  ------             -------
  AbleToScale    True    SucceededGetScale  the HPA controller was able to get the target's current scale
  ScalingActive  False   InvalidSelector    the HPA target's scale is missing a selector
Events:
  Type     Reason                        Age                     From                       Message
  ----     ------                        ----                    ----                       -------
  Warning  FailedComputeMetricsReplicas  3m39s (x12 over 6m24s)  horizontal-pod-autoscaler  selector is required
  Warning  SelectorRequired              84s (x21 over 6m24s)    horizontal-pod-autoscaler  selector is required
```

**KEDA Targetting StatefulSet managed by MariaDB CRD**

The only way I get 3 current / 3 desired and metrics is if I point to to the `StatefulSet`, however direct scaling of the StatefulSet causes the operator to manage it back down to the Replica count the instant it attempts to scale.

```
Reference:                                                                       StatefulSet/mariadb-galera
Metrics:                                                                         ( current / target )
  resource cpu of container "mariadb" on pods  (as a percentage of request):     10% (151m) / 50%
  resource memory of container "mariadb" on pods  (as a percentage of request):  10% (676276Ki) / 50%
Min replicas:                                                                    3
Max replicas:                                                                    15
StatefulSet pods:                                                                3 current / 3 desired
Conditions:
  Type            Status  Reason            Message
  ----            ------  ------            -------
  AbleToScale     True    ReadyForNewScale  recommended size matches current size
  ScalingActive   True    ValidMetricFound  the HPA was able to successfully calculate a replica count from cpu container resource utilization (percentage of request)
  ScalingLimited  True    TooFewReplicas    the desired replica count is less than the minimum replica count
Events:           <none>
```

Events from the StatefulSet when I set minReplicas to 5 to force a scale up
```
  Normal  SuccessfulCreate  103s (x19 over 73m)   statefulset-controller  create Pod mariadb-galera-3 in StatefulSet mariadb-galera successful
  Normal  SuccessfulDelete  103s (x19 over 73m)   statefulset-controller  delete Pod mariadb-galera-3 in StatefulSet mariadb-galera successful
  Normal  SuccessfulCreate  103s (x3 over 2m13s)  statefulset-controller  create Pod mariadb-galera-4 in StatefulSet mariadb-galera successful
  Normal  SuccessfulDelete  103s (x3 over 2m13s)  statefulset-controller  delete Pod mariadb-galera-4 in StatefulSet mariadb-galera successful

```

Here is the ScaledObject I am currently using with KEDA, I left in some Prometheus metrics I was attempting to use as well 
```
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: mariadb-galera
spec:
  scaleTargetRef:
    apiVersion: k8s.mariadb.com/v1alpha1
    kind: MariaDB
    name: mariadb-galera
  minReplicaCount: 3
  maxReplicaCount: 5
  triggers:
    - type: cpu
      metricType: Utilization
      metadata:
        value: "50"
        containerName: "mariadb"
    - type: memory
      metricType: Utilization
      metadata:
        value: "50"
        containerName: "mariadb"
#  - type: prometheus
#    metadata:
#      serverAddress: http://kube-prometheus-stack-prometheus.kube-system:9090
#      query: max((sum(container_memory_working_set_bytes{namespace="my-app-ns", pod=~"mariadb-galera.*", container="mariadb"}) BY (pod, container) / sum(kube_pod_container_resource_limits{namespace="my-app-ns", pod=~"mariadb-galera.*", container="mariadb", resource="memory"}) BY (pod, container)) * 100)
#      threshold: "50"
```

[Came across a similar issue here](https://github.com/orgs/strimzi/discussions/6871) which seems like it wasn't [fully implemented until later with labelSelector](https://github.com/strimzi/strimzi-kafka-operator/issues/10450#issuecomment-2304136743). I am testing this out and am getting further after editing the `mariadbs.k8s.mariadb.com` CRD to add the following:

(Added to spec.versions[0].schema.openAPIV3Schema.properties.spec.properties)
```
              labelSelector:
                default: mariadb-galera
                type: string
```

Adding the missing "optional" field
```
    subresources:
      scale:
        labelSelectorPath: .spec.labelSelector
```

with the following result on the HPA:

```
Events:
  Type     Reason                            Age   From                       Message
  ----     ------                            ----  ----                       -------
  Warning  FailedGetContainerResourceMetric  0s    horizontal-pod-autoscaler  failed to get cpu utilization: unable to get metrics for resource cpu: no metrics returned from resource metrics API
  Warning  FailedGetContainerResourceMetric  0s    horizontal-pod-autoscaler  failed to get memory utilization: unable to get metrics for resource memory: no metrics returned from resource metrics API
  Warning  FailedComputeMetricsReplicas      0s    horizontal-pod-autoscaler  invalid metrics (2 invalid out of 2), first error is: failed to get mariadb container metric value: failed to get cpu utilization: unable to get metrics for resource cpu: no metrics returned from resource metrics API
```

Will keep chipping away and see where I land and update, this is a test env so no real issues directly editing the CRD so if there is anything you need or want me to test against it please let me know.

Thank you!


---

Update:

It was _**not**_ the MariaDB CRD/Object scaling me back to 3, it was ArgoCD. I had added the below section to my application but did not apply so that part was on me. 

```
      ignoreDifferences:
        - group: k8s.mariadb.com
          kind: MariaDB
          jsonPointers:
            - /spec/replicas
```

It does appear to work with the above modifications, CPU/Memory do not work directly but external metrics via Prometheus do and adjusting minReplicas to 5 works and settles properly.

```
mariadb-galera-0                            2/2     Running     0          4m47s
mariadb-galera-1                            2/2     Running     0          4m1s
mariadb-galera-2                            2/2     Running     0          116s
mariadb-galera-3                            2/2     Running     0          2m44s
mariadb-galera-4                            2/2     Running     0          2m44s

```

Some tweaking to do on the metric side but it is showing combined usage for all 3 here for memory

```
keda-hpa-mariadb-autoscaler   MariaDB/mariadb-galera                2037m/50 (avg)   5         15        5          61m
```

So in all, this is working as expected currently after:
* Add `labelSelectorPath` to subresources
* Add `labelSelector` to the `openAPIV3Schema` with a default of `mariadb-galera` (this is my MariaDB instance name so may not be correct for everyone)
* I added `spec.labelSelector: mariadb-galera` on my MariaDB resource to avoid relying on the default should the CRD change and not rely on the probably-not-sane default I had added.


Happy to share any info if needed or if it helps! Will try to remember to get the Prometheus metrics in here once I'm done so it can be a jumping off point for others.
