### ISSUE TITLE
Unclear doc about MaxScale GUI credentials location

### ISSUE THREAD

**Issue by deimosfr** [mariadb-operator/mariadb-operator#1304]
Hi,

Following the documentation https://github.com/mariadb-operator/mariadb-operator/blob/main/docs/MAXSCALE.md#maxscale-gui, I should be able to retrieve credentials from a secret. There is no mention of the secret name when auth is auto-generated.

So I have those secrets:
```
maxscale-repl-admin                Opaque                     1      6d18h
maxscale-repl-client               Opaque                     1      6d18h
maxscale-repl-config               Opaque                     1      22m
maxscale-repl-metrics              Opaque                     1      6d18h
maxscale-repl-monitor              Opaque                     1      6d18h
maxscale-repl-server               Opaque                     1      6d18h
maxscale-repl-sync                 Opaque                     1      6d18h
```

They are containing a password, but is `admin` the default login?

Thanks in advance for the clarification

**Comment by Dariocent** [comment]
Hello, I had the same issue and found that the default admin user is "mariadb-operator", which is tied to the password contained in the secret "maxscale-repl-admin".
Hope that helps

**Comment by rgambelli** [comment]
> Hello, I had the same issue and found that the default admin user is "mariadb-operator", which is tied to the password contained in the secret "maxscale-repl-admin". Hope that helps

I'm trying with mariadb-operator and the password contained in secret but I receive 401 in maxscale gui

```
spec:
  admin:
    guiEnabled: true
    port: 8989
  auth:
    adminPasswordSecretKeyRef:
      generate: true
      key: password
      name: maxscale-admin
    adminUsername: mariadb-operator
```
