### ISSUE TITLE
Syntax for database.mmontes.io/GrantMariaDB

### ISSUE THREAD

**Issue by krptg0** [mariadb-operator/mariadb-operator#14]
Hi,

The [Grant example](https://github.com/mmontes11/mariadb-operator/blob/main/config/samples/database_v1alpha1_grantmariadb.yaml) shows how to grant basic rights to a user, but how to list them all ? Like what should I declare to grant all rights to a database to a user ?

Thanks in advance,

**Comment by mmontes11** [comment]
Hi @krptg0 !

You can grant [ALL PRIVILEGES](https://mariadb.com/kb/en/grant/#the-all-privileges-privilege) using the `Grant` CRD:
```yaml
apiVersion: database.mmontes.io/v1alpha1
kind: GrantMariaDB
metadata:
  name: user
spec:
  mariaDbRef:
    name: mariadb
  privileges:
    - "ALL PRIVILEGES"
  database: "*"
  table: "*"
  username: user
  grantOption: true
```
