### ISSUE TITLE
[Feature] Specify database name 

### ISSUE THREAD

**Issue by mac-lucky** [mariadb-operator/mariadb-operator#140]
**Is your feature request related to a problem? Please describe.**

I would like to use Mariadb operator in Kubernetes, but there are apps that need to work in another system and database is using naming like that `users_database`. I cannot name the Kubernetes resource like that, because it is not allowed

**Describe the solution you'd like**

Specify the name of database in configuration like that:
```
apiVersion: mariadb.mmontes.io/v1alpha1
kind: Database
metadata:
  name: "opt-assets-test"
  namespace: mariadb
spec:
  mariaDbRef:
    name: mariadb
  name: users_database
  characterSet: utf8
  collate: utf8_general_ci
```

**Describe alternatives you've considered**
I couldn't figure out another solution

**Environment details**:
- Kubernetes version: v1.25.9
- mariadb-operator version: 0.15.1
- Install method: helm
- Install flavour: recommended
