### ISSUE TITLE
[Bug] Stateful sets misses metrics container port on upgrade from 0.15.1 to 0.17.0

### ISSUE THREAD

**Issue by pmig** [mariadb-operator/mariadb-operator#160]
**Describe the bug**

Cluster upgrade from 0.15.1 to 0.17.0 seems to create a broken statefull set:

generated statefull set section:

```yaml
- name: metrics
          image: prom/mysqld-exporter:v0.14.0
          ports:
            - name: metrics
              containerPort: 0
              protocol: TCP
```

```json
[
"spec.ports[1].port: Invalid value: 0: must be between 1 and 65535, inclusive",
"spec.ports[1].targetPort: Invalid value: 0: must be between 1 and 65535, inclusive"
],
"stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:273\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:234"
```

**Steps to reproduce the bug**

1. Create a MariaDB with an exporter with operator 0.15.1
2. Upgrade operator to 0.17.0
3. see failed upgrade

**Environment details**:
- Kubernetes version: 1.27
- mariadb-operator version: 0.17.0 
- Install method: helm
- Install flavour: minimal
