### ISSUE TITLE
[Bug] Cannot delete `Grant` CRD

### ISSUE THREAD

**Issue by matthieugusmini** [mariadb-operator/mariadb-operator#172]
**Describe the bug**
When I'm trying to delete the CRD with the following command it does't get deleted:
```shell
kubectl delete --force grants.mariadb.mmontes.io foo
```

**Expected behaviour**
The deployed `Grant` should be deleted.

**Steps to reproduce the bug**
Deploy a `Grant` with a non existent database table. Here's the YAML file I used to deploy the CRD:
```yaml
apiVersion: mariadb.mmontes.io/v1alpha1
kind: Grant
metadata:
  name: foo
spec:
  mariaDbRef:
    name: mariadb
  privileges:
    - "SELECT"
  database: "mysql"
  table: "proxies-priv"
  username: maxscale
  grantOption: false
```
(It should be `mysql.proxies_priv`)

**Additional context**
Not an expert but I suspect a deadlock in the finalizer 🤔 Don't really have the time to inspect further right now but might give it a look later.
Following the instructions from [this answer](https://github.com/kubernetes/kubernetes/issues/60538#issuecomment-1039128094) I eventually deleted the CRD.

**Environment details**:
- Kubernetes version: 
```
Client Version: v1.27.2
Kustomize Version: v5.0.1
Server Version: v1.24.14-gke.1200
```
- mariadb-operator version: v0.0.18
- Install method: helm
- Install flavour: custom
