### ISSUE TITLE
[Feature] Configure the hostname when creating a user

### ISSUE THREAD

**Issue by matthieugusmini** [mariadb-operator/mariadb-operator#173]
**Is your feature request related to a problem? Please describe.**
I'm currently configuring MaxScale in my company's system and as [stated in the official documentation](https://mariadb.com/kb/en/mariadb-maxscale-6-setting-up-mariadb-maxscale/#creating-client-user-accounts) I need a second set of grants for the user at the MaxScale instance host name.

**Describe the solution you'd like**
I'd like to be able to configure the hostname of the user via an additional field in the `User` and the `Grant` CRD.

I think passing the hostname as well to the `CreateUser` and the `Grant` methods of the `Client` would be an appropriate approach.
🔗 https://github.com/mariadb-operator/mariadb-operator/blob/main/pkg/client/client.go#L192
🔗 https://github.com/mariadb-operator/mariadb-operator/blob/main/pkg/client/client.go#L219

So the `wrappedUserReconciler` and the `wrappedGrantReconciler` can pass the field as an argument when calling the client [here](https://github.com/mariadb-operator/mariadb-operator/blob/main/controllers/user_controller.go#L98) and here [respectively](https://github.com/mariadb-operator/mariadb-operator/blob/main/controllers/grant_controller.go#L157).

This field could be optional and replaced by a '%' in case it is not specified since these methods already receive a `CreateUserOpts` and `GrantOpts` option struct respectively.

**Environment details**:
- Kubernetes version: 
```
Client Version: v1.27.2
Kustomize Version: v5.0.1
Server Version: v1.24.14-gke.1200
```
- mariadb-operator version: v0.0.18
- Install method: helm
- Install flavour: custom

**Comment by mmontes11** [comment]
Hey @matthieugusmini ! thanks for your suggestion.

This totally makes sense to me, I would add a `spec.host` field to both the `User` and the `Grant` resources:
```yaml
apiVersion: mariadb.mmontes.io/v1alpha1
kind: User
metadata:
  name: user
spec:
  mariaDbRef:
    name: mariadb
  passwordSecretKeyRef:
    name: user
    key: password
  maxUserConnections: 20
  name: jdoe
  host: maxscale-host
```
```yaml
apiVersion: mariadb.mmontes.io/v1alpha1
kind: Grant
metadata:
  name: grant
spec:
  mariaDbRef:
    name: mariadb
  privileges:
    - "SELECT"
    - "INSERT"
    - "UPDATE"
  database: "*"
  table: "*"
  username: user
  grantOption: true
  host: maxscale-host
```
The new fields would be optional, and we can add a `HostOrDefault` method to fallback to `%`, as we did with the `Database`:
https://github.com/mariadb-operator/mariadb-operator/blob/2c7e5f9fc4ec5d3a1cefd558da4b7a7a7cb9fef2/api/v1alpha1/database_types.go#L69

We would pass, as you suggest, the return value of this `HostOrDefault` to the `wrappedUserReconciler` and the `wrappedGrantReconciler` . Would you like to make another contribution?  This can be very useful 🙏🏻
