### ISSUE TITLE
[Ha replication] 

### ISSUE THREAD

**Issue by SolomonJang** [mariadb-operator/mariadb-operator#192]
Hi all:
**Describe the issue**
semi-symc architecture can consistency be guaranteed?

It can be confirmed that after the master pod die.
Make sure that slave's relay logs have been written before turning slave into master

**Operating procedure**
I built it according to mariadb_v1alpha1_mariadb_replication.yaml, as shown in the figure
![image](https://github.com/mariadb-operator/mariadb-operator/assets/120467467/9ba04aec-1a8b-47e6-b45d-1dbd9e568be0)

we can see primary-mariadb-repl.
![image](https://github.com/mariadb-operator/mariadb-operator/assets/120467467/76602ccf-130b-4d98-8a39-1541b6fc842e)
label is repl-0.

Then I also prepared sysbench for testing.
1. use primary-mariadb-repl to create database "sbtest".
![image](https://github.com/mariadb-operator/mariadb-operator/assets/120467467/cab15392-ede6-4b4b-b8e6-4572066e2c80)
![image](https://github.com/mariadb-operator/mariadb-operator/assets/120467467/ceedf56e-1233-4b97-b662-65f327c062bc)
we can check the read is also create.
![image](https://github.com/mariadb-operator/mariadb-operator/assets/120467467/315c83d5-d03d-4848-9681-6a8e44aa2a88)
2. Prepare sysbench
![image](https://github.com/mariadb-operator/mariadb-operator/assets/120467467/cd493fd8-2379-4d3a-8d4d-090306505473)
job-repl.yaml
```
apiVersion: batch/v1
kind: Job
metadata:
  name: sysbench-prepare
spec:
  template:
    metadata:
      name: sysbench-prepare
    spec:
      containers:
      - name: sysbench-prepare
        image: severalnines/sysbench
        command:
        - sysbench
        - --db-driver=mysql
        - --oltp-table-size=100000
        - --oltp-tables-count=24
        - --threads=1
        - --mysql-host=primary-mariadb-repl
        - --mysql-port=3306
        - --mysql-user=mariadb
        - --mysql-password=mariadb
        - /usr/share/sysbench/tests/include/oltp_legacy/parallel_prepare.lua
        - run
      restartPolicy: Never
```
and I run the sysbench.
![image](https://github.com/mariadb-operator/mariadb-operator/assets/120467467/f5975a3b-6aea-48bf-ba8b-da22e062fdab)
can also add -f to see logs.
sysbench-repl.yaml:
```
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: sysbench
  name: sysbench
spec:
  containers:
  - command:
    - sysbench
    - --db-driver=mysql
    - --report-interval=2
    - --mysql-table-engine=innodb
    - --oltp-table-size=100000
    - --oltp-tables-count=24
    - --threads=64
    - --time=99999
    - --mysql-host=primary-mariadb-repl
    - --mysql-port=3306
    - --mysql-user=mariadb
    - --mysql-password=mariadb
    - /usr/share/sysbench/tests/include/oltp_legacy/oltp.lua
    - run
    image: severalnines/sysbench
    name: sysbench
  restartPolicy: Never
```
3. I force delete master pod
![image](https://github.com/mariadb-operator/mariadb-operator/assets/120467467/f6988bc2-1e52-42fd-9213-7c0e7398033f)
and we can see repl will recovery.
![image](https://github.com/mariadb-operator/mariadb-operator/assets/120467467/09bc3565-ca46-4dce-8a6b-d40b868674f5)

4. To see table checksum 
![image](https://github.com/mariadb-operator/mariadb-operator/assets/120467467/ae2ed6a5-4335-498c-a8ec-ba43d2a6b8d8)
The Three db is different.
