### ISSUE TITLE
[Feature] Manage existing Database

### ISSUE THREAD

**Issue by aschaber1** [mariadb-operator/mariadb-operator#199]
Hello :)

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I have a MariaDB provided by a DBaaS. I'd like to be able to manage Users, Grants and logical Databases with the operator. I might just be missing the right pieces from the documentation.

**Describe alternatives you've considered**
Managing the Users Grants and DBs as well in Terraform.

**Additional context**
We're running EKS on AWS and the DBaaS is a RDS Database. But I believe this issue would apply in any environment.

**Environment details**:
- Kubernetes version: 1.26
- mariadb-operator version:  v0.0.19
- Install method: helm
- Install flavour: recommended

Thank you in advance for any pointers.

**Comment by mmontes11** [comment]
Hey @aschaber1 ! Thanks for this suggestion. This is currently not supported but it is definetly interesting 👍🏻 

We will need to adapt our SQL resources to add an `externalMariaDb` field. This will basically replace the current `mariaDbRef`  that refers to local `MariaDB` instances provisioned by the `mariadb-operator` in the same cluster:

```yaml
apiVersion: mariadb.mmontes.io/v1alpha1
kind: User
metadata:
  name: user
spec:
  externalMariaDb:
    host: mydb.123456789012.us-east-1.rds.amazonaws.com.
    user: admin
    passwordSecretKeyRef:
      name: admin
      key: password
    caSecretKeyRef:
      name: aws-rds-ca
      key: ca.crt
  passwordSecretKeyRef:
    name: user
    key: password
  maxUserConnections: 20
```

```yaml
apiVersion: mariadb.mmontes.io/v1alpha1
kind: Grant
metadata:
  name: grant
spec:
  externalMariaDb:
    host: mydb.123456789012.us-east-1.rds.amazonaws.com.
    user: admin
    passwordSecretKeyRef:
      name: admin
      key: password
    caSecretKeyRef:
      name: aws-rds-ca
      key: ca.crt
  privileges:
    - "SELECT"
    - "INSERT"
    - "UPDATE"
  database: "*"
  table: "*"
  username: user
  grantOption: true
```

```yaml
apiVersion: mariadb.mmontes.io/v1alpha1
kind: Database
metadata:
  name: data-test
spec:
  externalMariaDb:
    host: mydb.123456789012.us-east-1.rds.amazonaws.com.
    user: admin
    passwordSecretKeyRef:
      name: admin
      key: password
    caSecretKeyRef:
      name: aws-rds-ca
      key: ca.crt
  characterSet: utf8
  collate: utf8_general_ci
```

As an alternative to password authentication, you may annotate the `mariadb-operator` serviceaccount to setup [IRSA](https://aws.amazon.com/blogs/opensource/introducing-fine-grained-iam-roles-service-accounts/):
```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mariadb-operator
  annotations:
    eks.amazonaws.com/role-arn: $(MARIADB_OPERATOR_IAM_ROLE)
```
This can be achieved by setting `serviceAccount.annotations` when installing the helm chart:
- https://github.com/mariadb-operator/mariadb-operator/blob/main/deploy/charts/mariadb-operator/values.yaml#L45

Does this make sense to you? 
This has been labeled with `help wanted`, contributions and PRs are welcome!

**Comment by aschaber1** [comment]
Thank you for your reply.

Im not a dev (long time ago some Java, hence the idea), but I'd like to suggest another approach, keep the mariaDbRef and have two implementations of the interface, one that is managed and one that is external. Cause i don't see the benefit of an additional field just from your examples.

On the other hand thinking about it.. your approach is probably easier to implement, while mine may be easier to use.

**Comment by mmontes11** [comment]
Hey there, that's a fair point.

Re-iterating on my previous proposal, we could introduce a new resource, the `ExternalMariaDB`:
```yaml
apiVersion: mariadb.mmontes.io/v1alpha1
kind: ExternalMariaDB
metadata:
  name: my-rds-instance
spec:
    host: mydb.123456789012.us-east-1.rds.amazonaws.com.
    user: admin
    passwordSecretKeyRef:
      name: admin
      key: password
    caSecretKeyRef:
      name: aws-rds-ca
      key: ca.crt
```

and specify it as a reference  via `spec.mariaDbRef`,  with the difference that we would be providing the `kind`:
```yaml
apiVersion: mariadb.mmontes.io/v1alpha1
kind: User
metadata:
  name: user
spec:
  mariaDbRef:
      name: my-rds-instance
      kind: ExternalMariaDB
  passwordSecretKeyRef:
    name: user
    key: password
  maxUserConnections: 20
```

```yaml
apiVersion: mariadb.mmontes.io/v1alpha1
kind: Grant
metadata:
  name: grant
spec:
  mariaDbRef:
      name: my-rds-instance
      kind: ExternalMariaDB
  database: "*"
  table: "*"
  username: user
  grantOption: true
```

```yaml
apiVersion: mariadb.mmontes.io/v1alpha1
kind: Database
metadata:
  name: data-test
spec:
  mariaDbRef:
      name: my-rds-instance
      kind: ExternalMariaDB
  characterSet: utf8
  collate: utf8_general_ci
```
This way we have two swappable implementations that can be used in the `spec.mariaDbRef`, so we can reuse the same reconciliation logic.

What do you think @aschaber1 ?
