### ISSUE TITLE
[feature] Support for `spec.initContainers`. Enable `mariabackup` restoration

### ISSUE THREAD

**Issue by Guzzi** [mariadb-operator/mariadb-operator#212]
As discussed in [Slack](https://mariadb-operator.slack.com/archives/C056RAECH0W/p1692791914669749), please add suport for init containers to the operator.
This would allow to e.g. "manuallly" support importing existing database via mariadbbackup physical backup from a PVC (until there is offficial support for it)

After taking a physical following the [docs](https://mariadb.com/kb/en/full-backup-and-restore-with-mariabackup/) and storing it in a PVC, we should be able to restore a physical backup with the following `MariaDB` resource:

```yaml
apiVersion: mariadb.mmontes.io/v1alpha1
kind: MariaDB
metadata:
  name: mariadb-init-mariabackup
spec:
  rootPasswordSecretKeyRef:
    name: mariadb
    key: root-password

  database: mariadb
  username: mariadb
  passwordSecretKeyRef:
    name: mariadb
    key: password

  image:
    repository: mariadb
    tag: "11.0.3"
    pullPolicy: IfNotPresent

  port: 3306

  # See: https://mariadb.com/kb/en/full-backup-and-restore-with-mariabackup/
  initContainers:
    - image:
        repository: mariadb
        tag: "11.0.3"
        pullPolicy: IfNotPresent
      args:
        - mariabackup 
        - --copy-back 
        - --target-dir=/var/mariadb/backup/

  volumes: 
    - name: mariabackup
      persistentVolumeClaim:
        claimName: mariabackup
  volumeMounts: 
    - name: mariabackup
      mountPath: /var/mariadb/backup/

  volumeClaimTemplate:
    resources:
      requests:
        storage: 1Gi
    accessModes:
      - ReadWriteOnce
```
