### ISSUE TITLE
[Bug] Argocd SyncError when tryin gto install mariadbs.mariadb.mmontes.io crd

### ISSUE THREAD

**Issue by stathis-ditc** [mariadb-operator/mariadb-operator#245]
**Describe the bug**

When trying to install mariadb-operator helm chart with Argocd, the following error occurs when trying to create  mariadbs.mariadb.mmontes.io crd

![Screenshot 2023-09-29 at 12 08 52](https://github.com/mariadb-operator/mariadb-operator/assets/84144268/38ab124f-8b34-4a8b-a094-52ca12794b85)

**Is the bug related to Galera?**
- [ ] I have checked the [Galera documentation](https://github.com/mariadb-operator/mariadb-operator/blob/main/docs/GALERA.md)
- [ ] I have checked the [Galera troubleshooting guide](https://github.com/mariadb-operator/mariadb-operator/blob/main/docs/GALERA.md#troubleshooting)

**Expected behaviour**

ArgoCD should install mariadb-operator helm chart and report Sync Ok, Healthy status

**Steps to reproduce the bug**

Install mariadb-operator helm chart with arog using the following manifests

```
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: mariadb-helm-charts
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: '*'
      server: '*'
  sourceRepos:
    - https://mariadb-operator.github.io/mariadb-operator

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mariadb-operator
  namespace: argocd
spec:
  project: mariadb-helm-charts
  source:
    chart: mariadb-operator
    repoURL: https://mariadb-operator.github.io/mariadb-operator
    targetRevision: 0.20.0
    helm:
      releaseName: mariadb-operator
      values: |-
        metrics:
          enabled: true
        webhook:
          certificate:
            certManager: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true

```
**Additional context**

**Environment details**:
- Kubernetes version: v1.27.6+k3s1 (k3s)
- mariadb-operator version: 0.20.0
- Install method: ArgoCD Application
- Install flavour: recommended
