### ISSUE TITLE
[Bug] Infinite loop updating NodePort services

### ISSUE THREAD

**Issue by kvaps** [mariadb-operator/mariadb-operator#256]
**Describe the bug**

```
# kubectl get svc -n db-mariadb -w
NAME            TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)          AGE
may             ClusterIP   172.23.54.220    <none>        3306/TCP         16m
may-internal    ClusterIP   None             <none>        3306/TCP         16m
may-primary     NodePort    172.23.253.144   <none>        3306:32442/TCP   16m
may-secondary   NodePort    172.23.253.205   <none>        3306:31597/TCP   16m
may-primary     NodePort    172.23.253.144   <none>        3306:32648/TCP   16m
may-secondary   NodePort    172.23.253.205   <none>        3306:32686/TCP   16m
may-primary     NodePort    172.23.253.144   <none>        3306:32641/TCP   16m
may-secondary   NodePort    172.23.253.205   <none>        3306:32690/TCP   16m
may-primary     NodePort    172.23.253.144   <none>        3306:30184/TCP   16m
may-secondary   NodePort    172.23.253.205   <none>        3306:32200/TCP   16m
may-primary     NodePort    172.23.253.144   <none>        3306:30307/TCP   16m
may-secondary   NodePort    172.23.253.205   <none>        3306:32255/TCP   16m
may-primary     NodePort    172.23.253.144   <none>        3306:30279/TCP   16m
may-secondary   NodePort    172.23.253.205   <none>        3306:30817/TCP   16m
may-primary     NodePort    172.23.253.144   <none>        3306:31172/TCP   16m
```

**Expected behaviour**

Service will use stable nodePort

**Steps to reproduce the bug**

```
apiVersion: mariadb.mmontes.io/v1alpha1
kind: MariaDB
metadata:
  name: mariadb-may
spec:
  rootPasswordSecretKeyRef:
    name: mariadb-may
    key: root-password

  image: "mariadb:11.0.2"

  port: 3306

  replicas: 3
     
  replication:
    enabled: true
    #primary:
    #  podIndex: 0
    #  automaticFailover: true

  volumeClaimTemplate:
    resources:
      requests:
        storage: 100Gi
    accessModes:
      - ReadWriteOnce

  #service:
  #  type: NodePort
  primaryService:
    type: NodePort
    externalTrafficPolicy: Local
  secondaryService:
    type: NodePort
    externalTrafficPolicy: Local
```

**Additional context**

**Environment details**:
- Kubernetes version: `v1.21.2`
- mariadb-operator version: `v0.22.0`
- Install method: helm
- Install flavour: baremetal
