### ISSUE TITLE
[Bug] MariaDB fails to restart after the whole cluster rebooted

### ISSUE THREAD

**Issue by outductor** [mariadb-operator/mariadb-operator#263]
**Describe the bug**

I get the folloing error after all nodes where MariaDB insntaces exist has got rebooted

```
mariadb 2023-10-27  9:13:02 30477 [ERROR] Master 'mariadb-operator': Error reading packet from server: Lost connection to server during
query (server_errno=2013)
mariadb 2023-10-27  9:13:02 30477 [Note] Master 'mariadb-operator': Slave I/O thread exiting, read up to log 'mariadb-bin.000001', posit
ion 912848; GTID position 0-12-61, master mariadb-2.mariadb-internal.seichi-minecraft.svc.cluster.local:3306
mariadb 2023-10-27  9:13:02 30484 [Note] Master 'mariadb-operator': Slave I/O thread: Start semi-sync replication to master 'repl@mariad
b-2.mariadb-internal.seichi-minecraft.svc.cluster.local:3306' in log 'mariadb-bin.000001' at position 1680
mariadb 2023-10-27  9:13:02 30485 [Note] Master 'mariadb-operator': Slave SQL thread initialized, starting replication in log 'mariadb-b
in.000001' at position 1680, relay log './mariadb-relay-bin-mariadb@002doperator.000001' position: 4; GTID position ''
mariadb 2023-10-27  9:13:02 30484 [Note] Master 'mariadb-operator': Slave I/O thread: connected to master 'repl@mariadb-2.mariadb-intern
al.seichi-minecraft.svc.cluster.local:3306',replication starts at GTID position ''
mariadb 2023-10-27  9:13:03 30485 [ERROR] Master 'mariadb-operator': Slave SQL: Could not execute Write_rows_v1 event on table seichi-ti
med-stats-conifers.break_count_diff_point; Duplicate entry '2099' for key 'PRIMARY', Error_code: 1062; handler error HA_ERR_FOUND_DUPP_K
EY; the event's master log mariadb-bin.000001, end_log_pos 2067, Gtid 0-12-10, Internal MariaDB error code: 1062
mariadb 2023-10-27  9:13:03 30485 [Warning] Master 'mariadb-operator': Slave: Duplicate entry '2099' for key 'PRIMARY' Error_code: 1062
mariadb 2023-10-27  9:13:03 30485 [ERROR] Master 'mariadb-operator': Error running query, slave SQL thread aborted. Fix the problem, and
 restart the slave SQL thread with "SLAVE START". We stopped at log 'mariadb-bin.000001' position 1680; GTID position '0-12-9'
mariadb 2023-10-27  9:13:03 30485 [Note] Master 'mariadb-operator': Slave SQL thread exiting, replication stopped in log 'mariadb-bin.00
0001' at position 1680; GTID position '0-12-9', master: mariadb-2.mariadb-internal.seichi-minecraft.svc.cluster.local:3306
```

```yaml
apiVersion: mariadb.mmontes.io/v1alpha1
kind: MariaDB
metadata:
  namespace: seichi-minecraft
  name: mariadb
spec:
  rootPasswordSecretKeyRef:
    name: mariadb
    key: root-password

  database: seichiassist
  username: mcserver
  passwordSecretKeyRef:
    name: mariadb
    key: mcserver-password

  image:
    repository: mariadb
    tag: "10.11.4"
    pullPolicy: IfNotPresent

  port: 3306

  replicas: 3

  replication:
    enabled: true
    primary:
      podIndex: 0
      automaticFailover: true
    replica:
      waitPoint: AfterSync
      connectionTimeout: 10s
      connectionRetries: 10
      syncTimeout: 10s

  primaryService:
    type: ClusterIP
  primaryConnection:
    secretName: primary-mariadb-conn
    secretTemplate:
      key: dsn

  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - topologyKey: "kubernetes.io/hostname"

  tolerations:
    - key: "mariadb.mmontes.io/ha"
      operator: "Exists"
      effect: "NoSchedule"

  podDisruptionBudget:
    minAvailable: "66%"

  myCnf: |
    [mysqld]
    bind-address=0.0.0.0
    default_storage_engine=InnoDB
    binlog_format=row
    innodb_autoinc_lock_mode=2
    max_allowed_packet=256M

  volumeClaimTemplate:
    resources:
      requests:
        storage: 100Gi
    storageClassName: synology-iscsi-storage
    accessModes:
      - ReadWriteOnce

  livenessProbe:
    exec:
      command:
        - bash
        - -c
        - mysql -u root -p"${MARIADB_ROOT_PASSWORD}" -e "SELECT 1;"
    initialDelaySeconds: 20
    periodSeconds: 10
    timeoutSeconds: 5

  readinessProbe:
    exec:
      command:
        - bash
        - -c
        - mysql -u root -p"${MARIADB_ROOT_PASSWORD}" -e "SELECT 1;"
    initialDelaySeconds: 20
    periodSeconds: 10
    timeoutSeconds: 5

  metrics:
    exporter:
      image:
        repository: prom/mysqld-exporter
        tag: "v0.14.0"
        pullPolicy: IfNotPresent
      resources:
        requests:
          cpu: 300m
          memory: 512Mi
        limits:
          cpu: 300m
          memory: 512Mi
    serviceMonitor:
      prometheusRelease: prometheus
      interval: 10s
      scrapeTimeout: 10s
```

**Is the bug related to Galera?**
- [x] I have checked the [Galera documentation](https://github.com/mariadb-operator/mariadb-operator/blob/main/docs/GALERA.md)
- [x] I have checked the [Galera troubleshooting guide](https://github.com/mariadb-operator/mariadb-operator/blob/main/docs/GALERA.md#troubleshooting)

**Expected behaviour**

**Steps to reproduce the bug**

**Additional context**

**Environment details**:
- Kubernetes version: 1.27.6
- mariadb-operator version: 0.20.0
- Install method: helm
- Install flavour: minimal
