### ISSUE TITLE
[Bug] Apply operator and manifest via helmfile in the same time generate racecondition

### ISSUE THREAD

**Issue by ox1depl** [mariadb-operator/mariadb-operator#267]
Hi.

When I deploy an operator and a manifest practically at the same time, there are problems with the operator webhook certificates.

I carry out the deployment using [helmfile](https://helmfile.readthedocs.io/en/latest/) and hooks:

```
  - name: mariadb-operator
    namespace: operators
    chart: mariadb-operator/mariadb-operator
    version: 0.22.0
    values:
      - "./values/mariadb-operator.yaml"
    hooks:
    - events:
      - "postsync"
      showlogs: true
      command: "kubectl"
      args: ["apply", "-f", "services/dev/mariadb.yaml"]
```

The operator deploys correctly, however, with the manifest itself, I get an error:

```
Error from server (InternalError): error when creating "services/dev/mariadb.yaml": Internal error occurred: failed calling webhook "mmariadb.kb.io": failed to call webhook: Post "[https://mariadb-operator-webhook.operators.svc:443/mutate-mariadb-mmontes-io-v1alpha1-mariadb?timeout=10s](https://mariadb-operator-webhook.operators.svc/mutate-mariadb-mmontes-io-v1alpha1-mariadb?timeout=10s)": x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "mariadb-operator")
```

And in the pod mariadb-operator-webhook-78dd44f8fb-mbhxf, the log can be seen:
```
2023/11/06 01:56:50 http: TLS handshake error from 10.244.0.19:56516: EOF
{"level":"info","ts":1699235860.298318,"logger":"controller-runtime.certwatcher","msg":"Updated current TLS certificate"}
{"level":"info","ts":1699235860.2989285,"logger":"controller-runtime.certwatcher","msg":"Updated current TLS certificate"}
{"level":"info","ts":1699236813.2671363,"logger":"controller-runtime.certwatcher","msg":"Updated current TLS certificate"}
```

It is likely that the operator does not have enough time to regenerate certificates during deployment, which is why the manifest is not being deployed. Waiting 10-30 seconds and deploying the same manifest manually solves the problem.

With other operators like ECK, Redis, Rabbit, there is no such problem, so maybe there is room for improvement, what do you think?

By the way, you're doing a great job with this operator! :1st_place_medal: 

**Environment details**:
- Kubernetes version: AKS v1.25.11
- mariadb-operator version: 0.22.0
- Install method: helmfile
- Install flavour: minimal
