### ISSUE TITLE
[Bug] When enableing metrics,  operator crashes complaining about unrestricted capabilties, etc

### ISSUE THREAD

**Issue by evanrich** [mariadb-operator/mariadb-operator#286]
**Describe the bug**
When enabling metrics in 0.23.1, I get the following output from the operator before it restarts the pod

```
{"level":"info","ts":1701743135.772831,"logger":"KubeAPIWarningLogger","msg":"would violate PodSecurity \"restricted:latest\": allowPrivilegeEscalation != false (container \"metrics\" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (containers \"mariadb\", \"metrics\" must set securityContext.capabilities.drop=[\"ALL\"]), runAsNonRoot != true (pod or containers \"mariadb\", \"metrics\" must set securityContext.runAsNonRoot=true), runAsUser=0 (pod must not set runAsUser=0), seccompProfile (pod or containers \"mariadb\", \"metrics\" must set securityContext.seccompProfile.type to \"RuntimeDefault\" or \"Localhost\")"}
```

Namely:
```
container \"metrics\" must set securityContext.allowPrivilegeEscalation=false)

unrestricted capabilities (containers \"mariadb\", \"metrics\" must set securityContext.capabilities.drop=[\"ALL\"])

runAsNonRoot != true (pod or containers \"mariadb\", \"metrics\" must set securityContext.runAsNonRoot=true

seccompProfile (pod or containers \"mariadb\", \"metrics\" must set securityContext.seccompProfile.type to \"RuntimeDefault\" or \"Localhost\")"}

```

I'm using the following Mariadb CRD:
```
apiVersion: mariadb.mmontes.io/v1alpha1
kind: MariaDB
metadata:
  name: mariadb
spec:
  rootPasswordSecretKeyRef:
    name: mysql-secrets
    key: mysql_root_password

  database: mariadb
  username: mariadb
  passwordSecretKeyRef:
    name: mysql-secrets
    key: mysql_password

  image: mariadb:11.0.3
  imagePullPolicy: IfNotPresent

  port: 3306

  volumeClaimTemplate:
    resources:
      requests:
        storage: 30Gi
    #storageClassName: standard
    accessModes:
      - ReadWriteOnce
  volumes: 
    - name: tmp
      emptyDir: {}
  volumeMounts: 
    - name: tmp
      mountPath: /tmp

  myCnf: |
    [mysqld]
    bind-address=0.0.0.0
    default_storage_engine=InnoDB
    binlog_format=row
    innodb_autoinc_lock_mode=2
    max_allowed_packet=256M

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      memory: 2Gi

  env:
    - name: TZ
      value: SYSTEM

  envFrom:
    - configMapRef:
        name: mariadb

  podSecurityContext:
    runAsUser: 0

  securityContext:
    allowPrivilegeEscalation: false

  livenessProbe:
    exec:
      command:
        - bash
        - -c
        - mariadb -u root -p"${MARIADB_ROOT_PASSWORD}" -e "SELECT 1;"
    initialDelaySeconds: 20
    periodSeconds: 10
    timeoutSeconds: 5

  readinessProbe:
    exec:
      command:
        - bash
        - -c
        - mariadb -u root -p"${MARIADB_ROOT_PASSWORD}" -e "SELECT 1;"
    initialDelaySeconds: 20
    periodSeconds: 10
    timeoutSeconds: 5
  
  podDisruptionBudget:
    maxUnavailable: 50%

  updateStrategy:
    type: RollingUpdate

  service:
    type: ClusterIP

  metrics:
    exporter:
      image: prom/mysqld-exporter:v0.14.0
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 300m
          memory: 512Mi
      port: 9104
    serviceMonitor:
      prometheusRelease: kube-prometheus-stack
      interval: 10s
      scrapeTimeout: 10s
```

This does not appear to affect the operation of the Mariadb instance, only the operator.   I've looked in the operator resources, templates, etc (searched the repo) and can't find mention or examples of the settings to set in helm values for this. 

**Environment details**:
- Kubernetes version: 1.28.4
- mariadb-operator version: 0.23.1 
- Install method: helm

please forgive my ignorance, SecurityPolicies are not my strongpoint in Kubernetes =(

**Comment by evanrich** [comment]
i ended up fixing it using 

```
  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 999

  securityContext:
    runAsNonRoot: true
    allowPrivilegeEscalation: false
```
