### ISSUE TITLE
[Bug]  Unable to validate certificates bis

### ISSUE THREAD

**Issue by jbperrin88** [mariadb-operator/mariadb-operator#287]
**Describe the bug**

Webhook does not validate certificate
I've already see the other case on the same subject but my update (to mariadb-operator.v0.23.1) doesn't resolve this issue

i'm using Argocd to deploy the operator on openshift and i've change my values.

The certificate seems OK from cert-manager and secret ressources

```     
 webhook:
        enabled: true
        ha:
          enabled: true
          replicas: 3
        cert:
          certManager:
            enabled: true
            issuerRef:
              group: certmanager.step.sm
              kind: StepClusterIssuer
              name: stepissuer-stepclusterissuer
            renewBefore: 8h0m0s
            duration: 168h0m0s
```
on event , I see readiness probe failed 

```    
0s          Warning   Unhealthy                pod/mariadb-operator-webhook-776cf98fcf-vjlt9                    Readiness probe failed: Get "http://10.137.0.155:8081/readyz": dial tcp 10.137.0.155:8081: connect: connection refused

0s          Warning   Unhealthy                pod/mariadb-operator-webhook-776cf98fcf-vjlt9                    Readiness probe failed: Get "http://10.137.0.155:8081/readyz": dial tcp 10.137.0.155:8081: connect: connection refused

```  

And i've exactly the same log as the other case related
```
{"level":"info","ts":1701770446.2099118,"logger":"setup","msg":"Validating certs"}
{"level":"info","ts":1701770456.2198622,"logger":"setup","msg":"Validating certs"}
{"level":"error","ts":1701770466.221084,"logger":"setup","msg":"Unable to validate certificates","error":"context deadline exceeded","stacktrace":"github.com/mariadb-operator/mariadb-operator/cmd/controller.glob..func3\n\t/app/cmd/controller/webhook.go:60\ngithub.com/spf13/cobra.(*Command).execute\n\t/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068\ngithub.com/spf13/cobra.(*Command).Execute\n\t/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992\ngithub.com/mariadb-operator/mariadb-operator/cmd/controller.Execute\n\t/app/cmd/controller/root.go:298\nmain.main\n\t/app/cmd/main.go:27\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:267"}
```

**Is the bug related to Galera?**
no

**Expected behaviour**
webhook takes the certificate

**Environment details**:
- Kubernetes version: openshift
- mariadb-operator version:  mariadb-operator.v0.23.1 
- Install method: helm, OLM or static manifests OLM
- Install flavour: custom
