### ISSUE TITLE
[Feature] Provide an abstrction to configure Pod antiaffinity

### ISSUE THREAD

**Issue by mmontes11** [mariadb-operator/mariadb-operator#316]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
[Feature] Provide an abstrction to configure Pod antiaffinity by setting a flag to true when HA is enabled:

```yaml
apiVersion: mariadb.mmontes.io/v1alpha1
kind: MariaDB
metadata:
  name: mariadb-repl
spec:
...
  affinity:
   enableAntiAffinity: true

```

Enable `affinity.enableAntiaffinity` will default `affinity.podAntiaffinity` to:

```yaml
apiVersion: mariadb.mmontes.io/v1alpha1
kind: MariaDB
metadata:
  name: mariadb-repl
spec:
...
  affinity:
   enableAntiAffinity: true
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/instance
                operator: In
                values:
                  - mariadb-repl
          topologyKey: "kubernetes.io/hostname"
 ```
 For achieving this and respect backwards compatibility, we will need to embed `corev1.Affinity` into our own struct:
 ```go
 type Affinity struct {
    corev1.Affinity 
    EnableAntiAffinity bool `json:"enableAntiAffinity,omitempty" webhook:"inmutable"`
 }

**Describe alternatives you've considered**
Expose the user the corev1.Affinity, but this is not ideal as they will need to know the labels beforehand.

**Additional context**
Not providing the label selector in `affinity.podAntiaffinity` results in the following error:
```bash
spec.template.spec.affinity. podAntiAffinity.requiredDuringSchedulingIgnoredDuringExecution[0].labelSelector: a null labelSelector resu lts in matching no pod"
```
