### ISSUE TITLE
[Feature] S3 authentication via Kubernetes `ServiceAccount` (like IRSA)

### ISSUE THREAD

**Issue by mmontes11** [mariadb-operator/mariadb-operator#318]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Authenticate with implicit credentials (service account token) in S3, similarly to AWS IRSA. This way we don't need to explicitly provide the `accessKeyIdSecretKeyRef` and the `secretAccessKeySecretKeyRef`.

For achieving this, we would need to provide extra annotations to the `ServiceAccount` used by the `Backup` so we can bind it with an IAM role in the case of AWS:

```yaml
apiVersion: k8s.mariadb.com/v1alpha1
kind: Backup
metadata:
  name: backup
spec:
  ...
  # metadata that will be inherited by all children objects
  inheritMetadata:
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::<<account_id>>:role/my-role-irsa
```

Does it worth creating a dedicated `serviceAccountMetadata` for this?

```yaml
apiVersion: k8s.mariadb.com/v1alpha1
kind: Backup
metadata:
  name: backup
spec:
  ...
  serviceAccountMetadata:
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::<<account_id>>:role/my-role-irsa
```

We would also need to extend our `S3` object to explicitly declare that we want to inherit the credentials from the IAM role:

```yaml
apiVersion: k8s.mariadb.com/v1alpha1
kind: Backup
metadata:
  name: backup
spec:
  ...
  storage:
    s3:
       inheritFromIAMRole: true
```

Then, we could integrate this in our Minio client, see the following example:
- https://github.com/minio/operator/blob/8b7654688fafae8459ccc505934f915daa45d785/examples/kustomization/sts-example/sample-clients/minio-sdk/go/main.go
- https://min.io/docs/minio/kubernetes/upstream/developers/sts-for-operator.html

**Describe alternatives you've considered**
Authenticate using `accessKeyIdSecretKeyRef` and the `secretAccessKeySecretKeyRef`, but implicit credentials are more convenient.

**Additional context**

Relevant links for context:
- https://github.com/minio/minio/issues/15930
- https://github.com/minio/operator/tree/8b7654688fafae8459ccc505934f915daa45d785/examples/kustomization/sts-example
- https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html
- https://awslabs.github.io/data-on-eks/docs/blueprints/distributed-databases/cloudnative-postgres
- https://github.com/minio/operator/blob/8b7654688fafae8459ccc505934f915daa45d785/examples/kustomization/sts-example/sample-clients/minio-sdk/go/main.go
- https://min.io/docs/minio/kubernetes/upstream/developers/sts-for-operator.html

This has also been requested here:
- https://github.com/mariadb-operator/mariadb-operator/issues/488
