### ISSUE TITLE
[Bug] CA must be mandatory when TLS is enabled

### ISSUE THREAD

**Issue by mmontes11** [mariadb-operator/mariadb-operator#329]
**Documentation**
- [x] I acknowledge that I have read the relevant [documentation](https://github.com/mariadb-operator/mariadb-operator/tree/main/docs).

**Describe the bug**

When enabling `tls` for S3, `caSecretKeyRef` is optional, but it is required to establish trust, as not CA is trusted in our distroless based image:
https://github.com/mariadb-operator/mariadb-operator/blob/3356b15d66bbea88b530a00e17956cd971e68437/api/v1alpha1/base_types.go#L229

Ideally, we could change the struct to be:
```go
type TLS struct {
	// Enabled is a flag to enable TLS.
	// +optional
	// +operator-sdk:csv:customresourcedefinitions:type=spec,xDescriptors={"urn:alm:descriptor:com.tectonic.ui:booleanSwitch"}
	Enabled bool `json:"enabled"`
	// CASecretKeyRef is a reference to a Secret key containing a CA bundle in PEM format used to establish TLS connections with S3.
	// +optional
	// +operator-sdk:csv:customresourcedefinitions:type=spec
	CASecretKeyRef corev1.SecretKeySelector `json:"caSecretKeyRef,omitempty"`
}
```
And add a validation method for the `TLS` struct that it is invoked later on in the validation webhook, to ensure that  the CA is always provided when TLS is enabled.

**Expected behaviour**
When enabling TLS, a reference to a CA bundle must be provided.

**Steps to reproduce the bug**

1. Create a `Backup` with S3 storage and TLS enabled, but no CA:
```yaml
apiVersion: mariadb.mmontes.io/v1alpha1
kind: Backup
metadata:
  name: backup
spec:
  mariaDbRef:
    name: mariadb
  maxRetention: 720h # 30 days
  storage:
    s3:
      bucket: backups
      endpoint: minio.minio.svc.cluster.local:9000
      region:  us-east-1
      accessKeyIdSecretKeyRef:
        name: minio
        key: access-key-id
      secretAccessKeySecretKeyRef:
        name: minio
        key: secret-access-key
      # sessionTokenSecretKeyRef:
      #   name: minio
      #   key: session-token
      tls:
        enabled: true
```

2. The CA path will be defaulted in the `backup`/`restore` subcommand and it will error:
```bash
{"level":"error","ts":1704559907.9339726,"msg":"error getting backup storage","error":"error creating S3 client: error creating Minio client options: error getting transport: error reading CA cert: open s3/pki/tls.crt: no such file or directory","stacktrace":"github.com/mariadb-operator/mariadb-operator/cmd/backup.glob..func1\n\t/app/cmd/backup/main.go:74\ngithub.com/spf13/cobra.(*Command).execute\n\t/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068\ngithub.com/spf13/cobra.(*Command).Execute\n\t/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992\nmain.main\n\t/app/cmd/controller/main.go:333\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:267"}
```

**Additional context**
Reported via Slack:
- https://mariadb-community.slack.com/archives/C06AWJBAC1H/p1704561902860369
