### ISSUE TITLE
[Feature] Add annotations to Backup Job template

### ISSUE THREAD

**Issue by andreasgeisslerdt** [mariadb-operator/mariadb-operator#350]
**Is your feature request related to a problem? Please describe.**
I am using mariadb-operator in a ServiceMesh environment (Istio), which adds to each pod a envoy proxy sidecar.
Setting some general annotations/labels the mariadb pods are well running.

In case of the Backup a job is created. 
In the job pod also a sidecar is injected, which is not deleted after the backup container finished, which leads to the situation, that the job will never be finished. (https://medium.com/redbox-techblog/handling-istio-sidecars-in-kubernetes-jobs-c392661c4af7)
To overcome this problem you have 2 possibilities:
1. add a sidecar container to kill the envoy proxy after the job container finishes
2. add a label to the job template to disable the sidecar injection
```
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            sidecar.istio.io/inject: "false"
```
The option 2 would help in case of mariadb-operator.

**Describe the solution you'd like**

I suggest to add an option in the Backup CRD (https://github.com/mariadb-operator/mariadb-operator/blob/main/docs/API_REFERENCE.md#backupspec) to define additional annotations for job templates

**Describe alternatives you've considered**
The alternative was to force the istio platform to disable the sidecar injection for the specific jobs.
But this is not working, as there is no fixed jobname:
```
sidecarInjectorWebhook:
  # You can use the field called alwaysInjectSelector and neverInjectSelector which will always inject the sidecar or
  # always skip the injection on pods that match that label selector, regardless of the global policy.
  # See https://istio.io/docs/setup/kubernetes/additional-setup/sidecar-injection/#more-control-adding-exceptions
  neverInjectSelector:
    - matchExpressions:
        - {key: job-name, operator: In, values: ["..."]}
```

**Environment details**:
- Kubernetes version: 1.27.5
- Kubernetes distribution: Vanilla
- mariadb-operator version: 0,24,0
- Install method: helm via ArgoCD
- Install flavor: recommended

**Additional context**

**Comment by mmontes11** [comment]
Hey there @andreasgeisslerdt ! Thanks for reporting this.

I agree, the option 2 seems better to integrate with `mariadb-operator`. You can actually achive this by specifying `spec.inheritMetadata` in the `MariaDB` resource:

```yaml
apiVersion: mariadb.mmontes.io/v1alpha1
kind: MariaDB
metadata:
  name: mariadb
spec:
  # metadata that will be inherited by all children objects
  inheritMetadata:
    labels:
      database.myorg.io: mariadb  
    annotations:
      database.myorg.io: mariadb

  volumeClaimTemplate:
    annotations:
      database.myorg.io: mariadb
    resources:
      requests:
        storage: 1Gi
    accessModes:
      - ReadWriteOnce
```

and then, when you create a `Backup` referring to it:

```yaml
apiVersion: mariadb.mmontes.io/v1alpha1
kind: Backup
metadata:
  name: backup
spec:
  mariaDbRef:
    name: mariadb
  storage:
    persistentVolumeClaim:
      resources:
        requests:
          storage: 100Mi
      accessModes:
        - ReadWriteOnce
  args:
    - --single-transaction
    - --all-databases
```

The following `Pod` will eventually be created:

```yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    database.myorg.io: mariadb
  creationTimestamp: "2024-01-25T16:52:32Z"
  finalizers:
  - batch.kubernetes.io/job-tracking
  generateName: backup-
  labels:
    batch.kubernetes.io/controller-uid: 28688b01-21bd-4cb7-8ce1-dd1fe8599259
    batch.kubernetes.io/job-name: backup
    controller-uid: 28688b01-21bd-4cb7-8ce1-dd1fe8599259
    database.myorg.io: mariadb
    job-name: backup
  name: backup-2sc28
...
``` 

Which I believe it should cover this case, could you confirm please? 🙏🏻
