### ISSUE TITLE
[Bug] Propagate `spec.inheritMetadata` to `Deployment` template

### ISSUE THREAD

**Issue by mmontes11** [mariadb-operator/mariadb-operator#351]
**Documentation**
- [x] I acknowledge that I have read the relevant [documentation](https://github.com/mariadb-operator/mariadb-operator/tree/main/docs).

**Describe the bug**
When a MariaDB with [prometheus metrics](https://github.com/mariadb-operator/mariadb-operator/blob/main/docs/METRICS.md) is created, if we specify `spec.inheritMetadata`, the labels and annotations are propagated to the exporter `Deployment` metadata, but not ot its Pods.

**Expected behaviour**
Like in the MariaDB `StatefulSet`, the exporter `Deployment` template inherit the `spec.inheritMetadata` , so the created `Pods` also do.

**Steps to reproduce the bug**

1. Create a MariaDB with `spec.inheritMetadata` and `spec.metrics:
```yaml
apiVersion: mariadb.mmontes.io/v1alpha1
kind: MariaDB
metadata:
  name: mariadb
spec:
  # metadata that will be inherited by all children objects
  inheritMetadata:
    labels:
      database.myorg.io: mariadb  
    annotations:
      database.myorg.io: mariadb

  volumeClaimTemplate:
    annotations:
      database.myorg.io: mariadb
    resources:
      requests:
        storage: 1Gi
    accessModes:
      - ReadWriteOnce

  service:
    type: LoadBalancer
    annotations:
      metallb.universe.tf/loadBalancerIPs: 172.18.0.20

  metrics:
    enabled: true
``` 
2. The `Deployment` does inherit the metadata, but its `Pod` template doesn't
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    database.myorg.io: mariadb
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2024-01-25T11:25:21Z"
  generation: 1
  labels:
    database.myorg.io: mariadb
  name: mariadb-metrics
spec:
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: mariadb
        app.kubernetes.io/name: exporter
```

**Additional context**
This is how we achieve it in the `StatefulSet`:
- https://github.com/mariadb-operator/mariadb-operator/blob/main/pkg/builder/statefulset_builder.go#L89

We should do the same here:
- https://github.com/mariadb-operator/mariadb-operator/blob/main/pkg/builder/deployment_buider.go#L24
