### ISSUE TITLE
[Bug] Helm Chart secretAnnotations is not properly indented

### ISSUE THREAD

**Issue by jescarri** [mariadb-operator/mariadb-operator#375]
**Documentation**
- [*] I acknowledge that I have read the relevant [documentation](https://github.com/mariadb-operator/mariadb-operator/tree/main/docs).

**Describe the bug**

When deploying the operator via helm + argo-cd the webhook secret is considered part of the helm release because label propagation, an easy fix is to add this annotation to the secret:

```
argocd.argoproj.io/compare-options: IgnoreExtraneous 
```

However the helm chart is indenting 4 spaces vs 6:

https://github.com/mariadb-operator/mariadb-operator/blob/0ad5569f2175a68ad167cd191e97ae9aeebca6e5/deploy/charts/mariadb-operator/templates/webhook-certificate.yaml#L45

When the helm chart is rendered using theve values:

```
fullnameOverride: "mariadb-operator"
logLevel: INFO
ha:
  enabled: false
metrics:
  enabled: true
webhook:
  cert:
    certManager:
      enabled: true
      issuerRef:
        group: cert-manager.io
        kind: ClusterIssuer
        name: selfsigned
    secretAnnotations:
       argocd.argoproj.io/compare-options: IgnoreExtraneous
  serviceMonitor:
    enabled: true

```

The result is:

```
---
# Source: mariadb-operator/templates/webhook-certificate.yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mariadb-operator-webhook-cert
  labels:
    helm.sh/chart: mariadb-operator-0.25.0
    app.kubernetes.io/name: mariadb-operator-webhook
    app.kubernetes.io/instance: mariadb-operator
    app.kubernetes.io/version: "v0.0.25"
    app.kubernetes.io/managed-by: Helm
spec:
  commonName: mariadb-operator-webhook.mariadb-operator.svc
  dnsNames:
    - mariadb-operator-webhook.mariadb-operator.svc.cluster.local
    - mariadb-operator-webhook.mariadb-operator.svc
    - mariadb-operator-webhook.mariadb-operator
    - mariadb-operator-webhook
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: selfsigned
  secretName: mariadb-operator-webhook-cert
  secretTemplate:
    labels:
      helm.sh/chart: mariadb-operator-0.25.0
      app.kubernetes.io/name: mariadb-operator-webhook
      app.kubernetes.io/instance: mariadb-operator
      app.kubernetes.io/version: "v0.0.25"
      app.kubernetes.io/managed-by: Helm
    annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous

```
Expected result is:

```
...
    annotations:
       argocd.argoproj.io/compare-options: IgnoreExtraneous
```
for code blocks of your kubectl output or YAML files.

**Expected behaviour**

Chart properly indenting extra secret annotations

**Steps to reproduce the bug**

Run helm template with the provided values.
