### ISSUE TITLE
[Bug] 0.25.0 maxscale statefulset failing to start

### ISSUE THREAD

**Issue by pasztorl** [mariadb-operator/mariadb-operator#381]
**Documentation**

- [ x ] I acknowledge that I have read the relevant [documentation](https://github.com/mariadb-operator/mariadb-operator/tree/main/docs).

**Describe the bug**

I'm testing the latest operator by creating a mariadb replication with maxscale. The maxscale statefulset pods failing to start because of a permission problem.
Here is the log output from the maxscale pod: 
```
2024-02-13 13:53:51   notice : MaxScale will be run in the terminal process.
2024-02-13 13:53:51   notice : /etc/config/..2024_02_13_13_53_43.4123823925/maxscale.cnf.d does not exist, not reading.
2024-02-13 13:53:51   notice : /var/lib/maxscale/maxscale.cnf.d does not exist, not reading.
2024-02-13 13:53:51   notice : Using up to 2.29GiB of memory for query classifier cache
2024-02-13 13:53:51   notice : syslog logging is disabled.
2024-02-13 13:53:51   notice : maxlog logging is enabled.
2024-02-13 13:53:51   error  : Failed to create directory '/var/lib/maxscale/maxscale.cnf.d': 13, Permission denied
2024-02-13 13:53:51   alert  : Can't access '/var/lib/maxscale/maxscale.cnf.d'.: No such file or directory
```
I see that the pod have a volume which mounted to this directory, the problem is that it tries to create a directory inside this mountpoint as maxscale user which is not allowed by the mountpoint filesystem permissions.

Here is the statefulset spec for the maxscale what the operator created:
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: test1-mariadb-maxscale
  namespace: test1-mariadb
  ...
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: test1-mariadb-maxscale
      app.kubernetes.io/name: maxscale
  template:
    metadata:
      name: test1-mariadb-maxscale
      namespace: test1-mariadb
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: test1-mariadb-maxscale
        app.kubernetes.io/name: maxscale
    spec:
      volumes:
        - name: config
          secret:
            secretName: test1-mariadb-maxscale-config
            defaultMode: 420
      containers:
        - name: maxscale
          image: mariadb/maxscale:23.08
          command:
            - maxscale
          args:
            - '--config'
            - /etc/config/maxscale.cnf
            - '-dU'
            - maxscale
            - '-l'
            - stdout
          ports:
            - name: admin
              containerPort: 8989
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: storage
              mountPath: /var/lib/maxscale
            - name: config
              mountPath: /etc/config
          livenessProbe:
            httpGet:
              path: /
              port: 8989
              scheme: HTTP
            initialDelaySeconds: 20
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 8989
              scheme: HTTP
            initialDelaySeconds: 20
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: test1-mariadb-maxscale
      serviceAccount: test1-mariadb-maxscale
      automountServiceAccountToken: false
      securityContext: {}
      schedulerName: default-scheduler
  volumeClaimTemplates:
    - kind: PersistentVolumeClaim
      apiVersion: v1
      metadata:
        name: storage
        creationTimestamp: null
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 100Mi
        volumeMode: Filesystem
  serviceName: test1-mariadb-maxscale-internal
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
  revisionHistoryLimit: 10
```
I've also tried image: mariadb/maxscale:23.08.4 with the same result.

MariaDB created with this manifest:
```
apiVersion: mariadb.mmontes.io/v1alpha1
kind: MariaDB
metadata:
  name: test1-mariadb
  namespace: test1-mariadb
spec:
  ephemeralStorage: false
  image: mariadb:11.2.3
  maxScale:
    connection:
      port: 3306
      secretName: test1-mariadb-connection
    enabled: true
    kubernetesService:
      type: ClusterIP
    replicas: 1
  maxScaleRef:
    name: test1-mariadb-maxscale
    namespace: test1-mariadb
  metrics:
    enabled: true
    exporter:
      image: prom/mysqld-exporter:v0.15.1
      port: 9104
    passwordSecretKeyRef:
      key: password
      name: test1-mariadb-metrics-password
    serviceMonitor: {}
    username: test1-mariadb-metrics
  port: 3306
  primaryService:
    type: ClusterIP
  replicas: 3
  replication:
    enabled: true
    primary:
      automaticFailover: true
      podIndex: 0
    probesEnabled: false
    replica:
      connectionRetries: 10
      connectionTimeout: 10s
      gtid: CurrentPos
      syncTimeout: 10s
      waitPoint: AfterSync
    syncBinlog: true
  rootEmptyPassword: false
  rootPasswordSecretKeyRef:
    key: password
    name: test1-mariadb-root-password
  secondaryService:
    type: ClusterIP
  service:
    type: ClusterIP
  volumeClaimTemplate:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 20Gi
```

**Comment by pasztorl** [comment]
I tried to set up an initcontainer (to do the chown) inside the [MaxScaleSpec](https://github.com/mariadb-operator/mariadb-operator/issues/381#maxscalespec). The CRD accepted it, but the operator seems to ignored it.

**Comment by DrZoidberg09** [comment]
Same problem here

**Comment by K-MeLeOn** [comment]
Mhh, strange, same problem, even with podSecurityContext set to:
```
maxScale:
   podSecurityContext:
      runAsUser: 0
```

**Comment by pasztorl** [comment]
https://jira.mariadb.org/plugins/servlet/mobile#issue/MXS-4984

**Comment by pasztorl** [comment]
But another problem (related to operator) is that it ignore the initContainer.

**Comment by mmontes11** [comment]
Hey there! thanks for reporting.

As you mentioned, it looks like a problem of the image that can be mitigated with an `initContainer`. For now I would

Adding support for `initContainer` to `MaxScale` would be a one liner, just add it to this this builder:
https://github.com/mariadb-operator/mariadb-operator/blob/467bf3bd4df56fa5d5905f8e21f055c812a6a580/pkg/builder/statefulset_builder.go#L144

Like we currently do for `MariaDB`: 
https://github.com/mariadb-operator/mariadb-operator/blob/467bf3bd4df56fa5d5905f8e21f055c812a6a580/pkg/builder/statefulset_builder.go#L113

Contributions welcome! I will do it myself before the next release if needed 👍🏻

**Comment by mmontes11** [comment]
Out of curioristy, which storage are you using?

**Comment by K-MeLeOn** [comment]
> Mhh, strange, same problem, even with podSecurityContext set to:
> 
> ```
> maxScale:
>    podSecurityContext:
>       runAsUser: 0
> ```

It works now, I use longhorn for local storage, but as I see, I need a minimum of 300Mi of storage and set security context to work. Hope it can help.

```
  maxScale:
    enabled: true
    config:
      volumeClaimTemplate:
        resources:
          requests:
            storage: 300Mi
        storageClassName: longhorn-encrypted-global-noretain
        accessModes:
          - ReadWriteMany
    podSecurityContext:
      runAsUser: 0 # For galera, caused by longhorn storage permission
```
```

**Comment by mmontes11** [comment]
@K-MeLeOn it does, thank you!.

Actually, some Longhorn users reported the same error with Galera:
- https://github.com/mariadb-operator/mariadb-operator/blob/main/docs/GALERA.md#permission-denied-writing-galera-configuration

Not a Longhorn user unfortunately, maybe something we could do for preventing this? Will take a closer look to the Longhorn docs

**Comment by K-MeLeOn** [comment]
> @K-MeLeOn it does, thank you!.
> 
> Actually, some Longhorn users reported the same error with Galera:
> 
>     * https://github.com/mariadb-operator/mariadb-operator/blob/main/docs/GALERA.md#permission-denied-writing-galera-configuration
> 
> 
> Not a Longhorn user unfortunately, maybe something we could do for preventing this? Will take a closer look to the Longhorn docs

My favorite actual hack with longhorn is to add a busybox image to grant permission to good user or group id.
It's muddy but it works:
```yaml
- name: volume-hack
  image: busybox
  command:
    - /bin/sh
    - -c
    - chown -R USER_ID:GROUP_ID /var/lib/maxscale
  securityContext:
    runAsUser: 0
```

**Comment by mmontes11** [comment]
> My favorite longhorn hack is to add a busybox image to grant permission to the right user or group.
It's ugly but it works

This will be doable after we add support to the `initContainers` in `MaxScale` in this release.

**Comment by DrZoidberg09** [comment]
Unfortunately, runAsUser: 0 did not work for me. I tried it with Hetzner-CSI (RWO) and with NFS-CSI (RWX), same result.

**Comment by DrZoidberg09** [comment]
Yes, I used your example from above for NFS and 10 Gi for Hetzner. No success.

**Comment by K-MeLeOn** [comment]
Mmmh, after many recreation, I got the error again with RWO, whit RWX it's working, this is a strange behavior, need to wait the `initContainer` update I think.

**Comment by K-MeLeOn** [comment]
> [...]
> 
> 
> I guess it should work, but just to confirm.

It works with :
```yaml
      initContainers:
        - name: volume-hack
          image: busybox
          command:
            - /bin/sh
            - -c
            - chown -R 998:996 /var/lib/maxscale
          resources: {}
          volumeMounts:
            - name: storage
              mountPath: /var/lib/maxscale
```
Looking for the user and group id :
```
less /etc/passwd
```
![20240218_202339](https://github.com/mariadb-operator/mariadb-operator/assets/47109782/71b7cdf0-18a8-4a8a-8e1d-53d13745eec0)
 
Applying `initContainers` config.

Folder tree :
![20240218_202311](https://github.com/mariadb-operator/mariadb-operator/assets/47109782/2d6a6efc-23a4-4101-862e-d12569da003d)

StatefullSet status :
![20240218_202859](https://github.com/mariadb-operator/mariadb-operator/assets/47109782/d600341a-3efa-4ac7-9809-07ec558462ea)


Maxscale log :
![20240218_202111](https://github.com/mariadb-operator/mariadb-operator/assets/47109782/f460b34e-0800-478c-9f7f-ac6f62c33091)

**Comment by DrZoidberg09** [comment]
Same problem here again. However, it is not a matter of password. This is mariadb-operator / (maxscale-admin secret password).

The Service is exposed via ingress.

However, when I log in, I immediatley get logged out with this error in the console:

` ERROR  [https://{URL}/js/app~06837ae4.65c68fab.js:1:fetchLoggedInUserAttrs] 
Object { stack: "o@https://{URL}/js/app~2a42e354.252e49c0.js:1:1881\nX@https:/{URL}n/js/app~2a42e354.252e49c0.js:1:22807\nh@https://{URL}/js/app~2a42e354.252e49c0.js:1:25959\n", message: "Request failed with status code 401", name: "AxiosError", code: "ERR_BAD_REQUEST", config: {…}, request: XMLHttpRequest, response: {…} }
​
code: "ERR_BAD_REQUEST"
​
config: Object { timeout: 0, xsrfCookieName: "XSRF-TOKEN", xsrfHeaderName: "X-XSRF-TOKEN", … }
​
message: "Request failed with status code 401"
​
name: "AxiosError"
​
request: XMLHttpRequest { readyState: 4, timeout: 0, withCredentials: false, … }
​
response: Object { data: {…}, status: 401, statusText: "", … }
​
stack: "o@https://{URL}/js/app~2a42e354.252e49c0.js:1:1881\nX@https://{URL}/js/app~2a42e354.252e49c0.js:1:22807\nh@https://{URL}/js/app~2a42e354.252e49c0.js:1:25959\n"
​
<prototype>: Object { constructor: o(e, t, n, r, o), toJSON: toJSON(), stack: "", … }
app~4e350ea9.0250b2a8.js:1:31181
    error https://{URL}/js/app~4e350ea9.0250b2a8.js:1
    fetchLoggedInUserAttrs https://{URL}/js/app~06837ae4.65c68fab.js:1
`

**Comment by mmontes11** [comment]
Thanks a lot for testing this @K-MeLeOn ! Very much appreciated 🙏🏻  I can confidently add the `initContainer` for the next release now, just as a temporary measure before the image gets fixed.

> I'm not sure, because module successfully load, isn't neccessary to write in this directory ?) 

Not entirely sure about this, I will ask and add the permissions in the `initContainer` if needed as you suggested.

**Comment by mmontes11** [comment]
> After the init container finished I started the operator. The MariaDB and MaxScale crd went true, I see the new config in the maxscale pod's log.

Good news @pasztorl ! This if the resources are in ready status we are good to go. I will keep this issue open until we add the `initContainer` 

> Now the problem is I can't log in to the admin console with the password from the adminPasswordSecretKeyRef. I also tried to use maxctrl and got permission denied.

@pasztorl / @DrZoidberg09 

That's a different problem, could you please file another issue for this? The operator uses this credentials to create resources in the MaxScale API, so if you don't see any error log, they should be valid. Be sure to use the `mariadb-operator` user and the following password:

```bash
kubectl get secret mariadb-operator-admin -o jsonpath="{.password}" | base64 -d
```

Also, take into account that, if you are accessing MaxScale via an Ingress controller, the headers might have been modified, which might result in a 401. Please try to access to the MaxScale instance directly via a port-forward to understand where the problem is first.

**Comment by pasztorl** [comment]
Update: now I dropped the namespace and recreated the MariaDB crd. When MaxScale statefulset created i stopped (kill -STOP) the operator. I fixed the permissions, then kill -CONT on the operator process.
Still can't access with the "admin" user, but.. I can log in with the mariadb-operator user using the admin password from the admin secret. So it looks like this secret holds the mariadb-operator user password not for the admin user?

Related logs from the maxscale pod:


```
2024-02-19 10:06:01   notice : Create network user 'mariadb-operator'
2024-02-19 10:06:01   notice : Deleted network user 'admin'
```

In the operator logs:

```
{"level":"info","ts":1708337161.7916281,"msg":"Configuring admin in MaxScale Pod","controller":"maxscale","controllerGroup":"mariadb.mmontes.io","controllerKind":"MaxScale","MaxScale":{"name":"mariadb-maxscale","namespace":"mariadb-test"},"namespace":"mariadb-test","name":"mariadb-maxscale","reconcileID":"0e36cf39-afb0-4d9d-9b2f-3bc71203b0a6","pod":"mariadb-maxscale-0"}
{"level":"info","ts":1708337161.8184333,"msg":"Initializing MaxScale Pod","controller":"maxscale","controllerGroup":"mariadb.mmontes.io","controllerKind":"MaxScale","MaxScale":{"name":"mariadb-maxscale","namespace":"mariadb-test"},"namespace":"mariadb-test","name":"mariadb-maxscale","reconcileID":"0e36cf39-afb0-4d9d-9b2f-3bc71203b0a6","pod":"mariadb-maxscale-0"}

```

**Comment by mmontes11** [comment]
>  So it looks like this secret holds the mariadb-operator user password not for the admin user?

You get it right.The secret contains the password not the user itself.

The logs above are expected ☝🏻 .

**Comment by K-MeLeOn** [comment]
> Thanks a lot for testing this @K-MeLeOn ! Very much appreciated 🙏🏻 I can confidently add the `initContainer` for the next release now, just as a temporary measure before the image gets fixed.
> 
> > I'm not sure, because module successfully load, isn't neccessary to write in this directory ?)
> 
> Not entirely sure about this, I will ask and add the permissions in the `initContainer` if needed as you suggested.

Oops, just think that this part can't work, because it's part of the container itself ! It's module already on it (`libpp_sqlite.so`).
```yaml
 && chown -R 998:996 /usr/lib64/maxscale
```

**Comment by lwj5** [comment]
Hi all,

could we use fscontext instead, and for CSI/storage provider that do not support fscontext, we allow the user to add volume initContainer?

This prevents the need to a chown -R and an additional container for some providers.

This is what is used in bitnami helm charts as well.

```yaml
      securityContext:
        fsGroup: 996
```

**Comment by mmontes11** [comment]
Hey @lwj5 ! 

Thanks for your suggestion, I've manged to spin up a `MaxScale` without the chown initContainer but adding the following to the spec:

```yaml
  podSecurityContext:
    fsGroup: 996
``` 

I am using the [synology CSI driver](https://github.com/SynologyOpenSource/synology-csi), which by default has `fsGroupPolicy = ReadWriteOnceWithFSType`:
```yaml
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: csi.san.synology.com
spec:
  attachRequired: true
  fsGroupPolicy: ReadWriteOnceWithFSType
  podInfoOnMount: true
  requiresRepublish: false
  storageCapacity: false
  volumeLifecycleModes:
  - Persistent
```

For context, the CSI driver specification allows to specify a `fsGroup` in order to delegate to the kubelet the permissions change:
https://kubernetes-csi.github.io/docs/support-fsgroup.html

Most of the CSI drivers nowadays support by default compatible values `fsGroupPolicy`:
- [rook](https://github.com/rook/rook/blob/7ca738e7b279196878d86d3d6a086693eaf1c238/deploy/charts/rook-ceph/values.yaml#L110)
- [ceph](https://github.com/ceph/ceph-csi/blob/328e4e5a0fa06521c5508b94a5b7ff250ada1681/deploy/rbd/kubernetes/csidriver.yaml#L17)
- [aws-ebs-csi-driver](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/charts/aws-ebs-csi-driver/templates/csidriver.yaml#L11)


Not sure about longhorn though, see the following issues:
- https://github.com/longhorn/longhorn/issues/2131
- https://github.com/longhorn/longhorn/issues/3762

I think it will be sensible to default the `fsGroup` by default instead of adding an initContainer running as root. The latter implies extra container orchestration and it could be seen as a red flag in terms of security. In any case, adding `initContainers` by the user is now supported! 

I will be moving forward with this change and I will add a troubleshooting section in the `MaxScale` docs.

Thanks! Let me know what you think.
