### ISSUE TITLE
[Feature] Add timezone value to Backup resources.

### ISSUE THREAD

**Issue by codestation** [mariadb-operator/mariadb-operator#383]
**Is your feature request related to a problem? Please describe.**

When configuring a Backup resource the created CronJob will always be run in the UTC timezone.  One cannot choose their prefered timezone.

**Describe the solution you'd like**

Since Kubernetes 1.27 there is a `.spec.timeZone` value available to CronJobs. Make this available to all the resources with a `schedule` field (like `Backup`).

**Describe alternatives you've considered**

**Environment details**:
- Kubernetes version: 1.28
- Kubernetes distribution: k3s
- mariadb-operator version: 0.0.25
- Install method: helm
- Install flavor: recommended

**Additional context**

**Comment by mmontes11** [comment]
Hey @codestation ! Thanks for bringing this up.

This will be a nice addition for the `Backup` and `SqlJob` resources, which are reconciled into `CronJobs as you correctly pointed out.

> Since Kubernetes 1.27 

I'm guessing that we will need to use the discovery client to check whether we are running in Kubernetes >= 1.27: 
https://pkg.go.dev/k8s.io/client-go/discovery 

Contributions are welcome!

**Comment by mbezhanov** [comment]
> Since Kubernetes 1.27 there is a .spec.timeZone value available to CronJobs.

Kubernetes 1.27 is when the feature graduated from `Beta` to `GA`. However, the `timeZone` field has been available since Kubernetes 1.24, with 1.25 marking it as `Beta` and enabling its feature gate by default (meaning that since 1.25, administrators had to explicitly disable this feature if they didn't want their clusters to support it).

See: https://github.com/kubernetes/enhancements/issues/3140

Take the following `CronJob` manifest, for example: <details><summary><b>cronjob.yaml</b></summary>

```yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: example-cronjob
spec:
  schedule: "0 12 * * *" # Every day at noon
  timeZone: "America/New_York" # Specify the time zone
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: example
            image: busybox
            args:
            - /bin/sh
            - -c
            - date; echo "Hello from the Kubernetes CronJob!"
          restartPolicy: OnFailure
```

</details>

Even with the `CronJobTimeZone` feature gate disabled, no errors will be thrown on Kubernetes versions >= 1.24 because of a `timeZone` field being present in the `CronJob` manifest, as the field already exists in the `CronJob` schema definition.

For Kubernetes <= 1.23, the API server drops any unrecognized fields from the input that it receives. So even if the operator sends a `timeZone` field with the `CronJob` creation request, the API server will still fulfill the request without throwing an error (just ignoring the `timeZone` field).

See: https://kubernetes.io/docs/reference/using-api/api-concepts/#field-validation

---

This makes me think that implementing this in a way similar to #721 (without using a `DiscoveryClient`) won't cause any issues.  Is there something I may be missing here @codestation @mmontes11?
