### ISSUE TITLE
[Bug] Anti Affinity

### ISSUE THREAD

**Issue by drag0n141** [mariadb-operator/mariadb-operator#442]
**Documentation**
- [x] I acknowledge that I have read the relevant [documentation](https://github.com/mariadb-operator/mariadb-operator/tree/main/docs).

**Describe the bug**
When is set `enableAntiAffinity: true` and bootstrap the affinity rule is also set to the galera-cluster-restore pod. But i have only three nodes and because of that the restore can not start. I think it would be the best when the affinity rule is not set to the restore pod.

**Environment details**:
- Kubernetes version: 1.29.2
- Kubernetes distribution: k3s
- mariadb-operator version: 0.27.0
- Install method: helm
- Install flavor: recommended

**Comment by drag0n141** [comment]
I have tested now a little bit more, the metrics pods have the same problem. It can not deployed when you have a galera cluster with 3 replicas and "only" three nodes.

**Comment by sennerholm** [comment]
It's also impact the metric pod if you try to set it to not be used there, like
```
apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb
spec:
  affinity:
    enableAntiAffinity: true
  metrics:
    enabled: true
    exporter:
      affinity:
        enableAntiAffinity: false
```

**Comment by sennerholm** [comment]
In the new 0.32.0 it's not working. The antiaffinity rules on the metric deployment is removed (step 1), but the generated rules on the Statefulset is using
`app.kubernetes.io/instance=mariadb`
and that is also set on the metric pod...

**Comment by mmontes11** [comment]
Hey there! Thanks for reporting.

Metrics anti-affinity issue has been sorted our in the following PR:
- https://github.com/mariadb-operator/mariadb-operator/pull/446

Regarding the `Restore`,  the issue is that we are re-using the same `PodTemplate` as `MariaDB`, and therefore the same anti-affinity-rules as well:
https://github.com/mariadb-operator/mariadb-operator/blob/470218ee348a99705d8eb1b1592423ded97a4b97/pkg/builder/restore_builder.go#L22

Will raise a PR soon!

**Comment by mmontes11** [comment]
In any case, you are still able to provide the anti-affinity rules yourself:

```yaml
kind: MariaDB
metadata:
  name: mariadb-galera
spec:
...
  affinity:
    enableAntiAffinity: true
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: <any-label>
            operator: In
            values:
            - <any-value>
        topologyKey: kubernetes.io/hostname
```

and create `Restores` yourself instead of using `spec.bootstrapFrom. This is just FYI, in order to unblock you, but of course, the default anti-affinity rules and the default `Restore` should work and will be fixed in the next release!

**Comment by sennerholm** [comment]
I got it working for metric with
```
apiVersion: v1
items:
- apiVersion: k8s.mariadb.com/v1alpha1
  kind: MariaDB
  metadata:
    annotations:
    name: mariadb
  spec:
    affinity:
      enableAntiAffinity: true
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: app.kubernetes.io/instance
              operator: In
              values:
              - mariadb
            - key: app.kubernetes.io/name
              operator: In
              values:
              - mariadb
          topologyKey: kubernetes.io/hostname
  metrics:
    enabled: true
    exporter:
      affinity:
        enableAntiAffinity: false          
```

**Comment by mmontes11** [comment]
We have supported `affinity` for the `Restore` `Job` with this PR:
- https://github.com/mariadb-operator/mariadb-operator/pull/448

Now you can disable anti-affinity in the `Restore` `Job`:
```yaml
apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb-galera
spec:
...
  bootstrapFrom:
    s3:
      bucket: backups
      endpoint: minio.minio.svc.cluster.local:9000
      accessKeyIdSecretKeyRef:
        name: minio
        key: access-key-id
      secretAccessKeySecretKeyRef:
        name: minio
        key: secret-access-key
      tls:
        enabled: true
    restoreJob:
       affinity:
          enableAntiAffinity: false
    targetRecoveryTime: 2023-12-19T09:00:00Z

  affinity:
    enableAntiAffinity: true
```


Closing!
