### ISSUE TITLE
[Feature] Support for `podMetadata` in `MariaDB`. Deprecate `podAnnotations`

### ISSUE THREAD

**Issue by mmontes11** [mariadb-operator/mariadb-operator#450]
**Describe the solution you'd like**
Currently, we support adding specific `medata` to all children resources via `inheritMetadata`, but there will be great if we could specify dedicated `metadata` for `MariaDB` `Pods`:
```yaml
apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb
spec:
  # metadata that will be inherited by all children objects
  inheritMetadata:
    labels:
      database.myorg.io: mariadb
    annotations:
      database.myorg.io: mariadb
  podMetadata:
     labels:
        sidecar.istio.io/inject: "false"
     annotations:
        sidecar.istio.io/inject: "false"
```

**Describe alternatives you've considered**
Use the current `podAnnotations` field, but we should deprecate that one and use the new [Metadata](https://github.com/mariadb-operator/mariadb-operator/blob/d2be99633b984fcc076efd1133008c1dd022e992/api/v1alpha1/base_types.go#L414) type

**Additional context**
Related to:
- https://github.com/mariadb-operator/mariadb-operator/issues/442
