### ISSUE TITLE
[Bug] Remove `MariaDB` initialization leftovers

### ISSUE THREAD

**Issue by mmontes11** [mariadb-operator/mariadb-operator#451]
**Describe the bug**
Some resources are left behind during the `MariaDB initialization:
- `Restore` resource used to perform the `bootstrapFrom`.
- `Galera` init `ConfigMap` used as entrypoint of the init `Job`. 

**Expected behaviour**
Clean up the resources after the initialization is done.

**Steps to reproduce the bug**
Create a `MariaDB` galera bootstrapping from any source:
```yaml
apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb-galera
spec:
  storage:
    size: 1Gi

  replicas: 3

  galera:
    enabled: true
    
  bootstrapFrom:
    backupRef:
      name: backup
```
