### ISSUE TITLE
[Feature] Support for `interitMetadata` and `podMetadata` in `MaxScale` 

### ISSUE THREAD

**Issue by mmontes11** [mariadb-operator/mariadb-operator#454]
**Describe the solution you'd like**
The same way we do for `MariaDB`, provide support for metadata in `MaxScale` via `interitMetadata` and `podMetadata`:
```yaml
apiVersion: k8s.mariadb.com/v1alpha1
kind: MaxScale
metadata:
  name: mariadb
spec:
  # metadata that will be inherited by all children objects
  inheritMetadata:
    labels:
      database.myorg.io: mariadb
    annotations:
      database.myorg.io: mariadb
  podMetadata:
     labels:
        sidecar.istio.io/inject: "false"
     annotations:
        sidecar.istio.io/inject: "false"
```

**Describe alternatives you've considered**
Keep it as it is inheriting metadata from `MariaDB`, but that may not be enoug flexibility to integrate with other CNCF projects like Istio.
