### ISSUE TITLE
[Bug] Restore job locks up on Galera cluster if backup contains `LOCK TABLES` statements

### ISSUE THREAD

**Issue by comminutus** [mariadb-operator/mariadb-operator#462]
**Documentation**
- [X] I acknowledge that I have read the relevant [documentation](https://github.com/mariadb-operator/mariadb-operator/tree/main/docs).

**Describe the bug**
When using the `mariadb-operator` `Backup` CRD, it creates a .sql file on the backup target that contains `LOCK TABLES` and `UNLOCK TABLES` statements.

When restoring from a backup created like this into a Galera cluster, it causes the restore job / process to lock up / freeze / hang.

This is likely due to what documentation mentions for `LOCK TABLES`:

> LOCK TABLES [doesn't work when using Galera cluster](https://mariadb.com/kb/en/mariadb-galera-cluster-known-limitations/). You may experience crashes or locks when used with Galera.

(from https://mariadb.com/kb/en/lock-tables/#limitations)

**Expected behaviour**
When using MariaDB in a Galera cluster, the backup files shouldn't produce scripts that contain `LOCK TABLES` statements.

**Steps to reproduce the bug**
1. Create a MariaDB cluster with the operator using a Galera configuration
2. Create a Backup
3. Try restoring from this Backup

**Debug information**
Creating a restore job using a similar CRD as below helps diagnose the problem since the verbose output will show the last statement that was being executed.  In this case, it was a `LOCK TABLES` statement:
```
apiVersion: k8s.mariadb.com/v1alpha1
kind: Restore
metadata:
  name: galera-restore
  namespace: default
spec:
  args:
    - "--verbose"
  mariaDbRef:
    name: mariadb-galera
  volume:
    nfs:
      server: my-nas
      path: /volume1/mariadb/backup/daily
  targetRecoveryTime: 2024-03-08T04:00:01Z
  resources:
    requests:
      cpu: 500m
      memory: 256Mi
    limits:
      memory: 1Gi
  podSecurityContext:
    runAsUser: 0
```

**Environment details**:
- Kubernetes version: v1.29.1+k3s2
- Kubernetes distribution: k3s
- mariadb-operator version: v0.27.0
- Install method: helm via flux
- Install flavor: recommended

**Additional context**
Please refer to this thread for the origin of this bug:  https://mariadb-community.slack.com/archives/C06AWJBAC1H/p1708538007292899
