### ISSUE TITLE
Can't connect to maxscale API

### ISSUE THREAD

**Issue by n7qnm** [mariadb-operator/mariadb-operator#463]
Still learning mariadb-operator and kubernetes - ran kubectl apply -f mariadb_replication_full.yaml 

3 mariadb-repl pods running, and one mariadb-repl-maxscale pod

I can connect to the databases using the IPs for replk-primary and secondary, but I can't connect to the IP for repl-maxscale

When I try to browse to the ip for repl-maxscale:8989, I get the welcome to MaxScale page; but no password seems to work.

What am I missing?

**Comment by mmontes11** [comment]
Hey @n7qnm ! Thanks for reporting.

Is the `MaxScale` resource in ready state?
```bash
kubectl get maxscale maxscale-repl
NAME              READY   STATUS    PRIMARY SERVER     AGE
maxscale-repl   True    Running   mariadb-repl-2   4h9m
```

If it is, which credentials are you using? You should be able to access with the credentials available in `spec.auth` 
```yaml
apiVersion: k8s.mariadb.com/v1alpha1
kind: MaxScale
metadata:
  name: maxscale-repl
spec:
  ....
  auth:
    adminPasswordSecretKeyRef:
      key: password
      name: maxscale-repl-admin
    adminUsername: mariadb-operator
```

For your example, it should work with `mariadb-operator` as user and the following command to obtain the password:

```bash
kubectl get secret maxscale-repl-admin -o jsonpath="{.data.password}" | base64 -d
```
