### ISSUE TITLE
[Bug] MaxScale startup failing

### ISSUE THREAD

**Issue by cloudnull** [mariadb-operator/mariadb-operator#493]
When deploying maxscale with galera I'm running into an issue where the maxscale pods are failing to start. Oddly, a fresh deployment of both galera and maxscale seems to work fine. However, if I deploy maxscale alongside an existing galera environment, which didn't have maxscale already, the deployment fails with the following error when the maxscale pods start up. Nothing bad happens to the galera cluster itself, everything remains operational; however, maxscale simply never goes online.

### Logs from maxscale pod

``` logs
2024-03-23 18:26:07   notice : MaxScale started with 64 worker threads.
2024-03-23 18:26:36   warning: Authentication failed for '', no password. Request: GET /
2024-03-23 18:26:36   warning: Authentication failed for '', no password. Request: GET /
```

The pods then go into a crashloop and not recover. In trying to debug, I found the grants and users and validates that the users were functional. 

### Reproducing the error

I am able to reproduce this error by deleting the maxscale deployment via kubectl and then redeploying the same manifest. In doing that operation it seems I'm not able to get back to a functional state.

**Documentation**
- [ x] I acknowledge that I have read the relevant [documentation](https://github.com/mariadb-operator/mariadb-operator/tree/main/docs).

Cluster manifests can be seen here
- galera: https://github.com/rackerlabs/genestack/blob/main/kustomize/mariadb-cluster/base/mariadb-galera.yaml
- maxscale: https://github.com/rackerlabs/genestack/blob/main/kustomize/mariadb-cluster/base/mariadb-maxscale.yaml

**Comment by cloudnull** [comment]
I was able to overcome the startup issue by using a TCP liveness probe instaead of an HTTP probe.

``` yaml
  livenessProbe:
    failureThreshold: 3
    tcpSocket:
      port: 8989
    initialDelaySeconds: 20
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 5

  readinessProbe:
    failureThreshold: 3
    tcpSocket:
      port: 8989
    initialDelaySeconds: 20
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 5
```

While this worked, I think it's less than ideal. Sadly once the service started up I ran into a different issue where the `/var/lib/maxscale/maxscale-config.json` file was being populated with what seemed like an old password, or at least a wrong one. I was able to resolve this by taking the generated secrete from the `maxscale` and manually editing the JSON file to use the updated value. After making this change, the service started and began communicating with the backend normally.

I'm not sure where the password value is being pulled from, when I redeploy, but I can confirm this issue is reproducible with a fairly simply. Should I be manually generating the secrets/users/grants?

**Comment by cloudnull** [comment]
well my joy was short lived, the file `/var/lib/maxscale/maxscale-config.json` was resynced and the bad value was put back into place :'(

**Comment by cloudnull** [comment]
To work around the password issues I once again deleted the maxscale deployment. I then created a new password for maxscale that didn't have the `ownerReferences`

``` yaml
apiVersion: v1
data:
  password: SuperSecrete
kind: Secret
metadata:
  name: maxscale
```

With the secrete in place the issue is now "fixed," however, I had to use the password that was generated when I first started the maxscale deployment, which I took out of the `maxscale-config.json` file; I have no idea where it's getting that value from.
