### ISSUE TITLE
[Bug] MariaDB not found with kind Backup

### ISSUE THREAD

**Issue by wirehack7** [mariadb-operator/mariadb-operator#513]
**Documentation**
- [x] I acknowledge that I have read the relevant [documentation](https://github.com/mariadb-operator/mariadb-operator/tree/main/docs).

**Describe the bug**
I'm currently trying to adopt the provided `backup.yaml` from `examples`. Current configuration for `Backup`:

```yaml
apiVersion: k8s.mariadb.com/v1alpha1
kind: Backup
metadata:
  name: backup
  namespace: mariadb
spec:
  logLevel: debug
  mariaDbRef:
    name: mariadb
    namespace: mariadb
    waitForIt: true
  serviceAccountName: backup
  storage:
    persistentVolumeClaim:
      resources:
        requests:
          storage: 100Mi
      accessModes:
        - ReadWriteOnce
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 512Mi
status:
  conditions:
    - lastTransitionTime: '2024-03-26T14:43:17Z'
      message: MariaDB not found
      reason: Failed
      status: 'False'
      type: Complete
```
Deployment is realized via ArgoCD. In operator I get this error:

```
{"level":"error","ts":1711459112.37436,"msg":"Reconciler error","controller":"backup","controllerGroup":"[k8s.mariadb.com](http://k8s.mariadb.com/)","controllerKind":"Backup","Backup":{"name":"backup","namespace":"mariadb"},"namespace":"mariadb","name":"backup","reconcileID":"29c8f53a-23c7-4cd9-b669-3a99913ff44b","error":"error getting MariaDB: 1 error occurred:\n\t* [MariaDB.k8s.mariadb.com](http://mariadb.k8s.mariadb.com/) \"mariadb\" not found\n\n","stacktrace":"[sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.2/pkg/internal/controller/controller.go:329\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.2/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.2/pkg/internal/controller/controller.go:227](http://sigs.k8s.io/controller-runtime/pkg/internal/controller.%28*Controller%29.reconcileHandler%5Cn%5Ct/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.2/pkg/internal/controller/controller.go:329%5Cnsigs.k8s.io/controller-runtime/pkg/internal/controller.%28*Controller%29.processNextWorkItem%5Cn%5Ct/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.2/pkg/internal/controller/controller.go:266%5Cnsigs.k8s.io/controller-runtime/pkg/internal/controller.%28*Controller%29.Start.func2.2%5Cn%5Ct/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.2/pkg/internal/controller/controller.go:227)"}
```

The ref for MariaDB is existend as I deploy databases with this ref:

```yaml
spec:
  characterSet: utf8mb4
  collate: utf8mb4_unicode_ci
  mariaDbRef:
    name: mariadb
    namespace: mariadb
    waitForIt: true
status:
  conditions:
    - lastTransitionTime: '2024-03-08T13:59:40Z'
      message: Created
      reason: Created
      status: 'True'
      type: Ready
 ```

When I simply run the examples inside minikube it works. What I also don't get is: from where comes the backup ServiceAccount? I don't see the creation inside the example manifests. And from where are the secrets coming for the root password?
I see in examples the secret `mariadb`, but where is it referenced inside `backup.yaml`?
In my deployment is no `mariadb` secret as it got renamed.

**Expected behaviour**
MariaDB is being found by Backup

**Steps to reproduce the bug**
1. Deploy mariadb-operator
2. Don't deploy secret `mariadb`, deploy it with other name
3. Deploy databases
4. Deploy backup manifest like in examples

**Environment details**:
Kubernetes version: 1.27+
Kubernetes distribution: EKS
mariadb-operator version: v0.0.27
Install method: helm
Install flavor: custom -> ArgoCD
