### ISSUE TITLE
[Bug] "no valid backup files were found" on BackBlaze storage

### ISSUE THREAD

**Issue by Danielss89** [mariadb-operator/mariadb-operator#515]
**Documentation**
- [x] I acknowledge that I have read the relevant [documentation](https://github.com/mariadb-operator/mariadb-operator/tree/main/docs).

**Describe the bug**
I am trying to set up a new mariadb instance from a backup, like the example from the documentation. 
```
apiVersion: mariadb.mmontes.io/v1alpha1
kind: MariaDB
metadata:
  name: uk-merge-test
spec:
  username: test
  database: test

  image: mariadb:11.2
  imagePullPolicy: IfNotPresent

  volumeClaimTemplate:
    storageClassName: db-europe-longhorn-sc
    resources:
      requests:
        storage: 20Gi
    accessModes:
      - ReadWriteOnce

  service:
    type: ClusterIP

  nodeSelector:
    region: europe
    type: db

  bootstrapFrom:
    s3:
      bucket: xxx
      endpoint: s3.eu-central-003.backblazeb2.com
      region: eu-west-1
      prefix: yyy/
      accessKeyIdSecretKeyRef:
        name: mariadb-backblaze
        key: AWS_ACCESS_KEY_ID
      secretAccessKeySecretKeyRef:
        name: mariadb-backblaze
        key: AWS_SECRET_ACCESS_KEY
      tls:
        enabled: true
        caSecretKeyRef:
          name: backblaze-ca
          key: ca
    targetRecoveryTime: 2024-03-26T03:30:25Z
```
As seen in screenshot, backup files does exist, with exact timestamp even.
The S3 part from config is copied directly from the backup yaml file, which works, so that should also work fine.

**Expected behaviour**
Instance would start up and backup would be imported.

**Debug information**
- Related object events:
```bash
mariadb-operator {"level":"info","ts":1711455940.049458,"msg":"starting restore"}    
mariadb-operator {"level":"info","ts":1711455940.0496657,"msg":"configuring S3 backup storage"}     
mariadb-operator {"level":"info","ts":1711455940.0636103,"msg":"obtained target time","time":"2024-03-26 03:30:25 +0000 UTC"} 
mariadb-operator {"level":"error","ts":1711455940.2660177,"msg":"error reading getting target backup","error":"no valid backup files were found","stacktrace":"github.com/mariadb-operator/mariadb-operator/cmd/backup.glob..func2\n\t/app/cmd/backup/restore.go:54\ngithub.com/spf13/cobra.(*Command).execute\n\t/go/pkg/mod/github.com /spf13/cobra@v1.7.0/command.go:944\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068\ngithub.com/spf13/cobra. (*Command).Execute\n\t/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992\nmain.main\n\t/app/cmd/controller/main.go:361\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:267"}  
```
