### ISSUE TITLE
[Bug] Host 'localhost' is not allowed to connect to this server

### ISSUE THREAD

**Issue by henrywhitaker3** [mariadb-operator/mariadb-operator#525]
**Documentation**
- [x] I acknowledge that I have read the relevant [documentation](https://github.com/mariadb-operator/mariadb-operator/tree/main/docs).

**Describe the bug**

After restoring a galera cluster from the backup (I tried both bootstrapping from backup, and creating a Restore resource), 1 of the galera nodes fails to run. It restarts, successfully SSTs, then fails as the agent cannot connect to mariadb:

```
{"level":"error","ts":1711728623.5119305,"logger":"handler.probe.liveness","msg":"error getting SQL client","error":"Error 1130: Host 'localhost' is not allowed to connect to this MariaDB server","stacktrace":"github.com/mariadb-operator/mariadb-operator/pkg/galera/agent/handler.(*Probe).Liveness\n\t/app/pkg/galera/agent/handler/probe.go:67\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2136\ngithub.com/go-chi/chi/v5.(*Mux).routeHTTP\n\t/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.8/mux.go:444\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2136\ngithub.com/go-chi/chi/v5/middleware.Recoverer.func1\n\t/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.8/middleware/recoverer.go:43\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2136\ngithub.com/go-chi/chi/v5/middleware.(*Compressor).Handler-fm.(*Compressor).Handler.func1\n\t/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.8/middleware/compress.go:213\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2136\ngithub.com/go-chi/chi/v5.(*Mux).ServeHTTP\n\t/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.8/mux.go:90\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2938\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:2009"}
```

**Expected behaviour**

**Steps to reproduce the bug**

1. Create a galera cluster
2. Run a backup
3. Restore from the backup

**Environment details**:
- Kubernetes version: 1.29.3
- Kubernetes distribution: k3s
- mariadb-operator version: v0.0.27
- Install method: helm/argocd

**Additional context**

Mariadb resource:

```
apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  port: 3306

  replicas: 3

  galera:
    enabled: true
    config:
      reuseStorageVolume: true
    recovery:
      enabled: true

  podSecurityContext:
    runAsUser: 0

  rootPasswordSecretKeyRef:
    name: mariadb-secrets
    key: root-password

  storage:
    volumeClaimTemplate:
      storageClassName: longhorn-no-backups
      resources:
        requests:
          storage: 10Gi
      accessModes:
        - ReadWriteOnce

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 512Mi

  metrics:
    enabled: true

  service:
    type: LoadBalancer
    loadBalancerIP: 10.0.0.28
```
