### ISSUE TITLE
[Bug] Avoid passing `--all-databases` flag in `Backup` if `--databases` is set by the user

### ISSUE THREAD

**Issue by mmontes11** [mariadb-operator/mariadb-operator#551]
**Describe the bug**
When the user specifies the `--databases` flag in `Backup`, it clashes with the default `--all-databases` flag:
```yaml
apiVersion: k8s.mariadb.com/v1alpha1
kind: Backup
metadata:
  name: backup
  namespace: default
spec:
  args:
  - --databases sbtest
  - --skip-add-locks
```

Causing the following error:
```bash
mariadb 💾 Taking backup: /backup/backup.2024-04-10T09:12:37Z.sql
mariadb Usage: mariadb-dump [OPTIONS] database [tables]
mariadb OR     mariadb-dump [OPTIONS] --databases DB1 [DB2 DB3...]
mariadb OR     mariadb-dump [OPTIONS] --all-databases
mariadb OR     mariadb-dump [OPTIONS] --system=[SYSTEMOPTIONS]]
mariadb For more options, use mariadb-dump --help
``` 

**Expected behaviour**
Omit the `--all-databases` default flag if the user provides `--databases` 

**Steps to reproduce the bug**

1. Create a `Backup` passing `--databases foo`  as args
2. Wait for the `Job` to be reconciled
3. Check the `Pod` logs.
