### ISSUE TITLE
[Bug] Prefixed s3 backups do not get cleaned up

### ISSUE THREAD

**Issue by markus-brln** [mariadb-operator/mariadb-operator#564]
**Documentation**
- [x] I acknowledge that I have read the relevant [documentation](https://github.com/mariadb-operator/mariadb-operator/tree/main/docs).

**Describe the bug**

Hi, we're encountering the issue that when setting a [prefix in the s3 storage backup config](https://github.com/mariadb-operator/mariadb-operator/blob/main/docs/API_REFERENCE.md#s3), the backups do get created properly in a sub-path in the s3 bucket, but the cleanup according to the `maxRetention` is not working.

**Expected behaviour**

Cleanup according to the `maxRetention`, resulting in deletion of older backups. (As soon as I remove `prefix`, it works fine.)

**Steps to reproduce the bug**

1. Run mariadb-operator on your cluster(we're running Helm chart version 0.25.0 of the operator)
2. Create a `MariaDB` instance
3. Create a `Backup` using [s3 as storage](https://github.com/mariadb-operator/mariadb-operator/blob/main/docs/API_REFERENCE.md#s3)
4. Set `maxRetention: 1h` so you can see the cleanup not working as soon as possible (I think that's the minimum)

**Debug information**

Logs of mariadb-operator container in the backup pod (see "no old backups were found"):
```json
{"level":"info","ts":1713342902.1655796,"msg":"starting backup"}
{"level":"info","ts":1713342902.1657372,"msg":"configuring S3 backup storage"}
{"level":"info","ts":1713342902.165813,"msg":"reading target file","path":"/backup/0-backup-target.txt"}
{"level":"info","ts":1713342902.16585,"msg":"obtained target backup","file":"backup.2024-04-17T08:35:00Z.sql"}
{"level":"info","ts":1713342902.1658537,"msg":"pushing target backup","file":"backup.2024-04-17T08:35:00Z.sql"}
{"level":"info","ts":1713342902.2018082,"msg":"cleaning up old backups"}
{"level":"info","ts":1713342902.2018452,"msg":"no old backups were found"}
```

I looked a bit through the code (this my the first time ever looking at Go...) and I think the problem might be somewhere close to this [line](https://github.com/mariadb-operator/mariadb-operator/blob/a4ab36f925bb84c33f0325306aadfadbe5932eb3/pkg/backup/storage.go#L139). I find it weird that it's passing a `minio.ListObjectsOptions` even though the [implementation of ListObjects](https://github.com/minio/minio-go/blob/18e8073b0226383a551afd03cbd3b8c24e55d0b8/core.go#L48) only wants a prefix there. Maybe I'm completely wrong, but maybe it helps to get started with investigating :)

**Environment details**:
- Kubernetes version: 1.27
- Kubernetes distribution: microk8s
- mariadb-operator version: 0.25.0
- Install method: helm
- Install flavor: not sure [minimal, recommended, or custom]

**Additional context**

<details><summary>Backup CRD</summary>

```yaml
apiVersion: mariadb.mmontes.io/v1alpha1
kind: Backup
metadata:
  name: mariadb-backup
  namespace: my-namespace
spec:
  args:
    - '--single-transaction'
    - '--add-drop-database'
    - '--all-databases'
  backoffLimit: 5
  logLevel: info
  mariaDbRef:
    name: mariadb
    waitForIt: true
  maxRetention: 1h
  resources:
    limits:
      cpu: 2
      memory: 2Gi
    requests:
      cpu: 100m
      memory: 100Mi
  restartPolicy: OnFailure
  schedule:
    cron: '* * * * *'
    suspend: false
  storage:
    s3:
      accessKeyIdSecretKeyRef:
        key: my-backups-access-key
        name: my-backups-s3-credentials
      bucket: my-backups
      endpoint: my.s3.endpoint.com
      prefix: my-prefix/
      region: ''
      secretAccessKeySecretKeyRef:
        key: my-backups-secret-key
        name: backups-s3-credentials
```

</details>
