### ISSUE TITLE
[Bug] rootPasswordSecretKeyRef race condition (provided Secret / Generated by operator)

### ISSUE THREAD

**Issue by poblin-orange** [mariadb-operator/mariadb-operator#587]
**Documentation**
- [x] I acknowledge that I have read the relevant [documentation](https://github.com/mariadb-operator/mariadb-operator/tree/main/docs).

**Describe the bug**

the spec.rootPasswordSecretKeyRef has two roles:
- use to get the initial root password
- use as Secret name which is generated by the operator, if missing

When the MariaDb CR is used in same Kustomization as a password generator (ESO External Secret Operator, which generates a Secret), the result is not predictable. Sometimes ESO generates the Secret before MariaDb operator, sometime ESO is faster.

**Expected behaviour**

**Steps to reproduce the bug**

1. ...
2. ...
3. ...

**Debug information**
- Related object events:
```bash
kubectl get events --field-selector involvedObject.name=<mariadb-resource-name>
kubectl get events --field-selector involvedObject.name=<backup-resource-name>
kubectl get events --field-selector involvedObject.name=<restore-resource-name>
```
- `mariadb-operator` logs. Set the `--log-level` to `debug` if needed.

**Environment details**:
- Kubernetes version: [Version number]
- Kubernetes distribution: [Vanilla, EKS, GKE, AKS, Rancher, OpenShift, k3s, KIND...]
- mariadb-operator version: [Version number]
- Install method: [helm, OLM, or static manifests]
- Install flavor: [minimal, recommended, or custom]

**Additional context**

**Comment by mmontes11** [comment]
Hey @poblin-orange ! Thanks for reporting.

@K-MeLeOn reported a very similar issue a while ago:
- https://github.com/mariadb-operator/mariadb-operator/issues/340

It is the same root cause: If the operator doesn't find the `Secret` related to the root password by the time it reconciles, it creates one. See the `Secret` reconciler logic for further detail
https://github.com/mariadb-operator/mariadb-operator/blob/7fe204fb7baa914fa5e2c2bdafd922b89e1c5b7b/pkg/controller/secret/controller.go#L46

If the `Secret` is created asynchronously by an external operator (ESO or SealedSecrets), it can happen that it is not created by the time `mariadb-operator` kicks in.

We could introduce a new `generate` field in the `Secret` references to indicate that we don't want the `mariadb-operator` to generate a random `Secret`, instead, we will rely on an external controller:

```yaml
apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb-galera
spec:
  rootPasswordSecretKeyRef:
    name: mariadb
    key: root-password
    generate: false
```

All the `Secret` references fields are optional, if not provided they will default to:

```yaml
apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb-galera
spec:
  rootPasswordSecretKeyRef:
    name: mariadb
    key: root-password
    generate: true
```

In order to maintain backwards compatibility, if the user provides only the `Secret` reference:

```yaml
apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb-galera
spec:
  rootPasswordSecretKeyRef:
    name: mariadb
    key: root-password
```

the new `generate` field will also be defaulted to `true`:

```yaml
apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb-galera
spec:
  rootPasswordSecretKeyRef:
    name: mariadb
    key: root-password
    generate: true
```

@poblin-orange what do you think?
@K-MeLeOn your input here will be very much appreciated.

**Comment by mmontes11** [comment]
Just to add some context. Integrating with [external-secrets-operator ](https://github.com/external-secrets/external-secrets)and [sealed-secrets ](https://github.com/bitnami-labs/sealed-secrets) is crucial, as it enables potential GitOps uses cases:
- Configure a `MariaDB` with a root password provided as a `SealedSecret` and reconciled as a `Secret` by sealed-secrets
- Configure a `MariaDB` with a root password provided as a `ExternalSecret` which has a reference to a Vault key and it is reconciled into a `Secret` by ESO

**Comment by poblin-orange** [comment]
@mmontes11 yes, a flag to configure would be perfect for our use cases, letting Gitops config be explicit about Secret ownership !

**Comment by K-MeLeOn** [comment]
@poblin-orange If it can help you, if you're using ArgoCD you can configure the deployment like that :

```yaml
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: [...]
  namespace: [...]
  annotations:
    # Before MariaDb to avoid password generation
    argocd.argoproj.io/sync-wave: "-10"
spec:
```
