### ISSUE TITLE
[Bug]  error: unknown field "spec.primaryService.annotations"

### ISSUE THREAD

**Issue by blodone** [mariadb-operator/mariadb-operator#589]
**Describe the bug**

When setting annotations in service or primary / secondary Service this pops up:
```
  primaryService:
    type: LoadBalancer
    annotations:
      external-dns.alpha.kubernetes.io/hostname: mariadb-001-pri.ns.bla.local

-> strict decoding error: unknown field "spec.primaryService.annotations"

```
when using metadata like this:
```
  primaryService:
    type: LoadBalancer
    metadata:
      annotations:
        external-dns.alpha.kubernetes.io/hostname: mariadb-001-pri.ns.bla.local
```
it is applied but won't get applied to the service

**Environment details**:
- Kubernetes version: 1.25
- Kubernetes distribution: Vanilla
- mariadb-operator version: 0.0.27
- Install method: helm to static
- Install flavor: helm template?
