### ISSUE TITLE
Support for S3 storage in `BackupMariaDB` and `RestoreMariaDB`

### ISSUE THREAD

**Issue by mmontes11** [mariadb-operator/mariadb-operator#6]
Be able to take and restore backups using AWS S3 as storage.

**Comment by ox1depl** [comment]
its will support only AWS or any storage with S3 API, like azure blob, monio and others ?

**Comment by mmontes11** [comment]
Hey @ox1depl !

The intention is supporting any S3 compatible API by levaraging this library:
- https://github.com/minio/minio-go

Let me know if you have other suggestions.

**Comment by mmontes11** [comment]
At the moment, S3 backups can be achieved by installing the following CSI driver:
- https://github.com/yandex-cloud/k8s-csi-s3

and specify its `storageClassName` in the `Backup`/`Restore` resources:
```yaml
apiVersion: mariadb.mmontes.io/v1alpha1
kind: Backup
metadata:
  name: backup
spec:
  mariaDbRef:
    name: mariadb
  storage:
    persistentVolumeClaim:
      storageClassName: csi-s3
      resources:
        requests:
          storage: 100Mi
      accessModes:
        - ReadWriteOnce
  args:
    - --single-transaction
    - --all-databases
 ```
 The S3 support is a priority for the next releases though
