### ISSUE TITLE
[Question] Can I change image repository of a object backup which use mariadb-operator to deploy its pod

### ISSUE THREAD

**Issue by se-baj** [mariadb-operator/mariadb-operator#623]
Hello,

I try to instantiate a backup object with mariadb-operator. Backup and its job are created.
when creating pod (backup-xxxx), image can not be pulled and it's normal since I am using a private repository.

Message is: "__Back-off pulling image "ghcr.io/mariadb-operator/mariadb-operator:v0.0.27__"

I would like to point to my private repository for mariadb-operator:v0.0.27 but cannot find where I could configure that.
I had checked CRD and cannot find something which could allow me to configure that, or maybe I missed something.
Question is, is it possible to change image repository for "mariadb-operator/backup" object ?
Thanks
Regards
sebastien

**Comment by bswethareddy** [comment]
Have been facing same issue

**Comment by mmontes11** [comment]
Hey there ! Thanks for bringing this up.

In order to achieve this, you will need to provide the `MARIADB_OPERATOR_IMAGE`  env variable to your operator Deployment. You can achieve this by setting the `extraEnv` value in the helm chart.

You may also want to set the `imagePullSecrets` of the `Backup` resource, see more details here:
https://github.com/mariadb-operator/mariadb-operator/blob/main/docs/REGISTRY.md#backup-restore-and-sqljob

**Comment by se-baj** [comment]
Thanks for your answer, i will give it a try and let you know.
Thanks
Regards
sebastien

**Comment by siwyroot** [comment]
Hello, how I can set image for backup when using operator from operator hub on OpenShift? It looks like in there it's hardcoded.

**Comment by siwyroot** [comment]
Right now image is set to `docker-registry3.mariadb.com/mariadb-operator/mariadb-operator:v0.0.29` which is set via mariadb-operator-env, any way to override this? For other objects I can just set image in definition

**Comment by melledouwsma** [comment]
The instance from the OperatorHub on OpenShift is [mariadb-operator-helm](https://github.com/mariadb-operator/mariadb-operator-helm). You can configure the `MariadbOperator` resource with some custom image locations with something like this, for example:

```yaml
apiVersion: helm.mariadb.mmontes.io/v1alpha1
kind: MariadbOperator
metadata:
  name: mariadb-operator
  namespace: mariadb-operator
spec:
  # [...some other configuration...]
  image:
    pullPolicy: IfNotPresent
    repository: registry.corp.internal/mariadb-operator/mariadb-operator
    tag: ''
```

Another approach on disconnected OpenShift installations would be creating a `ImageContentSourcePolicy` mapping the image to a local repository. You can read more about that on [Configuring image registry repository mirroring](https://docs.openshift.com/container-platform/4.15/openshift_images/image-configuration.html#images-configuration-registry-mirror-configuring_image-configuration) in the OpenShift docs.

**Comment by siwyroot** [comment]
@melledouwsma Hi, I already have setup MariadbOperator but it's ignoring images

**Comment by melledouwsma** [comment]
> Hi, I already have setup MariadbOperator but it's ignoring images

Alright, thanks. I've setup a instance in my cluster and I'm seeing the same behaviour.

> In order to achieve this, you will need to provide the MARIADB_OPERATOR_IMAGE env variable to your operator Deployment. You can achieve this by setting the extraEnv value in the helm chart.

It seems the `spec.image` only controls the operator itself. To override the image in the `Backup` job, we'll need to provide that `MARIADB_OPERATOR_IMAGE` variable. We can supply that in the `MariadbOperator` resource like this:

```yaml
apiVersion: helm.mariadb.mmontes.io/v1alpha1
kind: MariadbOperator
metadata:
  name: mariadb-operator
  namespace: mariadb-operator
spec:
  # [...some other configuration...]
  extraEnv:
    - name: MARIADB_OPERATOR_IMAGE
      value: registry.corp.internal/mariadb-operator/mariadb-operator
```

After this, the `Backup` job in my test is using the custom image:

```bash
oc get pod -n mariadb-test backup-nh8cw-fdmj2 -o json | jq .spec.containers[].image
"registry.corp.internal/mariadb-operator/mariadb-operator"
```
