### ISSUE TITLE
[Bug] Resource Limits not correct set

### ISSUE THREAD

**Issue by hypery2k** [mariadb-operator/mariadb-operator#639]
**Documentation**
- [x] I acknowledge that I have read the relevant [documentation](https://github.com/mariadb-operator/mariadb-operator/tree/main/docs).

**Describe the bug**

I tried to use the operator together with limits and getting this error:
```
create Pod mariadb-1 in StatefulSet mariadb failed error: pods "mariadb-1" is forbidden: maximum ephemeral-storage usage per Container is 2Gi, but limit is 3000Mi
```

This is my config:
```
apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
spec:
  rootPasswordSecretKeyRef:
    name: database
    key: mariaDbRootPassword
  affinity:
    enableAntiAffinity: true
  connection:
    secretName: mariadb-repl-conn
    secretTemplate:
      key: dsn
  database: mariadb
  galera:
    enabled: false
  metrics:
    enabled: true
  myCnf: |
    [mariadb]
    bind-address=*
    default_storage_engine=InnoDB
    binlog_format=row
    innodb_autoinc_lock_mode=2
    max_allowed_packet=256M
  podDisruptionBudget:
    maxUnavailable: 33%
  primaryConnection:
    secretName: mariadb-repl-conn-primary
    secretTemplate:
      key: dsn
  primaryService:
    type: ClusterIP
  replicas: 3
  replication:
    enabled: true
  secondaryConnection:
    secretName: mariadb-repl-conn-secondary
    secretTemplate:
      key: dsn
  secondaryService:
    type: ClusterIP
  service:
    type: ClusterIP
  updateStrategy:
    type: RollingUpdate
  username: mariadb
  resources:
    requests:
      cpu: 300m
      memory: 256Mi
      ephemeral-storage: 100Mi
    limits:
      cpu: 1
      memory: 1Gi
      ephemeral-storage: 300Mi

```

**Expected behaviour**
Limits for ephemeral storage of 300Mi is used

**Steps to reproduce the bug**

1. Apply Limit Range 
```
  kind: LimitRange
  spec:
    limits:
    - max:
        cpu: "4"
        ephemeral-storage: 2Gi
        memory: 4Gi
      type: Pod
    - default:
        cpu: 500m
        ephemeral-storage: 1Gi
        memory: 1Gi
      defaultRequest:
        cpu: 200m
        ephemeral-storage: 300Mi
        memory: 256Mi
      max:
        cpu: "2"
        ephemeral-storage: 2Gi
        memory: 2Gi
      type: Container
    - max:
        storage: 10Gi
      type: PersistentVolumeClaim
```
2. Try to create a MySQL instance

**Debug information**
see above...

**Environment details**:
- Kubernetes version: 1.29.5
- Kubernetes distribution: k3s
- mariadb-operator version: 0.0.28
- Install method: [OLM
- Install flavor: custom with HA and 3 replica

**Additional context**
Any ideas where the 3000Mi came from?
