### ISSUE TITLE
[Feature] Backup encryption

### ISSUE THREAD

**Issue by mariadb-pieterhumphrey** [mariadb-operator/mariadb-operator#652]
**Is your feature request related to a problem? Please describe.**

ability to store backups with industry standard encryption algorithms.

AES 256, AES 128, AES 192, and Triple DES + RSA; a public key for encryption and a private key for decryption, which can be useful for sharing data over an insecure network.

**Comment by bognerf** [comment]
+1

**Comment by businessbean** [comment]
What about using `mariadb-dump ... | kopia snapshot create` for https://github.com/mariadb-operator/mariadb-operator/blob/c251ccd9894f8de08f2a361953c96da261c5d34d/pkg/command/backup.go#L135 to let `mariadb-dump` create consistent backups and than pipe them to `kopia` to be able to use all the [encryption, compression, deduplication, replication, retention etc. features](https://kopia.io/docs/features/) they are providing? With an additional Kopia server pod a WebUI to browse existing backups and being able to download them for other use cases would be possible.

**Comment by vixns** [comment]
@mmontes11 I'll may work on this feature, any advice ?
I think about implementing this feature using https://github.com/C2SP/C2SP/blob/main/age.md

**Comment by mmontes11** [comment]
Hey there @vixns !  Sure, that would be very much appreciated!

> I think about implementing this feature using https://github.com/C2SP/C2SP/blob/main/age.md

Unless really required (like with `bzip2`), I would suggest we start by supporting `AES 256` sticking to the standard library:
https://pkg.go.dev/crypto/aes@go1.23.1

It seems to be the most used algorithm for backup encryption. Once implemented we can consider supporting other asymetric algoritms like RSA or 3DES + RSA. The stdlib supports all of them in this case:
https://pkg.go.dev/crypto

We will need new fields in both `Backup` and `Restore` resources:

## Backup

The user will only need to enable encryption:

```yaml
apiVersion: k8s.mariadb.com/v1alpha1
kind: Backup
metadata:
  name: backup
spec:
   encryption:
      enabled: true
``` 

which will be defaulted by the operator to:

```yaml
apiVersion: k8s.mariadb.com/v1alpha1
kind: Backup
metadata:
  name: backup
spec:
   encryption:
      enabled: true
      algorithm: aes256
      generateKey: true
      privateKeySecretKeyRef: # this applies to symetric and asymetric algorithms
         name: backup-key
         key: private-key
      publicKeySecretKeyRef: # this only applies to symetric and asymetric algorithms (ignore when implementing aes256)
         name: backup-key
         key: public-key
```
As you probably now from your [previous contribution](https://github.com/mariadb-operator/mariadb-operator/pull/836) 🙏🏻 , the `Backup` resource gets defaulted here:
https://github.com/mariadb-operator/mariadb-operator/blob/2fc59600853941590b8e457b76d4c4c152d2aae5/internal/controller/backup_controller.go#L98

Additionaly, for the encryption, we will need to generate a random encryption key if the `generateKey=true`, which will be the default behaviour. This will need to take into account the `algorithm`, as we will need to either generate a symetric or an asymetric key.

The user can opt-out from this by setting `generateKey=false`, but in this case the `Secret` references `privateKeySecretKeyRef` and `publicKeySecretKeyRef` must exist.

We often generate random passwords referred by `Secrets`. Please take a look at this:
https://github.com/mariadb-operator/mariadb-operator/blob/2fc59600853941590b8e457b76d4c4c152d2aae5/internal/controller/mariadb_controller.go#L251

And we also have a `refresolver` package to deal with references:
https://github.com/mariadb-operator/mariadb-operator/blob/2fc59600853941590b8e457b76d4c4c152d2aae5/pkg/refresolver/refresolver.go#L111

## Restore

Unlike with the compression, we need a new field here to provide a reference to the `Secret` containing the keys to decrypt:

```yaml
apiVersion: k8s.mariadb.com/v1alpha1
kind: Restore
metadata:
  name: restore
spec:
   decryption:
      enabled: true
      algorithm: aes256
      privateKeySecretKeyRef: # this applies to symetric and asymetric algoritms
         name: backup-key
         key: private-key
      publicKeySecretKeyRef: # this only applies to symetric and asymetric algoritms (ignore when implementing aes256)
         name: backup-key
         key: public-key
```
and the same for the `MariaDB` `bootstrapFrom` field, which is used to programatically create a `Restore` resource from the opreator:

```yaml
apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb-galera-from-s3
spec:
  bootstrapFrom:
    s3:
      ...
    decryption:
      enabled: true
      algorithm: aes256
      privateKeySecretKeyRef: # this applies to symetric and asymetric algorithms
         name: backup-key
         key: private-key
      publicKeySecretKeyRef: # this only applies to symetric and asymetric algorithms (ignore when implementing aes256)
         name: backup-key
         key: public-key
``` 

The good news is that both `Restore` and `MariaDB` reuse the same model, so we will only need to do the changes in `RestoreSource`:
https://github.com/mariadb-operator/mariadb-operator/blob/2fc59600853941590b8e457b76d4c4c152d2aae5/api/v1alpha1/base_types.go#L592


It is important to note that, the new `Restore` fields don't have defaults, if the user wants to bootstrap from an encrypted backup, a `decryption` object will need to be provided.

Let me know what you think @vixns !

**Comment by vixns** [comment]
Thanks for this detailed proposal @mmontes11 

Using AES on big files requires implementations choices as you can read at https://stackoverflow.com/questions/49546567/how-do-you-encrypt-large-files-byte-streams-in-go

Asymmetric encryption is slow, my current way to encrypt backups is to use a generated symmetric key to encrypt the data, then encrypt this symmetric key using an asymmetric key pair, and store the encrypted symmetric key file alongside the encrypted backup.

I was using GNUPG for this, because one of my concern is to be able to decrypt with multiple key pairs, one from the platform, another from the owner of the data, a third secured in a vault, ...

I can rotate/delete/add any key pair, and still be able to decrypt previous backups with the remaining ones. The new key pairs cannot decrypt previous backups, the deleted ones cannot decrypt future backups. I like it, GPDR may like it.

AGE seems to be a nice GPG successor, that's why I'm thinking about it to implement this method in this operator to encrypt/decrypt AES keys.

**Comment by mmontes11** [comment]
Hey there @vixns ! Thanks for your detailed input.

I totally see the point of combining Asymmetric encryption for securely distributing multiple keys + Symmetric encryption to efficiently encrypt large backup files. As you said, this have multiple benefits:
- Leverage the best of both Asymmetric and Symmetric encryption, the right tool for each job
- Multiple keys can decrypt the same backup, giving access to multiple stakeholders to the backup
- GPDR may like it

I also have a couple of questions regarding:
> encrypted symmetric key file alongside the encrypted backup.

- Would this mean that we need to create an extra file with the encrypted symmectric key?  Or is it embedded into the backup file itself?
- What if we have multiple asymmetric keys?  Would this mean we will need multiple key files with the symmetric key encrypted for each asymmetric key? 
- I think the multiple keys are managed by the payload defined [here](https://github.com/C2SP/C2SP/blob/main/age.md) right? If so, since [C2SP](https://github.com/C2SP/C2SP) is just a spec, we would need to either implement the spec ourselves or find a third party lib.

In general terms, although I see the value of key management i.e. support multiple asymmetric keys, I think we should go one step at a time, as this could result in a complex implementation and therefore also complex to maintain. So my suggestion here it to and treat the support multiple asymmetric keys as a different feature in a different issue. Would you mind opening an issue?

That said, I think we should start with plain symmetric encryption using `aes256`, `aes192`  and `aes128`, which is pretty much what other operators do, and from there, support multiple keys via asymmetric cryptography as a bonus point. 

For doing so, I would [follow this design](https://github.com/mariadb-operator/mariadb-operator/issues/652#issuecomment-2383225643), but I would omit the public key part, treating the private key as a symmetric key. We could also leverage the `GeneratedSecretKeyRef` construct to indicate that such key should be auto-generated by the operator:

https://github.com/mariadb-operator/mariadb-operator/blob/308338c61f9060fc79c7eb56163159a8d5dc1a5a/api/v1alpha1/base_types.go#L686

```yaml
apiVersion: k8s.mariadb.com/v1alpha1
kind: Backup
metadata:
  name: backup
spec:
   encryption:
      enabled: true
      algorithm: aes256
      privateKeySecretKeyRef:
         name: backup-key
         key: private-key
         generated: true
``` 
```yaml
apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb-galera-from-s3
spec:
  bootstrapFrom:
    s3:
      ...
    decryption:
      enabled: true
      algorithm: aes256
      privateKeySecretKeyRef: 
         name: backup-key
         key: private-key
``` 
Regarding AES implementation details:

> Using AES on big files requires implementations choices as you can read at https://stackoverflow.com/questions/49546567/how-do-you-encrypt-large-files-byte-streams-in-go

It sounds like the second option fits better our use case, having >2GB backup files will be a very usual scenario. What do you think?
