### ISSUE TITLE
[Bug] [0.29.0] GRANT - sql error

### ISSUE THREAD

**Issue by pasztorl** [mariadb-operator/mariadb-operator#679]
I've using the latest mariadb-operator and when I add a grant i got this error message:

`Error creating portal-user-all: 1 error occurred: * error granting privileges in MariaDB: 1 error occurred: * Error 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'ON *.* TO 'portal-user'@'%' WITH GRANT OPTION' at line 1`

crd:
```
apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: portal-user-all
  namespace: test-db
spec:
  database: '*'
  grantOption: true
  host: '%'
  mariaDbRef:
    name: testdb
    waitForIt: false
  privileges:
    - SELECT
    - INSERT
    - UPDATE
    - DELETE
    - CREATE
    - DROP
    - RELOAD
    - SHUTDOWN
    - PROCESS
    - FILE
    - REFERENCES
    - INDEX
    - ALTER
    - SHOW DATABASES
    - SUPER
    - CREATE TEMPORARY TABLES
    - LOCK TABLES
    - EXECUTE
    - REPLICATION SLAVE
    - REPLICATION CLIENT
    - CREATE VIEW
    - SHOW VIEW
    - CREATE ROUTINE
    - ALTER ROUTINE
    - CREATE USER
    - EVENT
    - TRIGGER ON
  requeueInterval: 30s
  retryInterval: 5s
  table: '*'
  username: portal-user
```
