### ISSUE TITLE
[Bug] Helm repo change breaks umbrella charts

### ISSUE THREAD

**Issue by pschichtel** [mariadb-operator/mariadb-operator#680]
**Documentation**
- [x] I acknowledge that I have read the relevant [documentation](https://github.com/mariadb-operator/mariadb-operator/tree/main/docs).

**Describe the bug**

I deploy all my stuff with Argo CD using helm charts. All the helm charts are installed as part of an umbrella chart like this:

```yaml
apiVersion: v2
name: mariadb-operator
version: '1.0'

dependencies:
- name: mariadb-operator
  repository: https://helm.mariadb.com/mariadb-operator
  version: 0.28.*
```

This allows me to easily add additional resource and install several charts together. The change of the helm repo that happened together with the 0.29.0/0.0.29 release causes `helm dependency build` on this chart to fail:

```
$ helm dependency build
Error: error unpacking 0.28.1 in mariadb-operator: Chart.yaml file is missing
```

I think this happens, because the URLs in the index.yaml end with just the version. Even though the URLs redirect to URLs that end with .tgz, helm seems to use the filename of the original URL.
