### ISSUE TITLE
[Bug] Issues getting Quickstarted - Pod getting killed off, readiness probe failed

### ISSUE THREAD

**Issue by timatlee** [mariadb-operator/mariadb-operator#73]
**Describe the bug**
Quickstart process results in pods being launched that get killed off.  The pods events suggest that the service does not run:
```
Events:
  Type     Reason     Age                From               Message
  ----     ------     ----               ----               -------
  Normal   Scheduled  42s                default-scheduler  Successfully assigned mariadb/mariadb-0 to k3s-n3
  Warning  Unhealthy  22s (x3 over 32s)  kubelet            Liveness probe failed: ERROR 2002 (HY000): Can't connect to local server through socket '/run/mysqld/mysqld.sock' (2)
  Normal   Killing    22s                kubelet            Container mariadb failed liveness probe, will be restarted
  Warning  Unhealthy  2s (x8 over 32s)   kubelet            Readiness probe failed: ERROR 2002 (HY000): Can't connect to local server through socket '/run/mysqld/mysqld.sock' (2)
  Normal   Pulled     1s (x2 over 42s)   kubelet            Container image "mariadb:10.7.4" already present on machine
  Normal   Created    1s (x2 over 42s)   kubelet            Created container mariadb
  Normal   Started    1s (x2 over 42s)   kubelet            Started container mariadb
```

**Expected behaviour**
A working MariaDB should be created, in a running state.

**Steps to reproduce the bug**
cert-manager and prometheus are both installed in the cluster.

1. Install mariadb-operator from Helm chart. `helm install -n mariadb mariadb-operator mariadb-operator/mariadb-operator -f values.yaml`.

```yaml
nameOverride: mariadb

metrics:
  enabled: true

ha:
  enabled: false
```

2. Install the config manifests defined in the quickstart
```shell
kubectl -n mariadb apply -f samples/config
```

3. Provision a MariaDB instance
```shell
kubectl -n mariadb apply -f samples/mariadb_v1alpha1_mariadb.yaml
```

I've modified `mariadb_v1alpha1_mariadb.yaml` to include a 'standard' storage class:

```yaml
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard
  namespace: mariadb
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-mariadb
  labels:
    app: mariadb-mariadb
spec:
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  # storageClassName: "mariadb-mariadb"
  # storageClassName: local-path
  storageClassName: standard
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/cephfs/apps/mariadb/mariadb"

---
apiVersion: mariadb.mmontes.io/v1alpha1
kind: MariaDB
metadata:
  name: mariadb
spec:
  rootPasswordSecretKeyRef:
    name: mariadb
    key: root-password

  database: mariadb
  username: mariadb
  passwordSecretKeyRef:
    name: mariadb
    key: password

  image:
    repository: mariadb
    tag: "10.7.4"
    pullPolicy: IfNotPresent

  port: 3306

  volumeClaimTemplate:
    resources:
      requests:
        storage: 100Mi
    storageClassName: standard
    accessModes:
      - ReadWriteOnce

  myCnf: |
    [mysqld]
    bind-address=0.0.0.0
    default_storage_engine=InnoDB
    binlog_format=row
    innodb_autoinc_lock_mode=2
    max_allowed_packet=256M
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 512Mi

  env:
    - name: TZ
      value: SYSTEM

  envFrom:
    - configMapRef:
        name: mariadb

  podSecurityContext:
    runAsUser: 0

  securityContext:
    allowPrivilegeEscalation: false
```

**Additional context**

**Environment details**:
- Kubernetes version:  v1.24.11+k3s1
- mariadb-operator version:  0.11
- Install method: helm
- Install flavour: Recommended I think.
