### ISSUE TITLE
emptyDir sizeLimit configuration option

### ISSUE THREAD

**Issue by tsgit** [mariadb-operator/mariadb-operator#745]
**Is your feature request related to a problem? Please describe.**

The K8s cluster operated by my institution requires resource and size limits for many objects via kyverno policies.

The mariadb operator utilizes corev1:EmptyDirVolumeSource{} in several places, e.g. S3 (scheduled-) backup and restore.
There does not appear to be spec setting to define a sizeLimit for the emptyDir{}
 
**Describe the solution you'd like**

a spec.emptyDirVolumesSizeLimit option or similar could address this issue.

**Describe alternatives you've considered**

**Environment details**:
- Kubernetes version: 1.29
- Kubernetes distribution: Vanilla
- mariadb-operator version: 0.29.0
- Install method: static manifests
- Install flavor: recommended

**Additional context**

**Comment by mmontes11** [comment]
Hey there @tsgit ! 

Thanks for bringing this up! It makes total sense, we are lacking some configurability here that might impact the compliance of some users.

Here a list of resources where we use `EmptyDirVolumeSource` and how I suggest we change the CRs to provide a `EmptyDirVolumeSource` field. For all these cases, we could replace the current `corev1.EmptyDirVolumeSource{}`  with the `EmptyDirVolumeSource` provided by the user via the CR.

### Backup

```yaml
apiVersion: k8s.mariadb.com/v1alpha1
kind: Backup
metadata:
  name: backup
spec:
  storage:
    emptyDir:
      medium: Memory
      sizeLimit: 300Mi
    s3:
      bucket: backups
      prefix: mariadb
      endpoint: minio.minio.svc.cluster.local:9000
      region:  us-east-1
```

https://github.com/mariadb-operator/mariadb-operator/blob/46ef148a2a8bb69b337dd93fccda50cffb6dddd7/api/v1alpha1/backup_types.go#L177

### Restore

```yaml
apiVersion: k8s.mariadb.com/v1alpha1
kind: Restore
metadata:
  name: restore
spec:
  emptyDir:
    medium: Memory
    sizeLimit: 300Mi
  s3:
    bucket: backups
    prefix: mariadb
    endpoint: minio.minio.svc.cluster.local:9000
    region:  us-east-1
```

https://github.com/mariadb-operator/mariadb-operator/blob/46ef148a2a8bb69b337dd93fccda50cffb6dddd7/api/v1alpha1/base_types.go#L612

### MariaDB

```yaml
apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb
spec:
  storage:
    ephemeral: true
    emptyDir:
      medium: Memory
      sizeLimit: 300Mi
```

https://github.com/mariadb-operator/mariadb-operator/blob/46ef148a2a8bb69b337dd93fccda50cffb6dddd7/pkg/builder/pod_builder.go#L294

### MaxScale

```yaml
apiVersion: k8s.mariadb.com/v1alpha1
kind: MaxScale
metadata:
  name: maxscale
spec:
  config:
    emptyDir:
      medium: Memory
      sizeLimit: 300Mi
``` 
https://github.com/mariadb-operator/mariadb-operator/blob/46ef148a2a8bb69b337dd93fccda50cffb6dddd7/pkg/builder/pod_builder.go#L362

https://github.com/mariadb-operator/mariadb-operator/blob/46ef148a2a8bb69b337dd93fccda50cffb6dddd7/pkg/builder/pod_builder.go#L368

https://github.com/mariadb-operator/mariadb-operator/blob/46ef148a2a8bb69b337dd93fccda50cffb6dddd7/pkg/builder/pod_builder.go#L374


It seems like there are quite a few changes, but this could be a straightforward contribution since the user-specified field can be directly mapped. Contributions are welcomed!

**Comment by tsgit** [comment]
thanks for the quick response. yes, this would address my request.

I would caution about using medium: Memory by default, though. At least for the scheduled backup to s3 the initcontainer creates the mariadb-dump in emptyDir and the mariadb-operator container then copies the completed dump file to S3. 

The dump file can easily be tens of GB, which is more readily supported by local storage. I guess any arbitrary default limit would have to be adjusted by the user to match the individual requirements. Thus it becomes part of required configuration adjustments.

**Comment by ricottatosta** [comment]
I would suggest to consider the option of configuring a temporary PVC/volume where to store data before sending them to S3 server.

**Comment by mmontes11** [comment]
This has been partially addressed by https://github.com/mariadb-operator/mariadb-operator/pull/946. Stay tuned for the next release! 🚀 

In particular, `Backup` and `Restore` CR are now able to override the `emptyDir` by using the new `stagingStorage` field:

```yaml
apiVersion: k8s.mariadb.com/v1alpha1
kind: Backup
metadata:
  name: backup
spec:
  mariaDbRef:
    name: mariadb
  schedule:
    cron: "*/1 * * * *"
    suspend: false
  maxRetention: 720h # 30 days
  # ignoreGlobalPriv: true
  compression: gzip
  storage:
    s3:
      bucket: backups
      prefix: mariadb
      endpoint: minio.minio.svc.cluster.local:9000
      region:  us-east-1
      accessKeyIdSecretKeyRef:
        name: minio
        key: access-key-id
      secretAccessKeySecretKeyRef:
        name: minio
        key: secret-access-key
      tls:
        enabled: true
        caSecretKeyRef:
          name: minio-ca
          key: ca.crt
  stagingStorage:
    emptyDir:
      sizeLimit: 300Mi
```

You can also use an staging area to restore S3 backups via the `Restore` CR:

```yaml
apiVersion: k8s.mariadb.com/v1alpha1
kind: Restore
metadata:
  name: restore
spec:
  mariaDbRef:
    name: mariadb
  targetRecoveryTime: 2023-12-19T09:00:00Z
  s3:
    bucket: backups
    prefix: mariadb
    endpoint: minio.minio.svc.cluster.local:9000
    region:  us-east-1
    accessKeyIdSecretKeyRef:
      name: minio
      key: access-key-id
    secretAccessKeySecretKeyRef:
      name: minio
      key: secret-access-key
    tls:
      enabled: true
      caSecretKeyRef:
        name: minio-ca
        key: ca.crt
  stagingStorage:
    emptyDir:
      sizeLimit: 300Mi
```

As discussed in https://github.com/mariadb-operator/mariadb-operator/issues/745#issuecomment-2252887665, we are still missing some `emptyDir` fields in the `MariaDB` and `MaxScale` resources. Contributions are welcome!
