### ISSUE TITLE
[Feature] Allow adding RBAC aggregation for custom resources

### ISSUE THREAD

**Issue by gprossliner** [mariadb-operator/mariadb-operator#747]
**Is your feature request related to a problem? Please describe.**
If the operator chart is installed to a Kubernetes cluster, there is no RBAC bindings created only for the Custom Resources. So only `cluster-admin` users can create / view / ...`k8s.mariadb.com` objects.

* The helm chart should allow ClusterRoles to be created only for the `k8s.mariadb.com` Custom Resources. The currently created `Role` object grants all permissions needed be the operator, and so should used be the operator itself, and not for a user.
* The helm chart should allow the ClusterRoles to be annotated using [Aggregated Cluster Roles](https://kubernetes.io/docs/reference/access-authn-authz/rbac/#aggregated-clusterroles) to apply them to the standard `view` and `edit` roles.

**Describe the solution you'd like**
The chart should contain a template for an `mariadb-edit` and `mariadb-view` ClusterRole. If a helm values `e.g. values.rbac.aggregation.enabled=true` is set, than the ClusterRoles are created with the `rbac.authorization.k8s.io/aggregate-to-` annotations.

Example:

```yaml
# the mariadb-view ClusterRole allows viewing all k8s.mariadb.com resources
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mariadb-view
  labels:
    # based on values.rbac.aggregation.enabled 
    rbac.authorization.k8s.io/aggregate-to-view: "true"
rules:
- apiGroups: ["k8s.mariadb.com"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]
---
# the mariadb-edit ClusterRole allows editing k8s.mariadb.com resources
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mariadb-edit
  labels:
    # based on values.rbac.aggregation.enabled 
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
rules:
- apiGroups: ["k8s.mariadb.com"]
  resources: ["*"]
  verbs: ["create", "update", "patch", "delete"]
```

**Describe alternatives you've considered**

I have created the ClusterRoles described in the example above manually, and tested them. Works as expected.

**Environment details**:
- Kubernetes version: v1.24.17
- Kubernetes distribution: RKE (Rancher)
- mariadb-operator version: :v0.0.29
- Install method: helm
- Install flavor: using default values

I could contribute a PR in case.
