### ISSUE TITLE
[Feature] Support for `extraEnvFrom` in the helm chart

### ISSUE THREAD

**Issue by mmontes11** [mariadb-operator/mariadb-operator#749]
**Describe the solution you'd like**
Currently, we support [`extraEnv`](https://github.com/mariadb-operator/mariadb-operator/blob/46ef148a2a8bb69b337dd93fccda50cffb6dddd7/deploy/charts/mariadb-operator/values.yaml#L63) for passing extra environment variables to the operator `Deployment`. 

Instead of passing each env variable individually, be able to pass multiple variables by referencing a `ConfigMap` or a `Secret`:
```yaml
extraEnvFrom:
   - configMapRef:
       name: mariadb-operator-env-extra
```
