### ISSUE TITLE
[Feature] Recover Galera cluster from existing PVCs

### ISSUE THREAD

**Issue by mmontes11** [mariadb-operator/mariadb-operator#768]
**Describe the solution you'd like**
Currently, when deleting a `MariaDB` resource, the PVCs are left behind to prevent data loss. However, if we recreate the `MariaDB` resource, the cluster does not manage to come up due to the lack of `GaleraConfigured` and `GaleraReady` status conditions. Here it is the status in this case:

```yaml
status:
  conditions:
  - lastTransitionTime: "2024-08-01T13:58:01Z"
    message: Not ready
    reason: StatefulSetNotReady
    status: "False"
    type: Ready
  - lastTransitionTime: "2024-08-01T13:58:06Z"
    message: Updated
    reason: Updated
    status: "True"
    type: Updated
  currentPrimary: mariadb-galera-0
  currentPrimaryPodIndex: 0
```

Basically, the galera init job finishes but the `Pods` start to fail, since a Galera cluster recovery is needed, which will only be triggered if `GaleraConfigured=true` and `GaleraReady=false`. 

We can set this conditions from the Galera init `Job` after checking if `/var/lib/mysql` is populated. For doing so, we can add a very simple `status` subcommand to the `mariadb-operator` CLI, and invoke it as an `initContainer` of the Galera init `Job` .

**Comment by mmontes11** [comment]
Just tested this approach by running the following command after the Galera init job completes:

```bash
kubectl patch mariadbs.k8s.mariadb.com mariadb-galera --subresource status --type merge -p "$(cat status.mariadb.yaml)"
```
`status.mariadb.yaml`:
```yaml
status:
  conditions:
  - lastTransitionTime: "2024-08-01T13:58:01Z"
    message: Not ready
    reason: StatefulSetNotReady
    status: "False"
    type: Ready
  - lastTransitionTime: "2024-08-01T13:58:06Z"
    message: Updated
    reason: Updated
    status: "True"
    type: Updated
  - lastTransitionTime: "2024-08-01T11:06:14Z"
    message: Galera ready
    reason: GaleraNotReady
    status: "False"
    type: GaleraReady
  - lastTransitionTime: "2024-08-01T11:03:30Z"
    message: Galera configured
    reason: GaleraConfigured
    status: "True"
    type: GaleraConfigured
````
