### ISSUE TITLE
[Bug] mariadb container fail with "unable to start container process: exec: "init": executable file not found in $PATH: unknown"

### ISSUE THREAD

**Issue by businessbean** [mariadb-operator/mariadb-operator#777]
**Documentation**
- [x] I acknowledge that I have read the relevant [documentation](https://github.com/mariadb-operator/mariadb-operator/tree/main/docs).

**Describe the bug**
I have built the container image for the Operator and the Helm chart based on [d94a96b](https://github.com/mariadb-operator/mariadb-operator/commit/d94a96bfcb2d1a371154f65010b18018a99c530b). The `mariadb-init` job has been rolled out successfully, but than the `mariadb-0/1/2` pods are failing with `failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "init": executable file not found in $PATH: unknown`. Is the initContainer part not yet ready for 0.30.0? I'm testing with the main branch because i want to check out the MariaDB 10.5 support...

**Expected behaviour**

The mariadb pods should startup normally.

**Steps to reproduce the bug**

1. I have built the container image for the Operator and the Helm chart based on [d94a96b](https://github.com/mariadb-operator/mariadb-operator/commit/d94a96bfcb2d1a371154f65010b18018a99c530b).
```shell
make docker-build
make helm-gen
```
2. I have uploaded the artifacts to a private registry. Than i have installed the operator with helm
```shell
helm upgrade --install mariadb-operator . --set image.repository=registry.fqdn/project/mariadb-operator --set image.tag=main-d94a96bf --set webhook.image.repository=registry.fqdn/project/mariadb-operator --set webhook.image.tag=main-d94a96bf --set certController.image.repository=registry.fqdn/project/mariadb-operator --set certController.image.tag=main-d94a96bf
```

3. Afterwards i have requested a new database with custom `image:` values.
```yaml
apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb
  namespace: {{ $.Release.Namespace }}
spec:
  image: {{ .Values.image.repository }}
  imagePullPolicy: {{ .Values.image.pullPolicy }}

  rootPasswordSecretKeyRef:
    name: mariadb-root
    key: password
    generate: false

  username: mariadb
  passwordSecretKeyRef:
    name: mariadb-password
    key: password
    generate: false
  database: {{ .Values.mariadb.database }}

  storage:
    size: {{ .Values.mariadb.storage.size }}

  replicas: {{ .Values.replicaCount }}

  galera:
    enabled: true
    agent:
      image: {{ .Values.image.agent.repository }}
    initContainer:
      image: {{ .Values.image.initContainer.repository }}

  service:
    type: {{ .Values.mariadb.service.type }}
  connection:
    secretName: mariadb-conn
    secretTemplate:
      key: dsn
  primaryService:
    type: ClusterIP
  primaryConnection:
    secretName: mariadb-conn-primary
    secretTemplate:
      key: dsn
  secondaryService:
    type: {{ .Values.mariadb.service.type }}
  secondaryConnection:
    secretName: mariadb-conn-secondary
    secretTemplate:
      key: dsn

  updateStrategy:
    type: ReplicasFirstPrimaryLast

  myCnf: |
    [mariadb]
    bind-address=*
    default_storage_engine=InnoDB
    binlog_format=row
    innodb_autoinc_lock_mode=2
    innodb_buffer_pool_size=1024M
    max_allowed_packet=256M

  metrics:
    passwordSecretKeyRef:
      name: mariadb-metrics
      key: password
      generate: false
    enabled: true
```

4. The `mariadb-0/1/2` pods are failing with because the initContainer cannot be started
```
Init Containers:
  init:
    Container ID:  containerd://15b620fc95b0bc4cc5d1cb386d19977d424073575e1e1f9dba4438cdeafb1044
    Image:         registry.fqdn/project/mariadb-operator:0.30.0-d94a96bf
    Image ID:      registry.fqdn/project/mariadb-operator@sha256:17e2da765d57e78c6bd0c08b7bf4eba1ffe36880b323eba9824d463c0569ac6c
    Port:          <none>
    Host Port:     <none>
    Args:
      init
      --config-dir=/etc/mysql/mariadb.conf.d
      --state-dir=/var/lib/mysql
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       StartError
      Message:      failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "init": executable file not found in $PATH: unknown
      Exit Code:    128
      Started:      Thu, 01 Jan 1970 01:00:00 +0100
      Finished:     Wed, 07 Aug 2024 19:38:23 +0200
    Ready:          False
    Restart Count:  67
    Environment:
      MYSQL_TCP_PORT:            3306
      MARIADB_ROOT_HOST:         %
      CLUSTER_NAME:              cluster.local
      POD_NAME:                  mariadb-0 (v1:metadata.name)
      POD_NAMESPACE:             keystone (v1:metadata.namespace)
      POD_IP:                     (v1:status.podIP)
      MARIADB_NAME:              mariadb
      MARIADB_ROOT_PASSWORD:     <set to the key 'password' in secret 'mariadb-root'>  Optional: false
      MYSQL_INITDB_SKIP_TZINFO:  1
    Mounts:
      /etc/mysql/conf.d from config (rw)
      /etc/mysql/mariadb.conf.d from galera (rw)
      /var/lib/mysql from storage (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from serviceaccount (rw)
```

**Environment details**:
- Kubernetes version: `1.30.3`
- Kubernetes distribution: Vanilla
- mariadb-operator version: 0.30.0-dev (d94a96b)
- Galera agent (sidecar container): 0.30.0-dev (d94a96b)
- Install method: helm
- Install flavor: custom

**Additional context**
