### ISSUE TITLE
[Bug] MariaDBSpec args parameter has no effect

### ISSUE THREAD

**Issue by sepek** [mariadb-operator/mariadb-operator#778]
**Documentation**
- [x] I acknowledge that I have read the relevant [documentation](https://github.com/mariadb-operator/mariadb-operator/tree/main/docs).

**Describe the bug**

No matter if from scratch or changing an existing resource of the type MariaDB, with our without Galera - the `args` parameter has no effect. Also the operator does not trigger a recreation of the pod.

```
apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb
spec:
  args:
    - --verbose
```

```
kubectl get pod --namespace mariadb mariadb-0 -o json | grep args | wc -l
0
kubectl exec --stdin --tty  --namespace mariadb mariadb-0 -- ps ax
    PID TTY      STAT   TIME COMMAND
      1 ?        Ssl    0:00 mariadbd
     15 pts/0    Ss     0:00 bash
     22 pts/0    R+     0:00 ps ax
```

**Expected behaviour**
```
kubectl exec --stdin --tty  --namespace mariadb mariadb-0 -- ps ax
    PID TTY      STAT   TIME COMMAND
      1 ?        Ssl    0:00 mariadbd --verbose
     15 pts/0    Ss     0:00 bash
     22 pts/0    R+     0:00 ps ax
```

**Steps to reproduce the bug**
Based on:
* examples/manifests/config
* examples/manifests/mariadb.yaml

```
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb
  labels:
    k8s.mariadb.com/watch: ""
data:
  my.cnf: |
    [mariadb]
    bind-address=*
    default_storage_engine=InnoDB
    binlog_format=row
    innodb_autoinc_lock_mode=2
    innodb_buffer_pool_size=1024M
    max_allowed_packet=256M
---

apiVersion: v1
kind: Secret
metadata:
  name: mariadb
  labels:
    k8s.mariadb.com/watch: ""
stringData:
  password: MariaDB11!
  root-password: MariaDB11!
---

apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb
spec:
  args:
    - --verbose
  rootPasswordSecretKeyRef:
    name: mariadb-root
    key: password
    generate: true

  username: mariadb
  passwordSecretKeyRef:
    name: mariadb-password
    key: password
    generate: true
  database: mariadb

  port: 3306

  storage:
    size: 1Gi

  service:
    type: LoadBalancer
    metadata:
      annotations:
        metallb.universe.tf/loadBalancerIPs: 172.18.0.20

  myCnf: |
    [mariadb]
    bind-address=*
    default_storage_engine=InnoDB
    binlog_format=row
    innodb_autoinc_lock_mode=2
    innodb_buffer_pool_size=1024M
    max_allowed_packet=256M

  metrics:
    enabled: false
```

```
kubectl apply --namespace mariadb example.yml
```

**Debug information**
- Related object events:
```bash
kubectl get events --field-selector involvedObject.name=mariadb-0 --namespace mariadb
3m58s       Normal    Scheduled                pod/mariadb-0   Successfully assigned mariadb/mariadb-0 to gear-prod-mk8s-gra11-pool-gene-node-5e17f1
3m45s       Normal    SuccessfulAttachVolume   pod/mariadb-0   AttachVolume.Attach succeeded for volume "ovh-managed-kubernetes-c7nzd0-pvc-65f6012f-21fb-4bc6-9988-19b96a589957"
2m34s       Normal    Pulling                  pod/mariadb-0   Pulling image "docker-registry1.mariadb.com/library/mariadb:10.11.8"
3m43s       Normal    Pulled                   pod/mariadb-0   Successfully pulled image "docker-registry1.mariadb.com/library/mariadb:10.11.8" in 783ms (783ms including waiting)
3m8s        Normal    Created                  pod/mariadb-0   Created container mariadb
3m8s        Normal    Started                  pod/mariadb-0   Started container mariadb
2m34s       Warning   Unhealthy                pod/mariadb-0   Readiness probe failed: ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
2m34s       Warning   Unhealthy                pod/mariadb-0   Liveness probe failed: ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
2m34s       Normal    Killing                  pod/mariadb-0   Container mariadb failed liveness probe, will be restarted
2m34s       Warning   Unhealthy                pod/mariadb-0   Readiness probe failed: ERROR 2002 (HY000): Can't connect to local server through socket '/run/mysqld/mysqld.sock' (2)
3m8s        Normal    Pulled                   pod/mariadb-0   Successfully pulled image "docker-registry1.mariadb.com/library/mariadb:10.11.8" in 790ms (790ms including waiting)
```

**Environment details**:
- Kubernetes version: `v1.29.6`
- Kubernetes distribution: OVH Managed k8s
- mariadb-operator version: 0.29.0
- Galera agent (sidecar container): happens with and without Galera
- Install method: helm
- Install flavor: minimum

**Additional context**
Workaround with
```
command:
- mariadb
- --verbose
```
works

Please tell me if the debug information of the operator are required.
