### ISSUE TITLE
[Bug] podAffinity for Galera recovery jobs

### ISSUE THREAD

**Issue by 0xmeyer** [mariadb-operator/mariadb-operator#840]
**Documentation**
- [x] I acknowledge that I have read the relevant [documentation](https://github.com/mariadb-operator/mariadb-operator/tree/main/docs).

**Describe the bug**
I'm currently testing the mariadb-operator to run a Galera cluster in Kubernetes and I'm currently trying out the recovery process. Unfortunately, this does not work as described.

I have a StorageClass that only supports RWO. As soon as I kill all Galera pods, the recovery process is started after approx. 30s and therefore a job is deployed for each instance. However, since it is currently not possible to configure `podAffinity` for those jobs, it is possible that the jobs are scheduled on a different node than the PVC is currently mounted, which means that the recovery process does not complete. It would therefore be helpful if it would be possible to configure `podAffinity` for the job or enable it by default.

**Comment by mmontes11** [comment]
Hey there @0xmeyer !  Thanks for bringing this up! Makes total sense to me.

I suggest we introduce an `affinity` field in the recovery `Job`:

```yaml
apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb-galera
spec:
  galera:
    recovery:
       job:
         affinity:
           podAffinityEnabled: true  
```
`podAffinityEnabled` will be defaulted to true if not provided by the user, and it will result in the following affinity rules:

```yaml
apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb-galera
spec:
  galera:
    recovery:
      job:
        affinity:
          podAffinityEnabled: true
          podAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                  - key: app.kubernetes.io/instance
                    operator: In
                    values:
                    - mariadb-galera
                topologyKey: kubernetes.io/hostname
```
This way, we are enforcing the `Job` to be scheduled in the same node as the `MariaDB` `Pod`. 

Do you think this would cover your case?

**Comment by 0xmeyer** [comment]
> I suggest we introduce an `affinity` field in the recovery `Job`

Sounds good to me.

> and it will result in the following affinity rules ... we are enforcing the Job to be scheduled in the same node as the MariaDB Pod

Since every pod in the Galera cluster has this label, we can't make sure that the `mariadb-galera-0-recovery` pod is scheduled on the same node as the `mariadb-galera-0` pod, can we? Maybe we should additionally use the labels created by the statefulset controller (e.g. `apps.kubernetes.io/pod-index`). However, `apps.kubernetes.io/pod-index` cannot be defined statically; the operator must have logic built into it.

```yaml
apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb-galera
spec:
  galera:
    recovery:
      job:
        affinity:
          podAffinityEnabled: true
          podAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                  - key: app.kubernetes.io/instance
                    operator: In
                    values:
                    - mariadb-galera
                  - key: apps.kubernetes.io/pod-index
                    operator: In
                    values:
                    - "0"
                topologyKey: kubernetes.io/hostname
```
