### ISSUE TITLE
[Bug] MariaDB with semi-sync replication breaks during statefulset update

### ISSUE THREAD

**Issue by hedgieinsocks** [mariadb-operator/mariadb-operator#845]
**Documentation**
- [x] I acknowledge that I have read the relevant [documentation](https://github.com/mariadb-operator/mariadb-operator/tree/main/docs).

**Describe the bug**

Upon making changes to `MariaDB` CR, the operator triggers the update procedure according to the default `updateStrategy` set to `ReplicasFirstPrimaryLast`. So it first restarts the replica, then it restarts the primary and gets forever stuck, unable to promote the replica.

**Expected behaviour**

The operator is able to complete the promotion of the replica to the primary.

**Workaround**

Set `UpdateStrategy` to `OnDelete` on `MariaDB` CR to be able to manually delete first the replica and then primary. This way, the primary properly failovers to the replica upon its deletion.

**Steps to reproduce the bug**

1. Create a fresh `MariaDB` CR with semi-sync replication and 2 replicas
2. Edit the created `MariaDB` CR by e.g. increasing `innodb_buffer_pool_size` value

**Debug information**

- Used `MariaDB` template

```yaml
apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mary-test
spec:
  image: "mariadb:11.4.2"
  replicas: 2
  replication:
    enabled: true
    probesEnabled: true
  metrics:
  rootPasswordSecretKeyRef:
    name: mary-test
    key: ROOT_PASSWORD
  myCnf: |
    [mariadb]
    innodb_buffer_pool_size = 8G
    ignore_db_dirs = lost+found
  storage:
    volumeClaimTemplate:
      storageClassName: openebs-lvmpv
      volumeMode: Filesystem
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
```

- Replica logs related to the issue:

```
mary-test-1 mariadb 2024-09-12  6:18:05 4 [Note] Master 'mariadb-operator': Slave I/O thread: connected to master 'repl@mary-test-0.mary-test-internal.database.svc.cluster.local:3306',replication starts at GTID position '0-10-16'
mary-test-1 mariadb 2024-09-12  6:18:31 4 [Note] Master 'mariadb-operator': Slave: received end packet from server, apparent master shutdown:
mary-test-1 mariadb 2024-09-12  6:18:31 4 [Note] Master 'mariadb-operator': Slave I/O thread: Failed reading log event, reconnecting to retry, log 'mary-test-bin.000002' at position 2912; GTID position '0-10-17'
mary-test-1 mariadb 2024-09-12  6:18:31 4 [ERROR] Master 'mariadb-operator': Slave I/O: error reconnecting to master 'repl@mary-test-0.mary-test-internal.database.svc.cluster.local:3306' - retry-time: 10  maximum-retries: 100000  message: Can't connect to server on 'mary-test-0.mary-test-internal.database.svc.cluster.local' (111 "Connection refused"), Internal MariaDB error code: 2003
mary-test-1 mariadb 2024-09-12  6:19:51 4 [Note] Master 'mariadb-operator': Slave: connected to master 'repl@mary-test-0.mary-test-internal.database.svc.cluster.local:3306',replication resumed in log 'mary-test-bin.000002' at position 2912
mary-test-1 mariadb 2024-09-12  6:19:51 4 [ERROR] Master 'mariadb-operator': Slave I/O: Fatal error: The slave I/O thread stops because master and slave have equal MariaDB server ids; these ids must be different for replication to work (or the --replicate-same-server-id option must be used on slave but this does not always make sense; please check the manual before using it). Internal MariaDB error code: 1593
mary-test-1 mariadb 2024-09-12  6:19:51 4 [Note] Master 'mariadb-operator': Slave I/O thread exiting, read up to log 'mary-test-bin.000002', position 2912; GTID position 0-10-17, master mary-test-0.mary-test-internal.database.svc.cluster.local:3306
```

- Status of `MariaDB` after attempting an update

```yaml
automaticFailover: true
podIndex: 1
conditions:
  - lastTransitionTime: '2024-09-12T06:18:05Z'
    message: Switching primary to 'mary-test-1'
    reason: SwitchPrimary
    status: 'False'
    type: Ready
  - lastTransitionTime: '2024-09-12T06:17:58Z'
    message: Updating
    reason: Updating
    status: 'False'
    type: Updated
  - lastTransitionTime: '2024-09-12T06:18:32Z'
    message: Switching primary to 'mary-test-1'
    reason: SwitchPrimary
    status: 'False'
    type: PrimarySwitched
currentPrimary: mary-test-0
currentPrimaryPodIndex: 0
replicas: 2
replicationStatus:
  mary-test-0: NotConfigured
  mary-test-1: NotConfigured
```

**Environment details:**

* Kubernetes version: [1.25]
* Kubernetes distribution: [Rancher]
* mariadb-operator version: [0.29.0]
* Install method: [helm]
* Install flavor: [recommended]
