### ISSUE TITLE
[Bug] restore from mariabackup / initContainer example 

### ISSUE THREAD

**Issue by Thomas-Ganter** [mariadb-operator/mariadb-operator#846]
**Documentation**
- [x] I acknowledge that I have read the relevant [documentation](https://github.com/mariadb-operator/mariadb-operator/tree/main/docs).

**Describe the bug**
Trying to replicate MariaDB bootstrapping from a mariabackup folder I found the example provided in `examples/manifests/mariadb_init_mariabackup.yaml` to be wrong/ not working, mainly for two reasons: 

* the default mysql storage directory is not mounted into the init container
* once mounted, the storage directory is not empty

**Expected behaviour**
I expected the example to work, i. e. the operator to mount the storage volume automatically and the copy-back to complete successfully. 

**Steps to reproduce the bug**

1. Create a mariabackup from any Database
2. Prepare that backup for restoration
3. Run the example

Init container will CrashLoop. 

**Debug information**

This modification worked for me: 

``` 
  initContainers:
    - image: docker-registry1.mariadb.com/library/mariadb:11.4.3
      args:
        - mariadb-backup 
        - --copy-back 
        - --force-non-empty-directories 
        - --target-dir=/var/mariadb/backup/ 
      
      volumeMounts:
       - name: rsync-volume  # This is just the volume I rsync my backups into
         mountPath: "/var/mariadb/backup/"
       - name: storage
         mountPath: "/var/lib/mysql/"
       - name: config
         mountPath: "/etc/mysql/conf.d"
``` 

Note the two additional `volumeMounts` and the one additional argument. 

So, either I am missing something or the example is wrong, or there is a bug. 

**Environment details**:
- Kubernetes version: 1.30.4
- Kubernetes distribution: k3s
- mariadb-operator version: 0.30.0
- Install method: helm
- Install flavor: recommended

**Additional context**
