### ISSUE TITLE
[Bug] BackupSpec and RestoreSpec unable to use podSecurityContext

### ISSUE THREAD

**Issue by kaloyanDEV** [mariadb-operator/mariadb-operator#847]
securityContext which I set in Backup and Restore CR not rendered in the k8s Job-s

**Documentation**
- https://github.com/mariadb-operator/mariadb-operator/blob/main/docs/API_REFERENCE.md#restore
- https://github.com/mariadb-operator/mariadb-operator/blob/main/docs/API_REFERENCE.md#backupspec

**Describe the bug**
Pod security context is empty

```
securityContext: {}
```
Sample

```
apiVersion: k8s.mariadb.com/v1alpha1
kind: Backup
metadata:
  name: backup
spec:
  logLevel: debug
  restartPolicy: OnFailure
  serviceAccountName: account
  ignoreGlobalPriv: false
  resources:
    limits:
      cpu: 300m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
  podSecurityContext:
    runAsGroup: 1
    runAsUser: 1
  backoffLimit: 5
  schedule:
    cron: '* * * * *'
    suspend: false
  maxRetention: 48h
  storage:
    volume:
      nfs:
        path: /vol
        server: host
  args:
    - '--verbose'
    - '--single-transaction'
    - '--all-databases'
  mariaDbRef:
    name: mariadb
    waitForIt: true

```

**Expected behaviour**
```
securityContext:
  runAsGroup: 1
  runAsUser: 1
```

**Steps to reproduce the bug**
Create Backup object from the yaml I provided

**Debug information**

**Environment details**:
- Kubernetes version: [v1.27.16+e826056]
- Kubernetes distribution: [OpenShift]
- mariadb-operator version: [0.30.0]
- Galera agent (sidecar container): [Version number]
- Install method: [OLM]
- Install flavor: [minimal, recommended, or custom]

**Additional context**
