### ISSUE TITLE
[Bug] MaxScale GUI session expires immediately after login

### ISSUE THREAD

**Issue by ikubetoomuzik** [mariadb-operator/mariadb-operator#858]
**Documentation**
- [x] I acknowledge that I have read the relevant [documentation](https://github.com/mariadb-operator/mariadb-operator/tree/main/docs).

**Describe the bug**
When trying to access the MaxScale GUI using a Traefik Ingress I can login but immediately get a "Session Expired" notice and get logged back out.

Ingress:
```yaml
---    
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: maxscale-galera-http
spec:
  rules:
    - host: <hostname>
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: maxscale-galera-gui
                port:
                  number: 8989
```

Maxscale Definition:
```yaml
apiVersion: k8s.mariadb.com/v1alpha1
kind: MaxScale
metadata:
  name: maxscale-galera
spec:
  auth:
    generate: true
  replicas: 3

  mariaDbRef:
    name: mariadb-galera
    namespace: mariadb

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      memory: 1Gi
```

**Expected behaviour**
I expect when I log into the GUI it will not log out until I request it to.

**Steps to reproduce the bug**

1. Followed examples for FluxCD
2. Create traefik ingress pointing at the 'maxscale-galera-gui' service.
3. Browse to url and attempt login, you will be immediately logged out.

**Debug information**
Could not find any object events or logs related to why my session is expiring, this may be my ignorance on where that might've been logged.

**Environment details**:
- Kubernetes version: [Version number]
- Kubernetes distribution: Vanilla
- mariadb-operator version: 0.0.31
- Galera agent (sidecar container): 0.0.31
- Install method: helm
- Install flavor: minimal?

**Additional context**
This is basically a fresh installation on a test system, there should be no other software interfering with the definitions. The only error I can see is: "Cannot reconcile ServiceMonitor" but I had disabled metrics when installing through helm so I don't think that error is really relevant.

**Comment by achar007** [comment]
I'm experiencing the same as soon as I login session expires.

**Comment by djjudas21** [comment]
Same observed here. I am already using the GUI service.

```yaml
apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb-galera
  namespace: mariadb-op-test
spec:
  rootPasswordSecretKeyRef:
    name: mariadb
    key: root-password
  storage:
    size: 2Gi
  replicas: 3
  # provision a MaxScale instance and set 'spec.maxScaleRef' automatically.
  maxScale:
    enabled: true
    replicas: 3
    kubernetesService:
      type: ClusterIP
    guiKubernetesService:
      type: ClusterIP
    connection:
      secretName: mxs-galera-conn
      port: 3306
    metrics:
      enabled: true
  galera:
    enabled: true
    config:
      reuseStorageVolume: true
  service:
    type: ClusterIP
  primaryService:
    type: ClusterIP
  secondaryService:
    type: ClusterIP
  metrics:
    enabled: true
```

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  name: mariadb-galera
  namespace: mariadb-op-test
spec:
  ingressClassName: public
  rules:
  - host: galera-maxscale.example.com
    http:
      paths:
      - backend:
          service:
            name: mariadb-galera-maxscale-gui
            port:
              number: 8989
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - galera-maxscale.example.com
    secretName: galera-maxscale-tls
```

**Comment by mmontes11** [comment]
Hey there @djjudas21 ! 

The MaxScale GUI `Service` uses `sessionAffinity: ClientIP` to guarantee that the client always addresses the same `Pod` and therefore the session is mantained. However, when using an API gateway, this session affinity may not be preserved, resulting in the MaxScale `Service` seeing different client IPs each time, and therefore redirecting the requests to a different `Pod`. 

As an alternative, and to save you some configuration on the API gateway side, we could point the MaxScale service to a specific `Pod` by adding it to the `Service` selector:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: maxscale-gui
spec:
  ports:
  - name: admin
    port: 8989
    protocol: TCP
    targetPort: 8989
  selector:
    app.kubernetes.io/instance: maxscale-xiaowen
    app.kubernetes.io/name: maxscale
    apps.kubernetes.io/pod-index: "0"   
``` 

The `apps.kubernetes.io/pod-index` label will be dynamic depending on the `Pods`  availability (i.e. first available `Pod`). Let me know if this makes sense to you.

Thanks!
