### ISSUE TITLE
[Bug] PVC StorageClass creation trouble on case of galera usage

### ISSUE THREAD

**Issue by obeyler** [mariadb-operator/mariadb-operator#862]
**Documentation**
- [X] I acknowledge that I have read the relevant [documentation](https://github.com/mariadb-operator/mariadb-operator/tree/main/docs). (https://github.com/mariadb-operator/mariadb-operator/blob/main/docs/STORAGE.md#configuration)

**Describe the bug**
If you want to use a storageClassName it's works for Mariadb on replication mode but not on galera mode

```
apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb-repl
spec:
  rootPasswordSecretKeyRef:
    name: mariadb
    key: root-password

  storage:
    storageClassName: longhorn
    resizeInUseVolumes: true
    waitForVolumeResize: true
    volumeClaimTemplate:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: longhorn

  replicas: 3

  # provision a MaxScale instance and set 'spec.maxScaleRef' automatically.
  maxScale:
    enabled: true

    kubernetesService:
      type: ClusterIP

    guiKubernetesService:
      type: ClusterIP

    connection:
      secretName: mxs-repl-conn
      port: 3306

#  replication:
#    enabled: true

  galera:
    enabled: true

  metrics:
    enabled: true
```

```
kubectl get pod -n test
NAME             READY   STATUS    RESTARTS   AGE
mariadb-repl-0   0/2     Pending   0          7m52s
mariadb-repl-1   0/2     Pending   0          7m52s
mariadb-repl-2   0/2     Pending   0          7m52s
```
The pod is not able to be created because the storage class is ignored and I don't have a default storageclass
```
Events:
  Type     Reason            Age                    From               Message
  ----     ------            ----                   ----               -------
  Warning  FailedScheduling  3m59s (x4 over 9m18s)  default-scheduler  0/3 nodes are available: pod has unbound immediate PersistentVolumeClaims. preemption: 0/3 nodes are available: 3 Preemption is not helpful for scheduling..
```

**Expected behaviour**
pod running

**Steps to reproduce the bug**
 launch it you'll have 3 PVC galera-mariadb-repl-x without storageClass requested
and 3 PVC storage-mariadb-repl-x with the storageClass requested

```
kubectl get pvc -n test galera-mariadb-repl-0 -o yaml 
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app.kubernetes.io/instance: mariadb-repl
    app.kubernetes.io/name: mariadb
    pvc.k8s.mariadb.com/role: config
  name: galera-mariadb-repl-0
  namespace: test
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  volumeMode: Filesystem
status:
  phase: Pending

kubectl get pvc -n test
NAME                     STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
galera-mariadb-repl-0    Pending                                                                                       20s
galera-mariadb-repl-1    Pending                                                                                       20s
galera-mariadb-repl-2    Pending                                                                                       20s
storage-mariadb-repl-0   Bound     pvc-010bb9cc-5d21-4e4d-9abc-c92a495725d4   10Gi       RWO            longhorn       46s
storage-mariadb-repl-1   Bound     pvc-9574c289-5af3-43b4-83c5-b8e46b71b1c7   10Gi       RWO            longhorn       20s
storage-mariadb-repl-2   Bound     pvc-9b273ebb-cb4a-43d9-9024-9a8712f4e678   10Gi       RWO            longhorn       20s
```

**Additional context**
operator 0.0.31
we can see that on the statefullset the volumeClaimtemplate dedicated for galera is wrong whereas the volumeClaimtemplate for storage is good:
```
...
kubectl get statefulsets.apps -n test -o yaml
....

    volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        creationTimestamp: null
        labels:
          pvc.k8s.mariadb.com/role: storage
        name: storage
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: longhorn # <========= Good
        volumeMode: Filesystem
      status:
        phase: Pending
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        creationTimestamp: null
        labels:
          pvc.k8s.mariadb.com/role: config
        name: galera
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 100Mi
        volumeMode: Filesystem
# <========= storageClassName is missing
```

**Comment by mmontes11** [comment]
Hey @obeyler ! Thanks for raising this.

Galera requires to persist configuration files, for this reason, we have a dedicated `volumeClaimTemplate` just for the config, as described here in the docs:
- https://github.com/mariadb-operator/mariadb-operator/blob/main/docs/GALERA.md#storage

Your issue is that you are not explicitly providing a `storageClassName` for the config volume, therefore, the default will be used. Note that this is independent from the `storage` one. You may provide it explicitly by setting:

```yaml
apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb-galera
spec:

  storage:
    storageClassName: longhorn
    resizeInUseVolumes: true
    waitForVolumeResize: true
    volumeClaimTemplate:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: longhorn

  galera:
    enabled: true
    config:
      reuseStorageVolume: false
      volumeClaimTemplate:
        storageClassName: longhorn
        resources:
          requests:
            storage: 300Mi
        accessModes:
          - ReadWriteOnce
```

See the API reference for further detail:
- https://github.com/mariadb-operator/mariadb-operator/blob/main/docs/API_REFERENCE.md#galeraconfig

Closing! Let me know if you have further questions.
