### ISSUE TITLE
[Bug] MariaDB operator stuck when trying to switch from replication to Galera

### ISSUE THREAD

**Issue by kos-team** [mariadb-operator/mariadb-operator#864]
**Documentation**
- [x] I acknowledge that I have read the relevant [documentation](https://github.com/mariadb-operator/mariadb-operator/tree/main/docs).

**Describe the bug**

After changing the MariaDB cluster from replication to using Galera, the operator fails to update the MariaDB pods and gets stuck.
It keeps trying to run recovery for Galera, although the Pods have not been restarted with the Galera agents yet.

**Expected behaviour**

The MariaDB pods should be able to restart with Galera enabled.

**Steps to reproduce the bug**

1. First create a MariaDB cluster with replication enabled, by applying the following yaml
```yaml
apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb-min
spec:
  rootEmptyPassword: true
  storage:
    size: 1Gi
    storageClassName: standard
    resizeInUseVolumes: true
    waitForVolumeResize: true
  galera:
    enabled: false
  replication:
    enabled: true
  replicas: 3
```
2. Switch from replication to galera:
```yaml
apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb-min
spec:
  rootEmptyPassword: true
  storage:
    size: 1Gi
    storageClassName: standard
    resizeInUseVolumes: true
    waitForVolumeResize: true
  galera:
    enabled: true
  replicas: 3
```
4. The MariaDB Pods remain with replication

**Debug information**
- Related object events:
```bash
kubectl get events --field-selector involvedObject.name=<mariadb-resource-name>
kubectl get events --field-selector involvedObject.name=<backup-resource-name>
kubectl get events --field-selector involvedObject.name=<restore-resource-name>
```
- `mariadb-operator` logs. Set the `--log-level` to `debug` if needed.
```
{"level":"error","ts":1726348336.0454385,"msg":"Unable to reconcile metrics","controller":"mariadb","controllerGroup":"k8s.mariadb.com","controllerKind":"MariaDB","MariaDB":{"name":"mariadb","namespace":"default"},"namespace":"default","name":"mariadb","reconcileID":"387af0a7-fe16-4aaa-ae23-18b78bf86128","error":"ServiceMonitor CRD not installed in the cluster","stacktrace":"github.com/mariadb-operator/mariadb-operator/internal/controller.(*MariaDBReconciler).reconcileMetrics\n\t/app/internal/controller/mariadb_controller_metrics.go:43\ngithub.com/mariadb-operator/mariadb-operator/internal/controller.(*MariaDBReconciler).Reconcile\n\t/app/internal/controller/mariadb_controller.go:193\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Reconcile\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:116\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:303\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:263\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:224"}
{"level":"info","ts":1726348340.21036,"logger":"galera.recovery","msg":"Recovering cluster","controller":"mariadb","controllerGroup":"k8s.mariadb.com","controllerKind":"MariaDB","MariaDB":{"name":"mariadb","namespace":"default"},"namespace":"default","name":"mariadb","reconcileID":"8ffe6aac-ef98-4891-b0f9-7f47b9f69d32"}
{"level":"error","ts":1726348640.2617462,"msg":"Reconciler error","controller":"mariadb","controllerGroup":"k8s.mariadb.com","controllerKind":"MariaDB","MariaDB":{"name":"mariadb","namespace":"default"},"namespace":"default","name":"mariadb","reconcileID":"8ffe6aac-ef98-4891-b0f9-7f47b9f69d32","error":"error reconciling Galera: 1 error occurred:\n\t* error recovering cluster: error getting state: 1 error occurred:\n\t* error getting Galera state for Pod 'mariadb-2': context deadline exceeded\n\n\n\n","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:316\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:263\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:224"}
{"level":"info","ts":1726348640.4087565,"logger":"galera.recovery","msg":"Recovering cluster","controller":"mariadb","controllerGroup":"k8s.mariadb.com","controllerKind":"MariaDB","MariaDB":{"name":"mariadb","namespace":"default"},"namespace":"default","name":"mariadb","reconcileID":"a52fbca9-6d5a-46cc-9f81-f40d4987272b"}
```

**Environment details**:
- Kubernetes version: v1.29.1
- Kubernetes distribution: KIND
- mariadb-operator version: 0.30.0
- Galera agent (sidecar container): N/A
- Install method: helm
- Install flavor: minimal

**Additional context**
