### ISSUE TITLE
[Bug] MariaDB operator is unable to update the MaxScale object after it is created

### ISSUE THREAD

**Issue by kos-team** [mariadb-operator/mariadb-operator#874]
**Documentation**
- [x] I acknowledge that I have read the relevant [documentation](https://github.com/mariadb-operator/mariadb-operator/tree/main/docs).

**Describe the bug**

We found that the operator is unable to update the MaxScale stanza in the MariaDB CR after the MariaDB and MaxScale is created.

**Expected behaviour**

The MariaDB pods should be able to restart with Galera enabled.

**Steps to reproduce the bug**

1. First create a MariaDB cluster with MaxScale specified, e.g.:
```yaml
apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb-min
spec:
  rootEmptyPassword: true
  storage:
    size: 1Gi
    storageClassName: standard
    resizeInUseVolumes: true
    waitForVolumeResize: true
  replication:
    enabled: true
  replicas: 3
  maxScale:
    admin:
      port: 8989
    connection:
      port: 3306
      secretName: mxs-galera-conn
    enabled: true
```
2. Change the `admin.port` from `8989` to `8888`, and observe that nothing happens:
```yaml
apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb-min
spec:
  rootEmptyPassword: true
  storage:
    size: 1Gi
    storageClassName: standard
    resizeInUseVolumes: true
    waitForVolumeResize: true
  replication:
    enabled: true
  replicas: 3
  maxScale:
    admin:
      port: 8888
    connection:
      port: 3306
      secretName: mxs-galera-conn
    enabled: true
```

**Debug information**
- Related object events:
```bash
kubectl get events --field-selector involvedObject.name=<mariadb-resource-name>
kubectl get events --field-selector involvedObject.name=<backup-resource-name>
kubectl get events --field-selector involvedObject.name=<restore-resource-name>
```
- `mariadb-operator` logs. Set the `--log-level` to `debug` if needed.
There is no new log in the mariadb-operator after the CR change regarding the MaxScale is applied.

**Environment details**:
- Kubernetes version: v1.29.1
- Kubernetes distribution: KIND
- mariadb-operator version: 0.30.0
- Galera agent (sidecar container): N/A
- Install method: helm
- Install flavor: minimal

**Additional context**

Root cause: We found that the logic in the MaxScale controller's reconciliation logic is to create A MaxScale CR according to the MaxScale stanze in the MariaDB CR. The reconciliation logic also tries to update the MaxScale CR, however, it only updates the MaxScale object if the desired MaxScale's property is not empty and the current MaxScale has a ZeroValue for the changed property:
https://github.com/mariadb-operator/mariadb-operator/blob/6171b061f944e10e29197fbdc7e4d1144b08352d/pkg/controller/maxscale/controller.go#L57-L64
