### ISSUE TITLE
[Bug] MariaDB operator does not delete left over secret after disabling MaxScale, causing resource leaks

### ISSUE THREAD

**Issue by kos-team** [mariadb-operator/mariadb-operator#875]
**Documentation**
- [x] I acknowledge that I have read the relevant [documentation](https://github.com/mariadb-operator/mariadb-operator/tree/main/docs).

**Describe the bug**

After we disable the MaxScale component, we found that the ConfigMap created for the MaxScale's configuration was not deleted.

**Expected behaviour**

We expect the ConfigMap to be garbage collected after the MaxScale is disabled.

**Steps to reproduce the bug**

1. First create a MariaDB cluster with replication enabled, by applying the following yaml
```yaml
apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb-min
spec:
  rootEmptyPassword: true
  storage:
    size: 1Gi
    storageClassName: standard
    resizeInUseVolumes: true
    waitForVolumeResize: true
  galera:
    enabled: false
  replication:
    enabled: true
  replicas: 3
  maxScale:
    connection:
      port: 3306
      secretName: mxs-galera-conn
    enabled: true
```
2. Disable MaxScale:
```yaml
apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb-min
spec:
  rootEmptyPassword: true
  storage:
    size: 1Gi
    storageClassName: standard
    resizeInUseVolumes: true
    waitForVolumeResize: true
  galera:
    enabled: false
  replication:
    enabled: true
  replicas: 3
  maxScale:
    connection:
      port: 3306
      secretName: mxs-galera-conn
    enabled: false
```
3. Observe that MaxScale pods are deleted, but the ConfigMap `mxs-galera-conn` is not deleted.

**Debug information**

**Environment details**:
- Kubernetes version: v1.29.1
- Kubernetes distribution: KIND
- mariadb-operator version: 0.30.0
- Galera agent (sidecar container): N/A
- Install method: helm
- Install flavor: minimal

**Additional context**
