### ISSUE TITLE
[Bug] MariaDB operator does not delete left over ConfigMap after disabling replication.probeEnabled, causing resource leaks

### ISSUE THREAD

**Issue by kos-team** [mariadb-operator/mariadb-operator#876]
**Documentation**
- [x] I acknowledge that I have read the relevant [documentation](https://github.com/mariadb-operator/mariadb-operator/tree/main/docs).

**Describe the bug**

After we change the `replication.probeEnabled` from `true` to `false`, although the Pods are updated correctly, but the ConfigMap which was previously used by the probes remains undeleted. This causes leftover resources stored in etcd.

**Expected behaviour**

We expect the ConfigMap to be garbage collected after the `replication.probeEnabled` is disabled.

**Steps to reproduce the bug**

1. First create a MariaDB cluster with replication and probeEnabled enabled
```yaml
apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb-min
spec:
  rootEmptyPassword: true
  storage:
    size: 1Gi
    storageClassName: standard
    resizeInUseVolumes: true
    waitForVolumeResize: true
  galera:
    enabled: false
  replication:
    enabled: true
    probesEnabled: true
  replicas: 3
```
2. Disable the `replication.probeEnabled`:
```yaml
apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb-min
spec:
  rootEmptyPassword: true
  storage:
    size: 1Gi
    storageClassName: standard
    resizeInUseVolumes: true
    waitForVolumeResize: true
  galera:
    enabled: false
  replication:
    enabled: true
    probesEnabled: false
  replicas: 3
```

**Debug information**

**Environment details**:
- Kubernetes version: v1.29.1
- Kubernetes distribution: KIND
- mariadb-operator version: 0.30.0
- Galera agent (sidecar container): N/A
- Install method: helm
- Install flavor: minimal

**Additional context**

The ConfigMap `test-cluster-probes` is left undeleted.
