### ISSUE TITLE
[Feature] Specify securityContext for metrics exporter pod

### ISSUE THREAD

**Issue by andreasgeisslerdt** [mariadb-operator/mariadb-operator#901]
**Is your feature request related to a problem? Please describe.**
To deploy the MariaDB instance in production we need to fulfil security requirements (checked by kyverno).
One of the requirements are certain securityContext settings on container level:
```
  securityContext:
    readOnlyRootFilesystem: true
    privileged: false
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
        - CAP_NET_RAW
```
It was possible to set the securityContext for the mariadb and for the metrics exporter in Operator version 0.31.0,
https://github.com/mariadb-operator/mariadb-operator/blob/v0.0.31/docs/API_REFERENCE.md#exporter
but in version 0.32.0/0.33.0 the setting for the exporter was removed to save space in the CRD definitions:
https://github.com/mariadb-operator/mariadb-operator/blob/v0.0.33/docs/API_REFERENCE.md#exporter

**Describe the solution you'd like**
The previous feature should be restored to solve security related issues.

**Environment details**:
- mariadb-operator version: 0.33.0
