### ISSUE TITLE
[Bug] cannot recover galera cluster

### ISSUE THREAD

**Issue by vixns** [mariadb-operator/mariadb-operator#911]
The recovery jobs are failing with the following error :

```
mariadbd: Please consult the Knowledge Base to find out how to run mysqld as root!
2024-10-05  9:15:44 0 [ERROR] Aborting
```

The associated mariadb resource :
```
apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb
  namespace: customer345
spec:
  rootPasswordSecretKeyRef:
    generate: false
    name: mariadb
    key: root-password
  storage:
    size: 10Gi
  replicas: 3
  galera:
    enabled: true
    agent:
      image: docker-registry3.mariadb.com/mariadb-operator/mariadb-operator:v0.0.33
    initContainer:
      image: docker-registry3.mariadb.com/mariadb-operator/mariadb-operator:v0.0.33
    replicaThreads: 1
    config:
      volumeClaimTemplate:
        resources:
          requests:
            storage: 300Mi
        accessModes:
          - ReadWriteOnce
    recovery:
      enabled: true
      minClusterSize: 1
      clusterMonitorInterval: 10s
      clusterHealthyTimeout: 30s
      clusterBootstrapTimeout: 10m0s
      podRecoveryTimeout: 5m0s
      podSyncTimeout: 5m0s
  podSecurityContext:
    runAsUser: 0
    seccompProfile:
      type: Unconfined
  metrics:
    enabled: true
  myCnf: |
    [mariadb]
      table_open_cache=3000
      table_definition_cache=3000
      query_cache_size=64M
      query_cache_limit=16M
      binlog_cache_size=16M
      open_files_limit = 100000
      max_connect_errors=100000
      max_allowed_packet=256M
      transaction_isolation=READ-COMMITTED
      innodb_buffer_pool_size=2G
      innodb_log_file_size=512M
      innodb_buffer_pool_instances=4
      innodb_flush_log_at_trx_commit=2
  updateStrategy:
    autoUpdateDataPlane: true
```

**Comment by mmontes11** [comment]
Hey there, the following PRs will be included in the version to be released next week:
- https://github.com/mariadb-operator/mariadb-operator/pull/904
- https://github.com/mariadb-operator/mariadb-operator/pull/910

Hopefully your issue is related!

**Comment by mmontes11** [comment]
But in any case, I think your issue is different @vixns :

```yaml
  podSecurityContext:
    runAsUser: 0
    seccompProfile:
      type: Unconfined
```

```bash
mariadbd: Please consult the Knowledge Base to find out how to run mysqld as root!
2024-10-05  9:15:44 0 [ERROR] Aborting
```

The `mariadb` container does not allow to run as root by default. I think the easiest way forward is opening an issue in here:
- https://github.com/MariaDB/mariadb-docker

cc @grooverdan

**Comment by vixns** [comment]
https://github.com/MariaDB/mariadb-docker/blob/master/10.11/docker-entrypoint.sh#L698

The entrypoint is switching to mysql user when ran as root, The recovery job command should also gosu when ran as user 0.

I guess i can workaround this by changing `runAsUser` to `999` if mutable.

**Comment by mmontes11** [comment]
There were some discussiong about `gosu` not actually needed here, not sure about the actual status:
- https://github.com/MariaDB/mariadb-docker/pull/598

In any case, yes, the operator defaults to `999`:

```yaml
  securityContext:
    fsGroup: 999
    runAsGroup: 999
    runAsNonRoot: true
    runAsUser: 999
```

which does not present that problem.
