### ISSUE TITLE
[Feature] Improve updates handling in semi-sync cluster

### ISSUE THREAD

**Issue by hedgieinsocks** [mariadb-operator/mariadb-operator#928]
**Is your feature request related to a problem? Please describe.**

In v0.0.29 `my.cnf` configuration became [mutable](https://github.com/mariadb-operator/mariadb-operator/releases/tag/v0.0.29). 

However, the default `ReplicasFirstPrimaryLast` update strategy proved to be unreliable in my [case](https://github.com/mariadb-operator/mariadb-operator/issues/845).

I tried `RollingUpdate` update strategy, and it seems to go through without breaking the cluster. However, neither approach is acceptable because it leads to downtime. This is so because after the master pod is finally deleted, [switchover cannot proceed because replication is not configured yet](
https://github.com/mariadb-operator/mariadb-operator/blob/c274f8eb66d8545872162f5bbf40af31eb5851d1/pkg/controller/replication/switchover.go#L31).  So the operator waits for the master to go up, and then it configures replication. And once it is finally configured as before the update, the operator proceeds the switchover. But that action does not make any sense.

**Describe the solution you'd like**

I want operator to be able to perform  automatic switchover just before it updates the master pod in a semi-sync replication cluster.

Alternatively, I want to be able to set `OnDelete` update policy and be able to trigger switchover after I update replicas and before I update master. Currently, it is [impossible](https://github.com/mariadb-operator/mariadb-operator/blob/c274f8eb66d8545872162f5bbf40af31eb5851d1/pkg/controller/replication/switchover.go#L28) due to `mdb.IsUpdating()` check.

**Environment details**:

- Kubernetes version: 1.26
- Kubernetes distribution: Rancher
- mariadb-operator version: 0.34.0
- Install method: helm

**Comment by hedgieinsocks** [comment]
Hello @mmontes11 could you please check my complaint and tell me at least if doing PR to remove `mdb.IsUpdating()`  from `shouldReconcileSwitchover()` is something that makes sense to you?

**Comment by hedgieinsocks** [comment]
Here is some additional info that might illustrate the issue:

```yaml

##############################
##### regular switchover #####
##############################

# normal running cluster

replicatioin:
  primary:
    podIndex: 0
currentPrimaryPodIndex: 0
replicas: 2
replicationStatus:
  mariadb-0: Master
  mariadb-1: Slave

# kill master pod =>

replicatioin:
  primary:
    podIndex: 1
currentPrimaryPodIndex: 0
replicas: 1
replicationStatus:
  mariadb-1: Slave

# operator switchovers =>

replicatioin:
  primary:
    podIndex: 1
currentPrimaryPodIndex: 1
replicas: 1
replicationStatus:
  mariadb-1: Master

# previous master joins as slave and cluster is ok

replicatioin:
  primary:
    podIndex: 1
currentPrimaryPodIndex: 1
replicas: 2
replicationStatus:
  mariadb-0: Slave
  mariadb-1: Master

#####################################
##### update wtih RollingUpdate #####
#####################################

# normal running cluster

replicatioin:
  primary:
    podIndex: 0
currentPrimaryPodIndex: 0
replicas: 2
replicationStatus:
  mariadb-0: Master
  mariadb-1: Slave

# tweak my.cnf and see how slave gets recreated =>

replicatioin:
  primary:
    podIndex: 0
currentPrimaryPodIndex: 0
replicas: 1
replicationStatus:
  mariadb-0: Master

# now operator restarted master and noted new desired index =>

replicatioin:
  primary:
    podIndex: 1
currentPrimaryPodIndex: 0
replicas: 1
replicationStatus:
  mariadb-0: Master

# and soon recreated slave is the only one in the status =>

replicatioin:
  primary:
    podIndex: 1
currentPrimaryPodIndex: 0
replicas: 1
replicationStatus:
  mariadb-1: NotConfigured

# and then it is joined by our previous master => 

replicatioin:
  primary:
    podIndex: 1
currentPrimaryPodIndex: 0
replicas: 1
replicationStatus:
  mariadb-1: NotConfigured
  mariadb-1: NotConfigured

# then in some time replication manages to configure itself and primary gets finally switched

replicatioin:
  primary:
    podIndex: 1
currentPrimaryPodIndex: 1
replicas: 2
replicationStatus:
  mariadb-1: Slave
  mariadb-1: Master
```

**Comment by mmontes11** [comment]
Hey there @hedgieinsocks ! Thanks for the detailed report. 

> I want operator to be able to perform automatic switchover just before it updates the master pod in a semi-sync replication cluster.

Yes, I agree. Ideally we should have a dedicated upgrade logic for replication. Assuming we have a 3 `Pod` replication cluster, where `mariadb-replication-1` is the primary, the logic would be:

- Update `mariadb-replication-2`
- Update `mariadb-replication-0`
- Switchover primary from `mariadb-replication-1` to a non lagged instance, most likely any of the previous 2, since they were just upgraded and synced.
- Upgrade `mariadb-replication-1` 

We have plans not only to implement this upgrade logic, but also to re-architect the whole repliccation implementation, most likely ditching the  `StatefulSet` to enable better replica rebuild. Before that happens, we still have more prioritary items in the roadmap, like [TLS](https://github.com/mariadb-operator/mariadb-operator/issues/137). 

That said, in case you haven't noticed in the docs, the current replication implementation is in alpha stage:
https://github.com/mariadb-operator/mariadb-operator/blob/main/docs/HA.md#topologies

Our recommendation is using Galera at this point if virtually synchronous replication fits your needs.

> Alternatively, I want to be able to set OnDelete update policy and be able to trigger switchover after I update replicas and before I update master. 

That's a legit suggestion, since this only affects the replication controller, I think it shoud be acceptable:
https://github.com/mariadb-operator/mariadb-operator/blob/c274f8eb66d8545872162f5bbf40af31eb5851d1/pkg/controller/replication/switchover.go#L28)

Please open a PR and refer to this issue as context!

**Comment by hedgieinsocks** [comment]
@mmontes11 I'm almost there :smiley:  With `ReplicasFirstPrimaryLast` I ensure replication is configured before deleting master pod and this makes switchover more robust. But I cannot overcome another related issue, which seems to be race condition :cry: 

The pod replication controller updates MariaDB status [here](https://github.com/mariadb-operator/mariadb-operator/blob/30f03700750b743cf4e10f005a800d9c7ae2b093/internal/controller/pod_replication_controller.go#L78) but then almost always it gets overwritten to the previous state by this [code](https://github.com/mariadb-operator/mariadb-operator/blob/30f03700750b743cf4e10f005a800d9c7ae2b093/pkg/condition/ready.go#L94-L102). 

And naturally, this [prevents](https://github.com/mariadb-operator/mariadb-operator/blob/30f03700750b743cf4e10f005a800d9c7ae2b093/pkg/controller/replication/controller.go#L98) switchover from starting until statefulset becomes healthy and restarted master comes up configured, which costs us half a minute delay + delay when switchover tries to sync gtid and do read lock stuff. 

Looking at the `lastTransitionTime` of `PrimarySwitched` condition, I suspect that [code](https://github.com/mariadb-operator/mariadb-operator/blob/30f03700750b743cf4e10f005a800d9c7ae2b093/pkg/condition/ready.go#L94-L102) operated with the outdated object. 

```yaml
# initial state for the test, normal healthy cluster
conditions:
  - lastTransitionTime: '2024-10-12T14:02:39Z'
    message: Running
    reason: StatefulSetReady
    status: 'True'
    type: Ready
  - lastTransitionTime: '2024-10-12T14:01:10Z'
    message: Updated
    reason: Updated
    status: 'True'
    type: Updated
  - lastTransitionTime: '2024-10-12T14:02:39Z'
    message: Switchover complete
    reason: SwitchPrimary
    status: 'True'
    type: PrimarySwitched

# this is after master goes down, all nice 
conditions:
  - lastTransitionTime: '2024-10-12T14:09:44Z'
    message: Switching primary to 'mariadb-0'
    reason: SwitchPrimary
    status: 'False'
    type: Ready
  - lastTransitionTime: '2024-10-12T14:01:10Z'
    message: Updated
    reason: Updated
    status: 'True'
    type: Updated
  - lastTransitionTime: '2024-10-12T14:09:44Z'
    message: Switching primary to 'mariadb-0'
    reason: SwitchPrimary
    status: 'False'
    type: PrimarySwitched

# wtf PrimarySwitched condition is reverted to initial state
conditions:
  - lastTransitionTime: '2024-10-12T14:09:49Z'
    message: Not ready
    reason: StatefulSetNotReady
    status: 'False'
    type: Ready
  - lastTransitionTime: '2024-10-12T14:01:10Z'
    message: Updated
    reason: Updated
    status: 'True'
    type: Updated
  - lastTransitionTime: '2024-10-12T14:02:39Z'
    message: Switchover complete
    reason: SwitchPrimary
    status: 'True'
    type: PrimarySwitched
```

If I comment out this [code](https://github.com/mariadb-operator/mariadb-operator/blob/v0.0.33/pkg/condition/ready.go#L94-L102) all works as intended. But I doubt that you can accept such a PR :rofl: 

So what do you think, is it really race condition or something else at play? And if it is race condition, how to avoid it?
