### ISSUE TITLE
[Bug] ConfigMap no more mountable in maria-db object

### ISSUE THREAD

**Issue by bennyvar77** [mariadb-operator/mariadb-operator#931]
We mount a ConfigMap to mariadb object to have some scripts in place. This stopped working with the recent operator version 0.34.0

**Documentation**
- [x] I acknowledge that I have read the relevant [documentation](https://github.com/mariadb-operator/mariadb-operator/tree/main/docs).

```
  volumes:
    - name: scripts
      configMap:
        name: cgroup-db-scripts

  volumeMounts: 
    - name: scripts
      mountPath: /mnt/backup-scripts
```
![image](https://github.com/user-attachments/assets/aedaab22-b7b9-42a5-86f2-945f75fe4e02)

**Expected behaviour**
Mounting a ConfigMap should work as before

**Steps to reproduce the bug**

1. Deploy a semisync maria-db
2. Try to mount a ConfigMap in the container

**Environment details**:
- Kubernetes version: [1.29.7]
- Kubernetes distribution: [AKS]
- mariadb-operator version: [0.34.0]
- Galera data-plane version (init and agent): [nil]
- Install method: [static manifests]
