### ISSUE TITLE
[Bug] nodeAffinity no longer works after 0.31.0

### ISSUE THREAD

**Issue by kenlasko** [mariadb-operator/mariadb-operator#933]
In versions prior to 0.32.0, I am able to define the nodes I want my cluster pods to run on. Starting on 0.32.0, I am told that 
```.spec.affinity.nodeAffinity: field not declared in schema```. Reverting back to 0.31 resolves the issue. 

**Documentation**
- [X] I acknowledge that I have read the relevant [documentation](https://github.com/mariadb-operator/mariadb-operator/tree/main/docs).

**Describe the bug**
As noted above, if I try to install any version of the operator/CRDs higher than 0.31.0, ```nodeAffinity``` is not shown as supported. I need to specify my nodes on specific hardware that supports local-path.
```
apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb
  namespace: mariadb-galera
spec:
  rootPasswordSecretKeyRef:
    generate: false
    name: mariadb-passwords
    key: mariadb-root-password

  storage:
    volumeClaimTemplate:
      storageClassName: local-path
      resources:
        requests:
          storage: 18Gi
      accessModes:
      - ReadWriteOnce

  bootstrapFrom:
    volume:
      nfs:
        server: 192.168.1.3
        path: /backup/mariadb/bootstrap

  replicas: 3

  galera:
    enabled: true
    primary:
      podIndex: 0
      automaticFailover: true
    sst: mariabackup
    replicaThreads: 1
    config: 
      reuseStorageVolume: true
    agent:
      kubernetesAuth:
        enabled: true
      gracefulShutdownTimeout: 5s
    recovery:
      enabled: true
      minClusterSize: 1

  service:
    type: LoadBalancer
    metadata:
      labels:
        tailscale.com/proxy-class: "run-on-worker"
      annotations:
        io.cilium/lb-ipam-ips: 192.168.1.15
        tailscale.com/expose: 'true'
        tailscale.com/hostname: 'home-mariadb-galera'

  affinity:
    antiAffinityEnabled: true
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node-role.kubernetes.io/control-plane
            operator: DoesNotExist
          - key: kubernetes.io/arch
            operator: In
            values: 
            - 'amd64'

  tolerations:
    - key: "mariadb.mmontes.io/ha"
      operator: "Exists"
      effect: "NoSchedule"

  podDisruptionBudget:
    maxUnavailable: 66%

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      memory: 1Gi

  metrics:
    enabled: true
```

**Expected behaviour**
I expect that nodeAffinity is supported in all versions after 0.31.0

**Steps to reproduce the bug**

1. Install MariaDB operator v0.31.0 with MariaDB cluster definition as above. Note the successful deployment
2. Remove MariaDB operator and all CRDs
3. Install MariaDB operator v0.32.0 or higher with MariaDB cluster definition as above. Note the cluster fails to deploy due to the unsupported ```nodeAffinity``` definition.

**Environment details**:
- Kubernetes version: 1.31.1
- Kubernetes distribution: Talos 1.8.1
- mariadb-operator version: 0.32.0+
- Galera data-plane version (init and agent): 0.32.0+
- Install method: Helm via ArgoCD
