### ISSUE TITLE
[Bug] Resources settings for metrics.exporter are ignored

### ISSUE THREAD

**Issue by andreasgeisslerdt** [mariadb-operator/mariadb-operator#942]
**Documentation**
- [x] I acknowledge that I have read the relevant [documentation](https://github.com/mariadb-operator/mariadb-operator/tree/main/docs).

**Describe the bug**

In the MariaDB definition you can set the "resources" in the metrics section.
```
  metrics:
    enabled: true
    exporter:
      podSecurityContext:
        fsGroup: 10001
        runAsGroup: 10001
        runAsNonRoot: true
        runAsUser: 10001
        seccompProfile:
          type: RuntimeDefault
      resources:
        limits:
          cpu: 100m
          memory: 128Mi
        requests:
          cpu: 100m
          memory: 128Mi
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
            - CAP_NET_RAW
        privileged: false
        readOnlyRootFilesystem: true
```
but in the resulting deployment the resources settings are empty:
```
      containers:
        - args:
            - '--config.my-cnf=/etc/config/exporter.cnf'
          image: 'dockerhub.devops.telekom.de/prom/mysqld-exporter:v0.15.1'
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 9104
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: exporter
          ports:
            - containerPort: 9104
              name: metrics
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 9104
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
                - CAP_NET_RAW
            privileged: false
            readOnlyRootFilesystem: true
```

**Expected behaviour**

Resources settings are filled as defined in the MariaDB definition.

**Steps to reproduce the bug**

1. define MariaDB including metrics.resources
2. create MariaDB with Operator
3. Check deployment definition of Metrics

**Debug information**
- Related object:
```bash
kubectl get deployment <mariadb-metrics> -o yaml
```
- `mariadb-operator` logs. Set the `--log-level` to `debug` if needed.

**Environment details**:
- Kubernetes version: [v1.28.6]
- Kubernetes distribution: [Vanilla]
- mariadb-operator version: [0.34.0]
- Galera data-plane version (init and agent): [0.34.0]
- Install method: [helm]

**Additional context**
