### ISSUE TITLE
[Bug] MaxScale: The parameter 'config_sync_db' cannot be modified at runtime

### ISSUE THREAD

**Issue by maciej-p** [mariadb-operator/mariadb-operator#957]
It's not possible to set custom database for sync:

```
  config:
    sync:
      database: custom_database
```
mariadb-operator showing errors:
`maxscale: The parameter 'config_sync_db' cannot be modified at runtime`

It's because this parameter is static and can't be set via maxscale API: https://mariadb.com/kb/en/mariadb-maxscale-2302-mariadb-maxscale-configuration-guide/#config_sync_db only via config during start.

Workaround for this is set it in params also:
```
  config:
    sync:
      database: custom_database
    params:
      config_sync_db: custom_database
```

mariadb-operator version: 0.34.0
