### ISSUE TITLE
[Bug] Sidecar deployment only allows upto 9 values

### ISSUE THREAD

**Issue by bennyvar77** [mariadb-operator/mariadb-operator#961]
Thanks for the quick fix for #930 in version 0.35.0

However, the number of values allowed in the sidecar seems limited to a maximum of 9. 

**Documentation**
- [x] I acknowledge that I have read the relevant [documentation](https://github.com/mariadb-operator/mariadb-operator/tree/main/docs).

**Describe the bug**
I couldn't deploy the sidecar as in #930 
This is what i was able to collect from the operator logs
```
{"level":"error","ts":1729855879.0734446,"msg":"Observed a panic","controller":"mariadb","controllerGroup":"k8s.mariadb.com","controllerKind":"MariaDB","MariaDB":{"name":"infoplatform-db","namespace":"dev-ctraffic-infoplatform"},"namespace":"dev-ctraffic-infoplatform","name":"infoplatform-db","reconcileID":"66252591-e45a-4cea-8959-d8b365ad0331","panic":"runtime error: index out of range [9] with length 9","panicGoValue":"runtime.boundsError{x:9, y:9, signed:true, code:0x0}","stacktrace":"goroutine 738 [running]:\nk8s.io/apimachinery/pkg/util/runtime.logPanic({0x260a5b8, 0xc00f27d620}, {0x2100420, 0xc01f527a10})\n\t/go/pkg/mod/k8s.io/apimachinery@v0.31.1/pkg/util/runtime/runtime.go:107 +0xbc\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Reconcile.func1()\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:105 +0x112\npanic({0x2100420?, 0xc01f527a10?})\n\t/usr/local/go/src/runtime/panic.go:785 +0x132\ngithub.com/mariadb-operator/mariadb-operator/pkg/builder.(*Builder).buildContainer(0x0?, 0xc014136d88, 0xc000cfce60)\n\t/app/pkg/builder/container_builder.go:315 +0x51e\ngithub.com/mariadb-operator/mariadb-operator/pkg/builder.(*Builder).mariadbContainers(0xc000b329d8, 0xc014136d88, {0xc000137c30, 0x1, 0x1})\n\t/app/pkg/builder/container_builder.go:101 +0x8c8\ngithub.com/mariadb-operator/mariadb-operator/pkg/builder.(*Builder).mariadbPodTemplate(0xc000b329d8, 0xc014136d88, {0xc000137c30, 0x1, 0x1})\n\t/app/pkg/builder/pod_builder.go:167 +0x4a\ngithub.com/mariadb-operator/mariadb-operator/pkg/builder.(*Builder).BuildMariadbStatefulSet(0xc000b329d8, 0xc014136d88, {{0xc01f1f2c20?, 0xc014136d88?}, {0xc01eab4da0?, 0x0?}}, 0xc0177a1a10)\n\t/app/pkg/builder/statefulset_builder.go:83 +0x5a5\ngithub.com/mariadb-operator/mariadb-operator/internal/controller.(*MariaDBReconciler).reconcileStatefulSet(0xc000b64000, {0x260a5b8, 0xc00f27d620}, 0xc014136d88)\n\t/app/internal/controller/mariadb_controller.go:350 +0xfc\ngithub.com/mariadb-operator/mariadb-operator/internal/controller.(*MariaDBReconciler).Reconcile(0xc000b64000, {0x260a5b8, 0xc00f27d620}, {{{0xc00070cec0?, 0x2276208?}, {0xc0007d2710?, 0x100?}}})\n\t/app/internal/controller/mariadb_controller.go:203 +0x6fe\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Reconcile(0xc00f27d590?, {0x260a5b8?, 0xc00f27d620?}, {{{0xc00070cec0?, 0x0?}, {0xc0007d2710?, 0x0?}}})\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:116 +0xbf\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler(0x2623c60, {0x260a5f0, 0xc000897950}, {{{0xc00070cec0, 0x19}, {0xc0007d2710, 0xf}}})\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:303 +0x3a5\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem(0x2623c60, {0x260a5f0, 0xc000897950})\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:263 +0x20e\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2()\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:224 +0x85\ncreated by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2 in goroutine 195\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:220 +0x490\n","stacktrace":"github.com/mariadb-operator/mariadb-operator/pkg/builder.(*Builder).buildContainer\n\t/app/pkg/builder/container_builder.go:315\ngithub.com/mariadb-operator/mariadb-operator/pkg/builder.(*Builder).mariadbContainers\n\t/app/pkg/builder/container_builder.go:101\ngithub.com/mariadb-operator/mariadb-operator/pkg/builder.(*Builder).mariadbPodTemplate\n\t/app/pkg/builder/pod_builder.go:167\ngithub.com/mariadb-operator/mariadb-operator/pkg/builder.(*Builder).BuildMariadbStatefulSet\n\t/app/pkg/builder/statefulset_builder.go:83\ngithub.com/mariadb-operator/mariadb-operator/internal/controller.(*MariaDBReconciler).reconcileStatefulSet\n\t/app/internal/controller/mariadb_controller.go:350\ngithub.com/mariadb-operator/mariadb-operator/internal/controller.(*MariaDBReconciler).Reconcile\n\t/app/internal/controller/mariadb_controller.go:203\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Reconcile\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:116\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:303\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:263\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:224"}
{"level":"error","ts":1729855879.0735686,"msg":"Reconciler error","controller":"mariadb","controllerGroup":"k8s.mariadb.com","controllerKind":"MariaDB","MariaDB":{"name":"infoplatform-db","namespace":"dev-ctraffic-infoplatform"},"namespace":"dev-ctraffic-infoplatform","name":"infoplatform-db","reconcileID":"66252591-e45a-4cea-8959-d8b365ad0331","error":"panic: runtime error: index out of range [9] with length 9 [recovered]","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:316\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:263\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:224"}

```
"panic":"runtime error: index out of range [9] with length 9"

I tried the deployment with a reduced number of env values. It is successful with up to 9 values. Any additional value will produce the error mentioned above. 

**Expected behaviour**
It should be possible to use the sidecar without limitation of env values

**Steps to reproduce the bug**
1. deploy maria db in semi-syn
2. use the sidecar described in #930 

**Environment details**:
- Kubernetes version: [v1.29.7]
- Kubernetes distribution: [AKS]
- mariadb-operator version: [0.35.0]
- Galera data-plane version (init and agent): [nil]
- Install method: [static manifests]

**Comment by mmontes11** [comment]
Managed to reproduce with the following manifest, thanks for reporting:

```yaml
apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb
spec:
  # Additional init containers to be added to the MariaDB Pod.
  initContainers:
    - name: init
      image: busybox:1.36
      command:
        - /bin/sh
        - -c
        - 'echo "MY_ENV: $MY_ENV"'
      # Additional env added to the container. By default, all the MariaDB container environment is included.
      env:
        - name: MY_ENV
          value: "foo"

  # Additional sidecar containers to be added to the MariaDB Pod.
  sidecarContainers:
    - name: sidecar
      image: busybox:1.36
      args:
        - sleep
        - infinity
      # Additional env added to the container. By default, all the MariaDB container environment is included.
      env:
        - name: INSTANCE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['app.kubernetes.io/instance']
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb
              key: password
        - name: PMM_AGENT_LISTEN_PORT
          value: '7777'
        - name: PMM_AGENT_PORTS_MIN
          value: '30100'
        - name: PMM_AGENT_PORTS_MAX
          value: '30105'
        - name: PMM_AGENT_CONFIG_FILE
          value: /usr/local/percona/pmm2/config/pmm-agent.yaml
        - name: PMM_AGENT_SERVER_INSECURE_TLS
          value: '1'
        - name: PMM_AGENT_LISTEN_ADDRESS
          value: 0.0.0.0
        - name: PMM_AGENT_SETUP_NODE_NAME
          value: $(POD_NAMESPASE)--$(POD_NAME)
        - name: PMM_AGENT_SETUP_METRICS_MODE
          value: push
        - name: PMM_AGENT_SETUP
          value: '1'
        - name: PMM_AGENT_SETUP_FORCE
          value: '1'
        - name: PMM_AGENT_SETUP_NODE_TYPE
          value: container
        - name: PMM_AGENT_SETUP_REGION
          value: azure
        - name: PMM_AGENT_SETUP_AZ
          value: ams
        - name: PMM_AGENT_PRERUN_SCRIPT
          value: >-
            set -o errexit;
            pmm_args=();
            read -ra PMM_ADMIN_CUSTOM_PARAMS_ARRAY <<<"$PMM_ADMIN_CUSTOM_PARAMS";
            pmm_args+=("${PMM_ADMIN_CUSTOM_PARAMS_ARRAY[@]}");
            pmm-admin status --wait=10s;
            pmm-admin add mysql --service-name="$PMM_AGENT_SETUP_NODE_NAME" --skip-connection-check --query-source=perfschema --metrics-mode=push --username="$DB_USER" --password="$DB_PASSWORD" --cluster="$CLUSTER_NAME" --replication-set="$CLUSTER_NAME" "${pmm_args[@]}";
            pmm-admin annotate --service-name="$PMM_AGENT_SETUP_NODE_NAME" 'Service restarted'
        - name: PMM_AGENT_SIDECAR
          value: 'true'
        - name: PMM_AGENT_SIDECAR_SLEEP
          value: '5'

  # Additional volumes to be mounted by containers.
  volumes: 
    - name: tmp
      emptyDir:
        sizeLimit: 100Mi
    - name: mariadb-secret
      secret:
        secretName: mariadb
    - name: mariadb-configmap
      configMap:
        name: mariadb
  # Additional volumeMounts to be used by all containers. By default, all the MariaDB container volumeMounts are included.
  volumeMounts: 
    - name: tmp
      mountPath: /tmp
    - name: mariadb-secret
      mountPath: /mariadb-secret
    - name: mariadb-configmap
      mountPath: /mariadb-configmap

  storage:
    size: 1Gi
```
