### ISSUE TITLE
Allow to create additionalLabels in serviceMonitor section

### ISSUE THREAD

**Issue by jpicara** [mariadb-operator/mariadb-operator#966]
**Describe the bug**
After trying different configurations, I am not able to add additionalLabels inside the serviceMonitor which could allow me to monitor specific mariadb instances. Checking the documentation [we only have ](https://github.com/mariadb-operator/mariadb-operator/blob/main/docs/METRICS.md#servicemonitor) we only have the following possibilities
```
    serviceMonitor:
      prometheusRelease: kube-prometheus-stack
      jobLabel: mariadb-monitoring
      interval: 10s
      scrapeTimeout: 10s
    username: monitoring
    passwordSecretKeyRef:
      name: mariadb
      key: password
```
However it is not enough for me as I would like to add some other additionalLabels.
**Expected behaviour**

Being able to code something like:

```
    serviceMonitor:
      additionalLabels:
        release: "${values['global']['helmReleaseNamePrefix']}monitoring-platform"
      interval: 10s
      scrapeTimeout: 10s
    username: monitoring
    passwordSecretKeyRef:
      name: mariadb
      key: password
```
**Steps to reproduce the bug**

additionalLabels or selector matchLabels are not being taken into account

**Debug information**
- Related object events:
```bash
kubectl get events --field-selector involvedObject.name=<mariadb-resource-name>
kubectl get events --field-selector involvedObject.name=<backup-resource-name>
kubectl get events --field-selector involvedObject.name=<restore-resource-name>
```
- `mariadb-operator` logs. Set the `--log-level` to `debug` if needed.

**Environment details**:
- mariadb-operator version: 0.30.0
- Install method: [helm]

**Additional context**

**Comment by jpicara** [comment]
Hi,
I was able to fix the issue by using the label `prometheusRelease` to point into the Prometheus release just like
```   
        metrics:
          enabled: true
          serviceMonitor:
            prometheusRelease: "${values['global']['helmReleaseNamePrefix']}monitoring-platform"
```

However in my view, I still consider we should have `additionalLabels` in case we want to add some specific label to the serviceMonitor automatically created.

**Comment by bjw-s** [comment]
Adding a +1 here, as I am running in to something similar. Because $reasons we run multiple Prometheus instances in our cluster and we therefore have a need to specify which label to monitor on. Unfortunately using the `release` label doesn't work for us there since we already use that label for other purposes.

**Comment by Cyb3rDudu** [comment]
+1

**Comment by mmontes11** [comment]
Thanks for bringing this up. We could extend our `serviceMonitor` definition to have a map of `additionalLabels` as you suggested:

```yaml
    serviceMonitor:
      additionalLabels:
        environment: production
        region: eu-west1
``` 

Which will result in the following `ServiceMonitor` getting reconciled:

```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
spec:
  endpoints:
  - port: metrics
    relabelings:
     - targetLabel: environment
       replacement: production
``` 

See `ServiceMonitor` reference for further detail:
- https://prometheus-operator.dev/docs/api-reference/api/#monitoring.coreos.com/v1.ServiceMonitorSpec

Contributions are welcomed!

**Comment by mhanc** [comment]
> Thanks for bringing this up. We could extend our `serviceMonitor` definition to have a map of `additionalLabels` as you suggested:
> 
> serviceMonitor:
>    additionalLabels:
>       environment: production
>       region: eu-west1
> 
> Which will result in the following `ServiceMonitor` getting reconciled:
> 
> apiVersion: monitoring.coreos.com/v1
> kind: ServiceMonitor
> spec:
>   endpoints:
>   - port: metrics
>     relabelings:
>      - targetLabel: environment
>        replacement: production
>      - targetLabel: region
>        replacement: eu-west1
> 
> See `ServiceMonitor` reference for further detail:
> 
>     * https://prometheus-operator.dev/docs/api-reference/api/#monitoring.coreos.com/v1.ServiceMonitorSpec
> 
> 
> Contributions are welcomed!

@mmontes11 I am not sure if that is exactly what @jpicara requested. We are also missing the feature for `serviceMonitor.additionalLablels`, but we just need the result to end up in `metadata.labels` of `ServiceMonitor` object (e.g. to work similar as most of the bitnami charts `servicemonitor.labels`). 

Example:
```
serviceMonitor:
   additionalLabels:
      prometheus: prod
```

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    prometheus: prod
```
