### ISSUE TITLE
[Bug] livenessProbe no longer possible in sidecar

### ISSUE THREAD

**Issue by bennyvar77** [mariadb-operator/mariadb-operator#976]
Thank you very much for the very quick fixes. 
I was able to deploy the sidecar with the env values. However, it seems like livenessProbe is no longer supported

**Describe the bug**
I am using the sidecar described in #930 for monitoring. This also contains a livenessProbe which has been working until version 0.29.0. The current version 0.35.1 no longer supports this.

```
livenessProbe:
        httpGet:
          path: /local/Status
          port: 7777
          scheme: HTTP
        initialDelaySeconds: 60
        timeoutSeconds: 5
        periodSeconds: 10
        successThreshold: 1
        failureThreshold: 3
```
**Expected behaviour**
livenessProbe should be possible as before

**Steps to reproduce the bug**
1. Deploy a semisync maria db
2. Add the sidecar container as in #961 
3. Add the livenessProbe as described in this issue

**Environment details**:
- Kubernetes version: [v1.29.7]
- Kubernetes distribution: [AKS]
- mariadb-operator version: [0.35.1]
- Galera data-plane version (init and agent): [nil]
- Install method: [static manifests]
