### ISSUE TITLE
[Bug] config configmap name is constructed as "config-" + mariadb.Name

### ISSUE THREAD

**Issue by ngrigoriev** [mariadb-operator/mariadb-operator#99]
Generated mariadb pod is configured with configmap different from what I put in myCnfConfigMapKeyRef.name

My configuration

```
  myCnfConfigMapKeyRef:¬
    name: mariadb-my-cnf¬
    key: my.cnf¬
```

Resulting pod manifest:
```
  - configMap:
      defaultMode: 420
      items:
      - key: my.cnf
        path: my.cnf
      name: config-mariadb
    name: config
```

I think it comes from here:
```
❯ rg config-
controllers/mariadb_controller.go
401:            Name:      fmt.Sprintf("config-%s", mariadb.Name),
```

**Expected behaviour**

The name of the configmap is exactly the one provided as myCnfConfigMapKeyRef.name. Or the documentation explaining that the map name is built using "config-" prefix and the name or MariaDB object.

**Steps to reproduce the bug**

Configure MariaDB object as described above.

**Environment details**:
- Kubernetes version: 1.26.4
- mariadb-operator version: 0.0.12
- Install method: kustomize 
- Install flavour: custom
