### ISSUE TITLE
[Bug] Timeout waiting for reply of binlog

### ISSUE THREAD

**Issue by djjudas21** [mariadb-operator/mariadb-operator#992]
**Documentation**
- [x] I acknowledge that I have read the relevant [documentation](https://github.com/mariadb-operator/mariadb-operator/tree/main/docs).

**Describe the bug**

I am deploying a brand new master-slave replication cluster with MaxScale, based closely on [mariadb_replication_maxscale.yaml](https://github.com/mariadb-operator/mariadb-operator/blob/main/examples/manifests/mariadb_replication_maxscale.yaml)

Deployment works OK, but after a short time the MariaDB pods start printing this warning every few seconds:

```
2024-10-27 21:30:56 721 [Warning] Timeout waiting for reply of binlog (file: mariadb-bin.000002, pos: 525248), semi-sync up to file mariadb-bin.000002, position 525248.
2024-10-27 21:30:56 721 [Note] Semi-sync replication switched OFF.
2024-10-27 21:30:56 25 [Note] Semi-sync replication switched ON with slave (server_id: 11) at (mariadb-bin.000002, 525369)
```

MaxScale also prints errors like this periodically:

```
2024-10-28 16:01:56   warning: [mariadbmon] The current primary server 'mariadb-0' is no longer valid because it's not marked as master by the primary MaxScale, but there is no valid alternative to swap to.
2024-10-28 16:01:56   notice : Server changed state: mariadb-0[mariadb-0.mariadb-internal.mariadb.svc.cluster.local:3306]: new_slave. [Master, Running] -> [Slave, Running]
2024-10-28 16:01:56   error  : (ConfigManager); Failed to sync configuration: No valid servers in cluster 'mariadbmon-monitor'.
2024-10-28 16:01:58   notice : Server changed state: mariadb-0[mariadb-0.mariadb-internal.mariadb.svc.cluster.local:3306]: new_master. [Slave, Running] -> [Master, Running]
2024-10-28 16:02:16   error  : Monitor was unable to connect to server mariadb-2[mariadb-2.mariadb-internal.mariadb.svc.cluster.local:3306] : 'Host '10.1.71.193' is not allowed to connect to this MariaDB server'
2024-10-28 16:02:16   notice : Server changed state: mariadb-2[mariadb-2.mariadb-internal.mariadb.svc.cluster.local:3306]: slave_down. [Slave, Running] -> [Down]
```

The Operator repeatedly logs errors like this:

```
{"level":"error","ts":1730151863.8485818,"msg":"Reconciler error","controller":"maxscale","controllerGroup":"k8s.mariadb.com","controllerKind":"MaxScale","MaxScale":{"name":"mariadb-maxscale","namespace":"mariadb"},"namespace":"mariadb","name":"mariadb-maxscale","reconcileID":"88cf6343-2bed-497c-9aaf-911bc937fef7","error":"error reconciling phase Monitor: 1 error occurred:\n\t* error patching monitor: Patch \"http://mariadb-maxscale-0.mariadb-maxscale-internal.mariadb.svc.cluster.local:8989/monitors/mariadbmon-monitor\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)\n\n","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:316\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:263\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:224"}
```

It looks like the cluster is unstable and repeatedly failing the master role over. No workloads are running in this MariaDB cluster yet, it's just an empty cluster. The Kubernetes cluster was stable during this time, although one of the replicas got killed during its initial sync, and had to do a crash recovery.

```
[jonathan@latitude mariadb]$ kubectl get po
NAME                                        READY   STATUS    RESTARTS        AGE
mariadb-0                                   1/1     Running   0               24h
mariadb-1                                   1/1     Running   1 (24h ago)     24h
mariadb-2                                   1/1     Running   0               24h
mariadb-maxscale-0                          1/1     Running   0               24h
mariadb-maxscale-1                          1/1     Running   0               24h
mariadb-maxscale-2                          1/1     Running   2 (7h53m ago)   24h
mariadb-maxscale-metrics-fbcfd46c7-2s6xq    1/1     Running   0               24h
mariadb-metrics-9d94688b8-xvwvt             1/1     Running   0               24h
mariadb-operator-85774fc5f7-mjnld           1/1     Running   0               24h
mariadb-operator-webhook-5c57d59fbd-ljj5c   1/1     Running   0               24h
```

### Helm values used to deploy the MariaDB Operator:

```yaml
# -- Controller log level
logLevel: INFO

# -- Cluster DNS name
clusterName: cluster.local

ha:
  # -- Enable high availability
  enabled: false
  # -- Number of replicas
  replicas: 3

metrics:
  # -- Enable operator internal metrics. Prometheus must be installed in the cluster
  enabled: true
  serviceMonitor:
    # -- Enable controller ServiceMonitor
    enabled: true
    # -- Labels to be added to the controller ServiceMonitor
    additionalLabels: {}
    # release: kube-prometheus-stack
    # --  Interval to scrape metrics
    interval: 30s
    # -- Timeout if metrics can't be retrieved in given time interval
    scrapeTimeout: 25s

serviceAccount:
  # -- Specifies whether a service account should be created
  enabled: true
  # -- Automounts the service account token in all containers of the Pod
  automount: true
  # -- The name of the service account to use.
  # If not set and enabled is true, a name is generated using the fullname template
  name: ""

rbac:
  # -- Specifies whether RBAC resources should be created
  enabled: true

currentNamespaceOnly: false

# -- Resources to add to controller container
resources:
  requests:
    cpu: 10m
    memory: 128Mi

webhook:
  image:
    repository: ghcr.io/mariadb-operator/mariadb-operator
    pullPolicy: IfNotPresent
    # -- Image tag to use. By default the chart appVersion is used
    tag: ""
  imagePullSecrets: []
  ha:
    # -- Enable high availability
    enabled: false
    # -- Number of replicas
    replicas: 3
  cert:
    certManager:
      # -- Whether to use cert-manager to issue and rotate the certificate. If set to false, mariadb-operator's cert-controller will be used instead.
      enabled: true
      # -- Issuer reference to be used in the Certificate resource. If not provided, a self-signed issuer will be used.
      issuerRef: {}
       # -- Duration to be used in the Certificate resource,
      duration: ""
       # -- Renew before duration to be used in the Certificate resource.
      renewBefore: ""
    # -- Annotatioms to be added to webhook TLS secret.
    secretAnnotations: {}
    # -- Labels to be added to webhook TLS secret.
    secretLabels: {}
    # -- Path where the CA certificate will be mounted.
    caPath: /tmp/k8s-webhook-server/certificate-authority
    # -- Path where the certificate will be mounted.
    path: /tmp/k8s-webhook-server/serving-certs
  # -- Port to be used by the webhook server
  port: 9443
  # -- Expose the webhook server in the host network
  hostNetwork: false
  serviceMonitor:
    # -- Enable webhook ServiceMonitor. Metrics must be enabled
    enabled: true
    # -- Labels to be added to the webhook ServiceMonitor
    additionalLabels: {}
    # release: kube-prometheus-stack
    # --  Interval to scrape metrics
    interval: 30s
    # -- Timeout if metrics can't be retrieved in given time interval
    scrapeTimeout: 25s
  serviceAccount:
    # -- Specifies whether a service account should be created
    enabled: true
    # -- Automounts the service account token in all containers of the Pod
    automount: true
    # -- The name of the service account to use.
    # If not set and enabled is true, a name is generated using the fullname template
    name: ""
  # -- Extra arguments to be passed to the webhook entrypoint
  extrArgs: []
  # -- Annotations to add to webhook Pod
  podAnnotations: {}
  # -- Security context to add to webhook Pod
  podSecurityContext: {}
  # -- Security context to add to webhook container
  securityContext: {}
  # -- Resources to add to webhook container
  resources:
    requests:
      cpu: 1m
      memory: 8Mi

certController:
  # -- Specifies whether the cert-controller should be created.
  enabled: true
  image:
    repository: ghcr.io/mariadb-operator/mariadb-operator
    pullPolicy: IfNotPresent
    # -- Image tag to use. By default the chart appVersion is used
    tag: ""
  imagePullSecrets: []
  ha:
    # -- Enable high availability
    enabled: false
    # -- Number of replicas
    replicas: 3
  # -- CA certificate validity. It must be greater than certValidity.
  caValidity: 35064h
  # -- Certificate validity.
  certValidity: 8766h
  # -- Duration used to verify whether a certificate is valid or not.
  lookaheadValidity: 2160h
  # -- Requeue duration to ensure that certificate gets renewed.
  requeueDuration: 5m
  serviceMonitor:
    # -- Enable cert-controller ServiceMonitor. Metrics must be enabled
    enabled: true
    # -- Labels to be added to the cert-controller ServiceMonitor
    additionalLabels: {}
    # release: kube-prometheus-stack
    # --  Interval to scrape metrics
    interval: 30s
    # -- Timeout if metrics can't be retrieved in given time interval
    scrapeTimeout: 25s
  serviceAccount:
    # -- Specifies whether a service account should be created
    enabled: true
    # -- Automounts the service account token in all containers of the Pod
    automount: true
    # -- The name of the service account to use.
    # If not set and enabled is true, a name is generated using the fullname template
    name: ""
  # -- Extra arguments to be passed to the cert-controller entrypoint
  extrArgs: []
  # -- Annotations to add to cert-controller Pod
  podAnnotations: {}
  # -- Security context to add to cert-controller Pod
  podSecurityContext: {}
  # -- Security context to add to cert-controller container
  securityContext: {}
  # -- Resources to add to cert-controller container
  resources: 
    requests:
      cpu: 10m
      memory: 128Mi
```

### MariaDB CR applied to the cluster:

```yaml
apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb
  namespace: mariadb
spec:
  rootPasswordSecretKeyRef:
    name: mariadb
    key: root-password
  storage:
    size: 8Gi
  replicas: 3
  maxScale:
    enabled: true
    replicas: 3
    kubernetesService:
      type: ClusterIP
    guiKubernetesService:
      type: ClusterIP
    connection:
      secretName: mxs-repl-conn
      port: 3306
    metrics:
      enabled: true
  replication:
    enabled: true
  service:
    type: ClusterIP
  primaryService:
    type: ClusterIP
  secondaryService:
    type: ClusterIP
  myCnf: |
    [mariadb]
    bind-address=*
    default_storage_engine=InnoDB
    binlog_format=row
    innodb_autoinc_lock_mode=2
    innodb_buffer_pool_size=1024M
    max_allowed_packet=256M
#  timeZone: "Europe/London"
  resources:
    requests:
      cpu: 100m
      memory: 1280Mi
    limits:
      memory: 2Gi
  metrics:
    enabled: true
```

### Pod logs

I've captured logs from all 3 MariaDB replicas, the first MaxScale, and the Operator

* [mariadb-0.log](https://github.com/user-attachments/files/17549040/mariadb-0.log)
* [mariadb-1.log](https://github.com/user-attachments/files/17549041/mariadb-1.log)
* [mariadb-2.log](https://github.com/user-attachments/files/17549042/mariadb-2.log)
* [mariadb-maxscale-0.log](https://github.com/user-attachments/files/17549043/mariadb-maxscale-0.log)
* [mariadb-operator.log](https://github.com/user-attachments/files/17549145/mariadb-operator.log)

**Expected behaviour**
The MariaDB cluster should start up and be stable if the underlying Kubernetes cluster is stable

**Steps to reproduce the bug***
1. Deploy MariaDB Operator into `mariadb` namespace
2. Create `mariadb` CR in the `mariadb` namespace
3. Wait, and observe

**Environment details**:
- Kubernetes version: v1.31.1
- Kubernetes distribution: MicroK8s
- mariadb-operator version: 0.35.1
- Install method: helm + static manifests

**Additional context**
I ran into this bug on OpenShift last week, but couldn't be sure if it was OpenShift-specific. This week I deployed the same CR on MicroK8s and reproduced the same bug.

I spoke to @mariadb-pieterhumphrey today and I understand the maturity of the master-slave replication deployment is not as stable as the Galera deployment. I thought it was worth reporting :slightly_smiling_face: I'm going to tear this test cluster down for now but please let me know if you want me to redeploy it to run tests etc.
